### ISSUE TITLE
lshw.py lshw -numeric command fails 

### ISSUE THREAD

**Issue by kyle-ibm** [avocado-framework-tests/avocado-misc-tests#1376]
Looks like a false fail as the lshw -numeric command completes successfully but script still says fail
```
019-10-08 10:54:53,091 process L0714 INFO | Command 'pseries_platform' finished with 0 after 0.0232059955597s
2019-10-08 10:54:53,094 process L0626 INFO | Running 'lshw -numeric | grep HCI | cut -d':' -f3'
2019-10-08 10:54:54,212 process L0458 DEBUG| [stdout] 8241]
2019-10-08 10:54:54,212 process L0714 INFO | Command 'lshw -numeric | grep HCI | cut -d':' -f3' finished with 0 after 1.11562609673s
2019-10-08 10:54:54,213 process L0458 DEBUG| [stdout] 2]
2019-10-08 10:54:54,213 process L0458 DEBUG| [stdout] 3]
2019-10-08 10:54:54,214 lshw L0051 INFO | Failed command: lshw -numeric | grep HCI | cut -d':' -f3
2019-10-08 10:54:54,214 stacktrace L0041 ERROR|
2019-10-08 10:54:54,214 stacktrace L0044 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py:844
2019-10-08 10:54:54,215 stacktrace L0047 ERROR| Traceback (most recent call last):
2019-10-08 10:54:54,215 stacktrace L0047 ERROR| File "/root/tests/tests/avocado-misc-tests/ras/lshw.py", line 215, in test_lshw_options
2019-10-08 10:54:54,215 stacktrace L0047 ERROR| self.error_check()
2019-10-08 10:54:54,215 stacktrace L0047 ERROR| File "/root/tests/tests/avocado-misc-tests/ras/lshw.py", line 52, in error_check
2019-10-08 10:54:54,215 stacktrace L0047 ERROR| self.fail("lshw: Failed commands are: %s" % self.fail_cmd)
2019-10-08 10:54:54,215 stacktrace L0047 ERROR| File "/usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py", line 1030, in fail
2019-10-08 10:54:54,215 stacktrace L0047 ERROR| raise exceptions.TestFail(message)
2019-10-08 10:54:54,215 stacktrace L0047 ERROR| TestFail: lshw: Failed commands are: ["lshw -numeric | grep HCI | cut -d':' -f3"]
2019-10-08 10:54:54,216 stacktrace L0048 ERROR|
```
System information:
Host Kernel Build: 4.14.0-115.13.1.el7a.ppc64le
Host OS: Red Hat Enterprise Linux Server 7.6 (Maipo)

**Comment by alfredyswu** [comment]
Update manually test log

```
[root@mihawk-sut1-nvmeg4 temp]# lshw -numeric | grep HCI | cut -d':' -f3
8241]
2]
3]
[root@mihawk-sut1-nvmeg4 temp]# echo $?
0
[root@mihawk-sut1-nvmeg4 temp]#
```

**Comment by naveen538** [comment]
@kyle-ibm Have you tested with https://github.com/avocado-framework-tests/avocado-misc-tests/blob/py2-lts/ras/lshw.py ??

If not please verify on it...

**Comment by alfredyswu** [comment]
Retest with latest version. Result all PASS

PASS 01-lshw.py:Lshwrun.test_lshw
PASS 02-lshw.py:Lshwrun.test_lshw_short
PASS 03-lshw.py:Lshwrun.test_lshw_class
PASS 04-lshw.py:Lshwrun.test_lshw_verification
PASS 05-lshw.py:Lshwrun.test_gen_rep
PASS 06-lshw.py:Lshwrun.test_businfo
PASS 07-lshw.py:Lshwrun.test_sanitize
PASS 08-lshw.py:Lshwrun.test_prod_id_serial
PASS 09-lshw.py:Lshwrun.test_lshw_options
PASS 10-lshw.py:Lshwrun.test_lshw_notime

**Comment by PraveenPenguin** [comment]
@alfredyswu thanks for validating so closing it , feel free to reopen if still face any issue
