### ISSUE TITLE
memtester.py : bad physaddrbase arg; does not start on page boundary

### ISSUE THREAD

**Issue by alfredyswu** [avocado-framework-tests/avocado-misc-tests#1384]
When run memtester.py, memtester failed for address 1048576 ( default yaml file )
And response "bad physaddrbase arg; does not start on page boundary" and Usage. Seems wrong parameter.

# In job.log :
2019-11-05 18:09:43,697 parameters       L0146 DEBUG| PARAMS (key=device, path=*, default=/dev/mem) => '/dev/mem'
2019-11-05 18:09:43,697 process          L0626 INFO | Running './memtester -p 1048576 -d /dev/mem 1G 1'
2019-11-05 18:09:43,703 process          L0458 DEBUG| [stdout] memtester version 4.3.0 (64-bit)
2019-11-05 18:09:43,703 process          L0458 DEBUG| [stdout] Copyright (C) 2001-2012 Charles Cazabon.
2019-11-05 18:09:43,704 process          L0458 DEBUG| [stdout] Licensed under the GNU General Public License version 2 (only).
2019-11-05 18:09:43,704 process          L0458 DEBUG| [stdout]
2019-11-05 18:09:43,704 process          L0458 DEBUG| [stdout] pagesize is 65536
2019-11-05 18:09:43,704 process          L0458 DEBUG| [stdout] pagesizemask is 0xffffffffffff0000
2019-11-05 18:09:43,704 process          L0714 INFO | Command './memtester -p 1048576 -d /dev/mem 1G 1' finished with 1 after 0.00332093238831s
2019-11-05 18:09:43,705 process          L0458 DEBUG| [stderr] bad physaddrbase arg; does not start on page boundary
2019-11-05 18:09:43,705 process          L0458 DEBUG| [stderr]
2019-11-05 18:09:43,706 process          L0458 DEBUG| [stderr] Usage: ./memtester [-p physaddrbase [-d device]] <mem>[B|K|M|G] [loops]
2019-11-05 18:09:43,706 stacktrace       L0041 ERROR|
2019-11-05 18:09:43,706 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py:844
2019-11-05 18:09:43,707 stacktrace       L0047 ERROR| Traceback (most recent call last):
2019-11-05 18:09:43,707 stacktrace       L0047 ERROR|   File "/root/tests/tests/alfred_1105/avocado-misc-tests/memory/memtester.py", line 77, in test
2019-11-05 18:09:43,707 stacktrace       L0047 ERROR|     self.fail("memtester failed for address %s" % phyaddr)
2019-11-05 18:09:43,707 stacktrace       L0047 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_framework-69.0-py2.7.egg/avocado/core/test.py", line 1030, in fail
2019-11-05 18:09:43,707 stacktrace       L0047 ERROR|     raise exceptions.TestFail(message)
2019-11-05 18:09:43,707 stacktrace       L0047 ERROR| TestFail: memtester failed for address 1048576

[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3808570/job.log)

# Manually test result:
[root@mihawk-sut1-nvmeg4 memtester-master]# ./memtester -p 0x100000 -d /dev/mem 10G 1
memtester version 4.3.0 (64-bit)
Copyright (C) 2001-2012 Charles Cazabon.
Licensed under the GNU General Public License version 2 (only).

pagesize is 65536
pagesizemask is 0xffffffffffff0000
want 10240MB (10737418240 bytes)
failed to mmap /dev/mem for physical memory: Operation not permitted
[root@mihawk-sut1-nvmeg4 memtester-master]#
[root@mihawk-sut1-nvmeg4 memtester-master]# ./memtester -p 1048576 -d /dev/mem 10G 1
memtester version 4.3.0 (64-bit)
Copyright (C) 2001-2012 Charles Cazabon.
Licensed under the GNU General Public License version 2 (only).

pagesize is 65536
pagesizemask is 0xffffffffffff0000
bad physaddrbase arg; does not start on page boundary

Usage: ./memtester [-p physaddrbase [-d device]] <mem>[B|K|M|G] [loops]
[root@mihawk-sut1-nvmeg4 memtester-master]#

**Comment by alfredyswu** [comment]
Upload sosreport for reference:
[sosreport-mihawk-sut2-sas16-_memtester_2019-11-01-fvyjuqw.tar.xz.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/3808766/sosreport-mihawk-sut2-sas16-_memtester_2019-11-01-fvyjuqw.tar.xz.zip)

**Comment by kyle-ibm** [comment]
@harish-24 Hi Harish, did you get a chance to take a look?

**Comment by harish-24** [comment]
@alfredyswu @kyle-ibm These inputs are only samples values as the `NOTE` in yaml file specifies the same. FWIW, I will send in a patch fixing the yaml inputs that does not affect the sample runs.

**Comment by kyle-ibm** [comment]
how do we get the page boundary address?

**Comment by harish-24** [comment]
It depends on the system being used. You can refer to `/proc/iomem` for start and end ranges. Depending on the page size you can utilize those addresses.

**Comment by kyle-ibm** [comment]
not sure if i'm doing this correctly
```
# cat /proc/iomem
00000000-2fffffffff : System RAM
4000000000-47ffffffff : System RAM
200000000000-203fffffffff : System RAM
6000000000000-6003fbfffffff : /pciex@600c3c0000000
6004000000000-6007f7fffffff : /pciex@600c3c0100000
  6004000000000-6007f7ff0ffff : PCI Bus 0001:01
    6004000000000-6007f7ff0ffff : PCI Bus 0001:02
...
...
# ./memtester -p 0x6000000000000 -d /dev/mem 1G 1
memtester version 4.3.0 (64-bit)
Copyright (C) 2001-2012 Charles Cazabon.
Licensed under the GNU General Public License version 2 (only).

pagesize is 65536
pagesizemask is 0xffffffffffff0000
want 1024MB (1073741824 bytes)
Loop 1/1:
  Stuck Address       : testing   0FAILURE: possible bad address line at physical address 0x6000000000000.
Skipping to next test...
  Random Value        : ok
  Compare XOR         : ok
  Compare SUB         : ok
  Compare MUL         : ok
  Compare DIV         : ok
  Compare OR          : ok
  Compare AND         : ok
  Sequential Increment: ok
  Solid Bits          : ok         
  Block Sequential    : ok         
  Checkerboard        : ok         
  Bit Spread          : ok         
  Bit Flip            : ok         
  Walking Ones        : ok         
  Walking Zeroes      : testing  67
(test still going after 12+hrs)
```
Is that a real failure or did i choose a wrong address again?

**Comment by harish-24** [comment]
From manpage:
```
-p PHYSADDR\fR
tells memtester to test a specific region of memory starting at physical
address PHYSADDR (given in hex), by mmap(2)ing a device specified by the
-d option (below, or /dev/mem by default).  This is mostly of use to hardware
developers, for testing memory-mapped I/O devices and similar.
Note that the memory region will be overwritten during testing, so it is not
safe to specify memory which is allocated for the system or for other
applications; doing so will cause them to crash.  If you absolutely must test
a particular region of actual physical memory, arrange to have that memory
allocated by your test software, and hold it in this allocated state, then
run memtester on it with this option.
```

**Comment by alfredyswu** [comment]
Retest with Nov 25 version, result is pass
PASS 1-memtester.py:Memtester.test;device-physaddr-c521

**Comment by PraveenPenguin** [comment]
@alfredyswu thanks for testing this patch , closing
