### ISSUE TITLE
lv_setup.py fails to get lv size when multiple lv_disks given (no support for multiple disks)

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1596]
2020-03-28 04:10:37,771 sysinfo          L0105 DEBUG| Not logging /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor (file does not exist)
2020-03-28 04:10:37,773 sysinfo          L0173 DEBUG| Not logging 'dmidecode' (command 'dmidecode' was not found)
2020-03-28 04:10:37,804 sysinfo          L0105 DEBUG| Not logging /proc/pci (file does not exist)
2020-03-28 04:10:37,804 parameters       L0143 DEBUG| PARAMS (key=lv_disks, path=*, default=None) => '/dev/sdb /dev/sdc /dev/sdd /dev/sde'
2020-03-28 04:10:37,804 parameters       L0143 DEBUG| PARAMS (key=vg_name, path=*, default=avocado_vg) => 'avocado_vg'
2020-03-28 04:10:37,805 parameters       L0143 DEBUG| PARAMS (key=lv_name, path=*, default=avocado_lv) => 'avocado_lv'
2020-03-28 04:10:37,805 parameters       L0143 DEBUG| PARAMS (key=fs, path=*, default=ext4) => 'ext2'
2020-03-28 04:10:38,162 process          L0436 DEBUG| [stderr]   Volume group "avocado_vg" not found
2020-03-28 04:10:38,162 process          L0436 DEBUG| [stderr]   Cannot process volume group avocado_vg
2020-03-28 04:10:38,295 process          L0686 INFO | Command 'lvdisplay avocado_vg' finished with 5 after 0.16666817665100098s
2020-03-28 04:10:38,297 process          L0604 INFO | Running 'fdisk -l /dev/sdb /dev/sdc /dev/sdd /dev/sde'
2020-03-28 04:10:38,339 process          L0436 DEBUG| [stdout] Disk /dev/sdb: 279.4 GiB, 299999997952 bytes, 73242187 sectors
2020-03-28 04:10:38,339 process          L0686 INFO | Command 'fdisk -l /dev/sdb /dev/sdc /dev/sdd /dev/sde' finished with 0 after 0.040235280990600586s
2020-03-28 04:10:38,340 process          L0436 DEBUG| [stdout] Units: sectors of 1 * 4096 = 4096 bytes
2020-03-28 04:10:38,340 process          L0436 DEBUG| [stdout] Sector size (logical/physical): 4096 bytes / 4096 bytes
2020-03-28 04:10:38,340 process          L0436 DEBUG| [stdout] I/O size (minimum/optimal): 4096 bytes / 4096 bytes
2020-03-28 04:10:38,341 process          L0436 DEBUG| [stdout]
2020-03-28 04:10:38,341 process          L0436 DEBUG| [stdout]
2020-03-28 04:10:38,341 process          L0436 DEBUG| [stdout] Disk /dev/sdc: 558.9 GiB, 600127266816 bytes, 146515446 sectors
2020-03-28 04:10:38,341 process          L0436 DEBUG| [stdout] Units: sectors of 1 * 4096 = 4096 bytes
2020-03-28 04:10:38,341 process          L0436 DEBUG| [stdout] Sector size (logical/physical): 4096 bytes / 4096 bytes
2020-03-28 04:10:38,342 process          L0436 DEBUG| [stdout] I/O size (minimum/optimal): 4096 bytes / 4096 bytes
2020-03-28 04:10:38,342 process          L0436 DEBUG| [stdout]
2020-03-28 04:10:38,342 process          L0436 DEBUG| [stdout]
2020-03-28 04:10:38,342 process          L0436 DEBUG| [stdout] Disk /dev/sdd: 558.9 GiB, 600127266816 bytes, 146515446 sectors
2020-03-28 04:10:38,342 process          L0436 DEBUG| [stdout] Units: sectors of 1 * 4096 = 4096 bytes
2020-03-28 04:10:38,343 process          L0436 DEBUG| [stdout] Sector size (logical/physical): 4096 bytes / 4096 bytes
2020-03-28 04:10:38,343 process          L0436 DEBUG| [stdout] I/O size (minimum/optimal): 4096 bytes / 4096 bytes
2020-03-28 04:10:38,343 process          L0436 DEBUG| [stdout]
2020-03-28 04:10:38,343 process          L0436 DEBUG| [stdout]
2020-03-28 04:10:38,344 process          L0436 DEBUG| [stdout] Disk /dev/sde: 279.4 GiB, 299999997952 bytes, 73242187 sectors
2020-03-28 04:10:38,344 process          L0436 DEBUG| [stdout] Units: sectors of 1 * 4096 = 4096 bytes
2020-03-28 04:10:38,344 process          L0436 DEBUG| [stdout] Sector size (logical/physical): 4096 bytes / 4096 bytes
2020-03-28 04:10:38,344 process          L0436 DEBUG| [stdout] I/O size (minimum/optimal): 4096 bytes / 4096 bytes
2020-03-28 04:10:38,362 stacktrace       L0039 ERROR|
2020-03-28 04:10:38,362 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-76.0-py3.6.egg/avocado/core/test.py:849
2020-03-28 04:10:38,363 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-03-28 04:10:38,363 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/lvsetup.py", line 97, in setUp
2020-03-28 04:10:38,363 stacktrace       L0045 ERROR|     self.lv_size = int(lv_utils.get_diskspace(self.disk)) / 2330168
2020-03-28 04:10:38,363 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-76.0-py3.6.egg/avocado/utils/lv_utils.py", line 54, in get_diskspace
2020-03-28 04:10:38,363 stacktrace       L0045 ERROR|     raise LVException('Error in finding disk space')
2020-03-28 04:10:38,363 stacktrace       L0045 ERROR| avocado.utils.lv_utils.LVException: Error in finding disk space
2020-03-28 04:10:38,364 stacktrace       L0046 ERROR|
2020-03-28 04:10:38,364 test             L1030 ERROR| ERROR 01-avocado-misc-tests/io/disk/lvsetup.py:Lvsetup.test;ext2-bc3a -> TestSetupFail: Error in finding disk space
2020-03-28 04:10:38,365 test             L1019 INFO |

**Comment by narasimhan-v** [comment]
We need to handle the code path of getting disk size when multiple disks are given.

**Comment by Naresh-ibm** [comment]
@narasimhan-v  why do we multiple disk here?
I mean, are we using multiple disk to create any vg or lv?
OR
if you mean from CI/CR perspective, then better we change all other scripts too, for multiple disk support.

**Comment by narasimhan-v** [comment]
@Naresh-ibm There are certain tests like lvsetup, software raid, which are capable of having multiple disks in their native command line. It is not like we support it explicitly from the test.

**Comment by narasimhan-v** [comment]
https://github.com/avocado-framework/avocado/pull/3792

**Comment by abdhaleegit** [comment]
@narasimhan-v this is still open to support multiple disks ?

**Comment by narasimhan-v** [comment]
@abdhaleegit Yes, but that will take sometime to close. For now, it supports only single disk. Please change your input files accordingly temporarily

**Comment by abdhaleegit** [comment]
@narasimhan-v thanks

**Comment by narasimhan-v** [comment]
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1784
