### ISSUE TITLE
parallel_dd.py : avcado crashed when running the test

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1676]
```
23:20:41 INFO    : Running Host Tests Suite io_vfc_parallel_dd_parallel_dd
23:20:41 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/disk/parallel_dd.py -m /tmp/mux/io_vfc_parallel_dd_parallel_dd.yaml --force-job-id 233013e88c2c516c1d6e66704b920c11a1a35995  --job-results-dir /home/ioci/logs/io_vfc/results
/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/plugins/run.py:287: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast, keep-tmp and ignore-missing-references.
  FutureWarning)
JOB ID     : 233013e88c2c516c1d6e66704b920c11a1a35995
JOB LOG    : /home/ioci/logs/io_vfc/results/job-2020-05-03T23.20-233013e/job.log
[18563.058197] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)
[18563.587552] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)
 (1/3) avocado-misc-tests/io/disk/parallel_dd.py:ParallelDd.test;25600-12800-dd_roptions-dd_woptions-ext4-fs_dd_roptions-fs_dd_woptions-100-yes-98b5:  PASS (4.00 s)
[18565.950936] XFS (dm-0): Mounting V5 Filesystem
[18565.965205] XFS (dm-0): Ending clean mount
[18565.969220] xfs filesystem being mounted at /var/tmp/avocado_dj5th9aa/avocado_job_r_rn8obw/2-avocado-misc-tests_io_disk_parallel_dd.py_ParallelDd.test_25600-12800-dd_roptions-dd_woptions-xfs-fs_dd_roptions-fs_dd_woptions-100-yes-1cd9 supports timestamps until 2038 (0x7fffffff)
[18566.354011] XFS (dm-0): Unmounting Filesystem
[18566.383472] XFS (dm-0): Mounting V5 Filesystem
[18566.397454] XFS (dm-0): Ending clean mount
[18566.401213] xfs filesystem being mounted at /var/tmp/avocado_dj5th9aa/avocado_job_r_rn8obw/2-avocado-misc-tests_io_disk_parallel_dd.py_ParallelDd.test_25600-12800-dd_roptions-dd_woptions-xfs-fs_dd_roptions-fs_dd_woptions-100-yes-1cd9 supports timestamps until 2038 (0x7fffffff)
 (2/3) avocado-misc-tests/io/disk/parallel_dd.py:ParallelDd.test;25600-12800-dd_roptions-dd_woptions-xfs-fs_dd_roptions-fs_dd_woptions-100-yes-1cd9:  PASS (2.78 s)
 (3/3) avocado-misc-tests/io/disk/parallel_dd.py:ParallelDd.test;25600-12800-dd_roptions-dd_woptions-btrfs-fs_dd_roptions-fs_dd_woptions-100-yes-5ba3:  CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.20 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB TIME   : 7.19 s
JOB HTML   : /home/ioci/logs/io_vfc/results/job-2020-05-03T23.20-233013e/results.html
Avocado crashed unexpectedly: [Errno 16] Device or resource busy: '2-avocado-misc-tests_io_disk_parallel_dd.py_ParallelDd.test_25600-12800-dd_roptions-dd_woptions-xfs-fs_dd_roptions-fs_dd_woptions-100-yes-1cd9
```

```
Avocado crashed:
Traceback (most recent call last):
  File "/usr/local/bin/avocado", line 4, in <module>
    __import__('pkg_resources').run_script('avocado-framework==78.0', 'avocado')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/EGG-INFO/scripts/avocado", line 78, in <module>
    sys.exit(app.run())
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/app.py", line 97, in run
    return method(self.parser.config)
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/plugins/run.py", line 315, in run
    job_instance)
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/job.py", line 217, in __exit__
    self.cleanup()
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/job.py", line 696, in cleanup
    shutil.rmtree(self.tmpdir)
  File "/usr/lib64/python3.6/shutil.py", line 486, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.6/shutil.py", line 428, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib64/python3.6/shutil.py", line 426, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '2-avocado-misc-tests_io_disk_parallel_dd.py_ParallelDd.test_25600-12800-dd_roptions-dd_woptions-xfs-fs_dd_roptions-fs_dd_woptions-100-yes-1cd9'

```

**Comment by abdhaleegit** [comment]
@PraveenPenguin do you have any hint here ? smruti is unable to sove this

**Comment by PraveenPenguin** [comment]
ah @abdhaleegit i did not check this, will check and try to fix

**Comment by narasimhan-v** [comment]
@smruti77 do you have any system setup or job.log that might help here ?

**Comment by smruti77** [comment]
@narasimhan-v have the system

**Comment by narasimhan-v** [comment]
Please ping me the credentials via slack

**Comment by smruti77** [comment]
ok
