### ISSUE TITLE
[CI] Add sriov logical support in DLPAR.py test case 

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1690]
currently the test cases io/pci/dlpar.py  has only support for eth devices,, please add support for sriov devices too
```
        cmd = 'lshwres **-r io** -m %s \
               --rsubtype slot --filter lpar_names= %s \
               | grep -i %s' % (server, lpar, drc_index)

for sriov it should be `-r sriov'
```

**Comment by abdhaleegit** [comment]
```
2020-05-04 18:31:33,247 dlpar            L0161 INFO | Running the command on hmc lshwres -r io -m ltc-zz3 --rsubtype slot --filter lpar_names=None -F lpar_id
2020-05-04 18:31:33,356 parameters       L0143 DEBUG| PARAMS (key=pci_device, path=*, default=None) => 28807260.0
2020-05-04 18:31:33,356 parameters       L0143 DEBUG| PARAMS (key=num_of_dlpar, path=*, default=1) => 10
2020-05-04 18:31:33,356 stacktrace       L0039 ERROR|
2020-05-04 18:31:33,357 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:851
2020-05-04 18:31:33,358 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-04 18:31:33,358 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/dlpar.py", line 94, in setUp
2020-05-04 18:31:33,358 stacktrace       L0045 ERROR|     self.cancel("Failed to get the location code for the pci device")
2020-05-04 18:31:33,358 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 1085, in cancel
2020-05-04 18:31:33,358 stacktrace       L0045 ERROR|     raise exceptions.TestCancel(message)
2020-05-04 18:31:33,358 stacktrace       L0045 ERROR| avocado.core.exceptions.TestCancel: Failed to get the location code for the pci device
2020-05-04 18:31:33,358 stacktrace       L0046 ERROR|
2020-05-04 18:31:33,659 test             L1034 ERROR| CANCEL 2-avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_drmgr_pci;run-f764 -> TestCancel: Failed to get the location code for the pci device
2020-05-04 18:31:33,659 test             L1023 INFO |
2020-05-04 18:31:33,681 sysinfo          L0409 INFO | Commands configured by file: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/etc/avocado/sysinfo/commands
2020-05-04 18:31:33,682 sysinfo          L0420 INFO | Files configured by file: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/etc/avocado/sysinfo/files
2020-05-04 18:31:33,683 sysinfo          L0440 INFO | Profilers configured by file: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/etc/avocado/sysinfo/profilers
2020-05-04 18:31:33,691 test             L0398 INFO | INIT 3-avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_drmgr_phb;run-f764
2020-05-04 18:31:33,692 parameters       L0143 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
2020-05-04 18:31:33,692 test             L0430 DEBUG| Test metadata:
2020-05-04 18:31:33,693 test             L0432 DEBUG|   filename: /home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/dlpar.py
2020-05-04 18:31:33,693 test             L0438 DEBUG|   teststmpdir: /var/tmp/avocado_axtonpc2
2020-05-04 18:31:33,693 test             L0439 DEBUG|   workdir: /var/tmp/avocado_a8t4xa0d/avocado_job_ygdkd6fq/3-avocado-misc-tests_io_pci_dlpar.py_DlparPci.test_drmgr_phb_run-f764

```

**Comment by vaishnavibhat** [comment]
Working on enabling DLPAR for sriov adapters.  Steps to be followed

List the logical ports: 
---------------------------
lshwres -r sriov --rsubtype logport -m ltcfleet2 --level eth --filter "lpar_names=ltcfleet2-lp19"

Remove a logical port:
---------------------------
 chhwres -r sriov -m ltcfleet2 --rsubtype logport -o r --id 19 -a "adapter_id=6,logical_port_id=27018012"

Add back the same logical port:
---------------------------------
chhwres -r sriov -m ltcfleet2 --rsubtype logport -o a --id 19 -a "phys_port_id=0,adapter_id=6,logical_port_id=27018012,logical_port_type=eth"
