### ISSUE TITLE
veth/austin : ethtool, network_test :  ERROR: Link up of interface is taking longer than 120 seconds

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1691]
```
2020-05-04 16:22:45,409 process          L0686 INFO | Command 'cat /sys/class/net/env3/operstate' finished with 0 after 0.001605987548828125s
2020-05-04 16:22:46,413 process          L0604 INFO | Running 'cat /sys/class/net/env3/operstate'
2020-05-04 16:22:46,415 process          L0436 DEBUG| [stdout] unknown
2020-05-04 16:22:46,416 process          L0686 INFO | Command 'cat /sys/class/net/env3/operstate' finished with 0 after 0.0014417171478271484s
2020-05-04 16:22:47,420 process          L0604 INFO | Running 'cat /sys/class/net/env3/operstate'
2020-05-04 16:22:47,422 process          L0436 DEBUG| [stdout] unknown
2020-05-04 16:22:47,423 process          L0686 INFO | Command 'cat /sys/class/net/env3/operstate' finished with 0 after 0.0015571117401123047s
2020-05-04 16:22:48,427 process          L0604 INFO | Running 'cat /sys/class/net/env3/operstate'
2020-05-04 16:22:48,430 process          L0436 DEBUG| [stdout] unknown
2020-05-04 16:22:48,431 process          L0686 INFO | Command 'cat /sys/class/net/env3/operstate' finished with 0 after 0.0016548633575439453s
2020-05-04 16:22:49,433 stacktrace       L0039 ERROR|
2020-05-04 16:22:49,433 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:891
2020-05-04 16:22:49,434 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-04 16:22:49,434 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 845, in _run_avocado
2020-05-04 16:22:49,434 stacktrace       L0045 ERROR|     self.setUp()
2020-05-04 16:22:49,434 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/ethtool_test.py", line 85, in setUp
2020-05-04 16:22:49,434 stacktrace       L0045 ERROR|     self.cancel("Link up of interface is taking longer than 120s")
2020-05-04 16:22:49,435 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 1085, in cancel
2020-05-04 16:22:49,435 stacktrace       L0045 ERROR|     raise exceptions.TestCancel(message)
2020-05-04 16:22:49,435 stacktrace       L0045 ERROR| avocado.core.exceptions.TestCancel: Link up of interface is taking longer than 120s
2020-05-04 16:22:49,435 stacktrace       L0045 ERROR|
2020-05-04 16:22:49,435 stacktrace       L0045 ERROR| During handling of the above exception, another exception occurred:
2020-05-04 16:22:49,436 stacktrace       L0045 ERROR|
2020-05-04 16:22:49,436 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-04 16:22:49,436 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/ethtool_test.py", line 181, in tearDown
2020-05-04 16:22:49,436 stacktrace       L0045 ERROR|     self.interface_state_change(self.iface, "up", "yes")
2020-05-04 16:22:49,436 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/ethtool_test.py", line 109, in interface_state_change
2020-05-04 16:22:49,436 stacktrace       L0045 ERROR|     self.fail("Link up of interface is taking longer than 120s")
2020-05-04 16:22:49,437 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 1054, in fail
2020-05-04 16:22:49,437 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-05-04 16:22:49,437 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: Link up of interface is taking longer than 120s
2020-05-04 16:22:49,437 stacktrace       L0046 ERROR|
2020-05-04 16:22:49,438 test             L1034 ERROR| CANCEL 16-avocado-misc-tests/io/net/ethtool_test.py:Ethtool.test_ethtool;Get-phy-tunable-eee4 -> TestCancel: Link up of interface is taking longer than 120s
2020-05-04 16:22:49,438 test             L1023 INFO |
2020-05-04 16:22:49,452 job              L0620 INFO | Test results available in /home/ioci/logs/io_veth/results/job-2020-05-04T15.17-0c8753d

```

**Comment by abdhaleegit** [comment]
Looks like it is because the interface state is not changing to UP state even though the links are up

**Comment by abdhaleegit** [comment]
this is a real bug with the code, closing this
