### ISSUE TITLE
Network_config.py : tests mtu_check, seed_check, duplex_check failed 

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1704]
```
2020-05-06 22:57:28,376 process          L0604 INFO | Running 'ip -4 -j address show env3'
2020-05-06 22:57:28,380 process          L0436 DEBUG| [stdout] [{},{},{"ifindex":3,"ifname":"env3","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":1500,"qdisc":"fq_codel","operstate":"UNKNOWN","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"100.10.10.204","prefixlen":24,"scope":"global","label":"env3","valid_life_time":4294967295,"preferred_life_time":4294967295}]},{}]
2020-05-06 22:57:28,380 process          L0686 INFO | Command 'ip -4 -j address show env3' finished with 0 after 0.00152587890625s
2020-05-06 22:57:28,385 process          L0604 INFO | Running 'ip link set env3 up'
2020-05-06 22:57:28,388 process          L0686 INFO | Command 'ip link set env3 up' finished with 0 after 0.0011587142944335938s
2020-05-06 22:57:28,389 process          L0604 INFO | Running 'basename /sys/class/net/env3/device/driver/module/drivers/*'
2020-05-06 22:57:28,392 process          L0436 DEBUG| [stdout] vio:ibmveth
2020-05-06 22:57:28,393 process          L0686 INFO | Command 'basename /sys/class/net/env3/device/driver/module/drivers/*' finished with 0 after 0.0020182132720947266s
2020-05-06 22:57:28,395 process          L0604 INFO | Running 'lscfg -vl env3'
2020-05-06 22:57:28,408 process          L0436 DEBUG| [stdout]   l-lan env3       U9009.42A.13C6F1W-V6-C3-T1
2020-05-06 22:57:28,409 process          L0436 DEBUG| [stdout]                                          Interpartition Logical LAN
2020-05-06 22:57:28,409 process          L0436 DEBUG| [stdout]         Machine Type-Model........network
2020-05-06 22:57:28,410 process          L0436 DEBUG| [stdout]         Network Address...........8eb25d3a1d03
2020-05-06 22:57:28,410 process          L0686 INFO | Command 'lscfg -vl env3' finished with 0 after 0.013132095336914062s
2020-05-06 22:57:28,410 process          L0436 DEBUG| [stdout]         Location Code.(YL)........U9009.42A.13C6F1W-V6-C3-T1
2020-05-06 22:57:28,411 process          L0436 DEBUG| [stdout]
2020-05-06 22:57:28,412 process          L0604 INFO | Running 'lsslot'
2020-05-06 22:57:28,476 process          L0436 DEBUG| [stdout] # Slot                     Description       Linux Name    Device(s)
2020-05-06 22:57:28,476 process          L0686 INFO | Command 'lsslot' finished with 0 after 0.062342166900634766s
2020-05-06 22:57:28,477 process          L0436 DEBUG| [stdout] U9009.42A.13C6F1W-V6-C0    Virtual I/O Slot  30000000      vty
2020-05-06 22:57:28,477 process          L0436 DEBUG| [stdout] U9009.42A.13C6F1W-V6-C2    Virtual I/O Slot  30000002      l-lan
2020-05-06 22:57:28,478 process          L0436 DEBUG| [stdout] U9009.42A.13C6F1W-V6-C3    Virtual I/O Slot  30000003      l-lan
2020-05-06 22:57:28,478 process          L0436 DEBUG| [stdout] U9009.42A.13C6F1W-V6-C4    Virtual I/O Slot  30000004      l-lan
2020-05-06 22:57:28,478 process          L0436 DEBUG| [stdout] U9009.42A.13C6F1W-V6-C106  Virtual I/O Slot  3000006a      v-scsi
2020-05-06 22:57:28,481 process          L0604 INFO | Running 'cat /sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/mtu'
2020-05-06 22:57:28,484 process          L0436 DEBUG| [stderr] cat: '/sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/mtu': No such file or directory
2020-05-06 22:57:28,485 process          L0686 INFO | Command 'cat /sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/mtu' finished with 1 after 0.0019927024841308594s
2020-05-06 22:57:28,487 stacktrace       L0039 ERROR|
2020-05-06 22:57:28,487 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:865
2020-05-06 22:57:28,488 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-06 22:57:28,489 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/Network_config.py", line 110, in test_mtu_check
2020-05-06 22:57:28,489 stacktrace       L0045 ERROR|     mtu = self.get_network_sysfs_param("mtu")
2020-05-06 22:57:28,489 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/Network_config.py", line 104, in get_network_sysfs_param
2020-05-06 22:57:28,489 stacktrace       L0045 ERROR|     return process.system_output(cmd, shell=True).decode("utf-8").strip()
2020-05-06 22:57:28,489 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/process.py", line 1167, in system_output
2020-05-06 22:57:28,489 stacktrace       L0045 ERROR|     encoding=encoding)
2020-05-06 22:57:28,490 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/process.py", line 1037, in run
2020-05-06 22:57:28,490 stacktrace       L0045 ERROR|     raise CmdError(cmd, sp.result)
2020-05-06 22:57:28,490 stacktrace       L0045 ERROR| avocado.utils.process.CmdError: Command 'cat /sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/mtu' failed.

```

```
 (1/5) avocado-misc-tests/io/net/Network_config.py:NetworkconfigTest.test_driver_check;Parameters-97d7:  PASS (2.99 s)
 (2/5) avocado-misc-tests/io/net/Network_config.py:NetworkconfigTest.test_mtu_check;Parameters-97d7:  ERROR: Command 'cat /sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/mtu' failed.\nstdout: b''\nstderr: b"cat: '/sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/mtu': No such file or directory\n"\nadditional_info: None (1.85 s)
 (3/5) avocado-misc-tests/io/net/Network_config.py:NetworkconfigTest.test_speed_check;Parameters-97d7:  ERROR: Command 'cat /sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/speed' failed.\nstdout: b''\nstderr: b"cat: '/sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/speed': No such file or directory\n"\nadditional_info: None (1.85 s)
 (4/5) avocado-misc-tests/io/net/Network_config.py:NetworkconfigTest.test_mac_aadr_check;Parameters-97d7:  ERROR: Command 'cat /sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/address' failed.\nstdout: b''\nstderr: b"cat: '/sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/address': No such file or directory\n"\nadditional_info: None (1.85 s)
 (5/5) avocado-misc-tests/io/net/Network_config.py:NetworkconfigTest.test_duplex_check;Parameters-97d7:  ERROR: Command 'cat /sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/duplex' failed.\nstdout: b''\nstderr: b"cat: '/sys/module/ibmveth/drivers/vio:ibmveth/None/net/env3/duplex': No such file or directory\n"\nadditional_info: None (1.85 s
```

**Comment by narasimhan-v** [comment]
@smruti77 can you please check on this ?

**Comment by smruti77** [comment]
> @smruti77 can you please check on this ?

ok

**Comment by smruti77** [comment]
#1742
