### ISSUE TITLE
htx test fails on veth nic devices

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1705]
```
2020-05-06 23:25:30,781 process          L0686 INFO | Command 'ip -4 -j address show env3' finished with 0 after 0.0015778541564941406s
2020-05-06 23:25:30,785 process          L0604 INFO | Running 'ip link set env3 up'
2020-05-06 23:25:30,788 process          L0686 INFO | Command 'ip link set env3 up' finished with 0 after 0.001149892807006836s
2020-05-06 23:25:30,789 process          L0604 INFO | Running 'ip addr add 200.20.20.204/24 dev env4'
2020-05-06 23:25:30,793 process          L0686 INFO | Command 'ip addr add 200.20.20.204/24 dev env4' finished with 0 after 0.0011551380157470703s
2020-05-06 23:25:30,794 process          L0604 INFO | Running 'ip -4 -j address show env4'
2020-05-06 23:25:30,797 process          L0436 DEBUG| [stdout] [{},{},{},{"ifindex":4,"ifname":"env4","flags":["BROADCAST","MULTICAST","UP","LOWER_UP"],"mtu":1500,"qdisc":"fq_codel","operstate":"UNKNOWN","group":"default","txqlen":1000,"addr_info":[{"family":"inet","local":"200.20.20.204","prefixlen":24,"scope":"global","label":"env4","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
2020-05-06 23:25:30,797 process          L0686 INFO | Command 'ip -4 -j address show env4' finished with 0 after 0.0015308856964111328s
2020-05-06 23:25:30,802 process          L0604 INFO | Running 'ip link set env4 up'
2020-05-06 23:25:30,805 process          L0686 INFO | Command 'ip link set env4 up' finished with 0 after 0.0011525154113769531s
2020-05-06 23:25:30,985 stacktrace       L0039 ERROR|
2020-05-06 23:25:30,986 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:854
2020-05-06 23:25:31,001 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-06 23:25:31,001 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py", line 88, in setUp
2020-05-06 23:25:31,001 stacktrace       L0045 ERROR|     self.login(self.peer_ip, self.peer_user, self.peer_password)
2020-05-06 23:25:31,001 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py", line 190, in login
2020-05-06 23:25:31,001 stacktrace       L0045 ERROR|     pxh.login(ip, username, password)
2020-05-06 23:25:31,002 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/pexpect/pxssh.py", line 424, in login
2020-05-06 23:25:31,002 stacktrace       L0045 ERROR|     raise ExceptionPxssh('Could not establish connection to host')
2020-05-06 23:25:31,002 stacktrace       L0045 ERROR| pexpect.pxssh.ExceptionPxssh: Could not establish connection to host
2020-05-06 23:25:31,002 stacktrace       L0046 ERROR|
2020-05-06 23:25:31,003 test             L1034 ERROR| ERROR 1-avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_start;run-0e36 -> TestSetupFail: Could not establish connection to host
2020-05-06 23:25:31,004 test             L1023 INFO |
2020-05-06 23:25:31,042 sysinfo          L0409 INFO | Commands configured by file: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/etc/avocado/sysinfo/commands
2020-05-06 23:25:31,044 sysinfo          L0420 INFO | Files configured by file: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/etc/avocado/sysinfo/files
2020-05-06 23:25:31,045 sysinfo          L0440 INFO | Profilers configured by file: /us
```

**Comment by smruti77** [comment]
@abdhaleegit not getting this error.but htx is configuring ip in different format, hots - 146.1.193.204 peer -   146.1.194.193 because of this interface is not pinging that's why its failing.

**Comment by narasimhan-v** [comment]
Waiting for @abdhaleegit to confirm on the latest status.

**Comment by narasimhan-v** [comment]
@abdhaleegit @smruti77 Is this still an issue ?
If not, please close the issue

**Comment by abdhaleegit** [comment]
this is the error due to veth in UNKNOWN state
