### ISSUE TITLE
dlpar.py: lshwres still lists the drc after dlpar remove of lpfc adapter

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1706]
```
2020-05-07 03:57:13,132 process          L0436 DEBUG| [stdout] Desired Variable Capacity Weight             : 0
2020-05-07 03:57:44,401 dlpar            L0161 INFO | Running the command on hmc lssyscfg -r sys  -F name
2020-05-07 03:57:44,513 parameters       L0143 DEBUG| PARAMS (key=lpar_2, path=*, default=None) => None
2020-05-07 03:57:44,514 parameters       L0143 DEBUG| PARAMS (key=pci_device, path=*, default=None) => '0014:70:00.0'
2020-05-07 03:57:44,516 parameters       L0143 DEBUG| PARAMS (key=num_of_dlpar, path=*, default=1) => 10
2020-05-07 03:57:44,516 dlpar            L0161 INFO | Running the command on hmc uname -a
2020-05-07 03:57:44,619 dlpar            L0161 INFO | Running the command on hmc lshwres -r io -m ltc-zz1 --rsubtype slot --filter lpar_names=ltc-zz1b-lp5-CI-austinveth-redfish -F drc_index,lpar_id,drc_name,bus_id
2020-05-07 03:57:44,732 dlpar            L0108 INFO | lpar_id : 6, loc_code: U78D2.001.WZS01DT-P1-C12, drc_index: 21030014, phb: 20
2020-05-07 03:57:44,733 dlpar            L0161 INFO | Running the command on hmc chhwres -r io --rsubtype slot -m ltc-zz1                    -o r --id 6 -l 21030014
2020-05-07 03:57:45,834 dlpar            L0161 INFO | Running the command on hmc lshwres -r io -m ltc-zz1                --rsubtype slot --filter lpar_names= ltc-zz1b-lp5-CI-austinveth-redfish                | grep -i 21030014
2020-05-07 03:57:45,948 dlpar            L0269 DEBUG| ['unit_phys_loc=U78D2.001.WZS01DT,bus_id=20,phys_loc=C12,drc_index=21030014,lpar_name=ltc-zz1b-lp5-CI-austinveth-redfish,lpar_id=6,slot_io_pool_id=none,description=PCIe3 2-Port 32Gb FC Adapter,"feature_codes=5787,EL5U,EL5V,EN1A,EN1B",pci_vendor_id=10DF,pci_device_id=E300,pci_subs_vendor_id=1014,pci_subs_device_id=0615,pci_class=0C04,pci_revision_id=01,bus_grouping=0,iop=0,parent_slot_drc_index=none,drc_name=U78D2.001.WZS01DT-P1-C12,interposer_present=0,interposer_pcie=0,lpar_assignment_capable=1,dynamic_lpar_assignment_capable=1']
2020-05-07 03:57:45,948 stacktrace       L0039 ERROR|
2020-05-07 03:57:45,948 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:865
2020-05-07 03:57:45,950 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-07 03:57:45,950 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/dlpar.py", line 222, in test_dlpar
2020-05-07 03:57:45,950 stacktrace       L0045 ERROR|     self.dlpar_remove()
2020-05-07 03:57:45,951 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/dlpar.py", line 270, in dlpar_remove
2020-05-07 03:57:45,951 stacktrace       L0045 ERROR|     self.fail("lshwres still lists the drc after dlpar remove")
2020-05-07 03:57:45,951 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 1054, in fail
2020-05-07 03:57:45,951 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-05-07 03:57:45,951 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: lshwres still lists the drc after dlpar remove
2020-05-07 03:57:45,952 stacktrace       L0046 ERROR|
2020-05-07 03:57:45,952 test             L0870 DEBUG| Local variables:
2020-05-07 03:57:46,041 test             L0873 DEBUG|  -> _ <class 'int'>: 0
2020-05-07 03:57:46,041 test             L0873 DEBUG|  -> self <class 'dlpar.DlparPci'>: 1-avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_dlpar;lpar_2-url-10ec
2020-05-07 03:57:46,342 test             L0299 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2020-05-07 03:57:46,352 test             L0299 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2020-05-07 03:57:46,353 test             L0299 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2020-05-07 03:57:46,387 sysinfo          L0173 DEBUG| Not logging 'dmidecode' (command 'dmidecode' was not found)
2020-05-07 03:57:46,624 sysinfo          L0105 DEBUG| Not logging /proc/pci (file does not exist)
2020-05-07 03:57:46,637 sysinfo          L0105 DEBUG| Not logging /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor (file does not exist)
2020-05-07 03:57:46,656 sysinfo          L0173 DEBUG| Not logging 'brctl show' (command 'brctl' was not found)
2020-05-07 03:57:46,656 sysinfo          L0237 ERROR| Daemon process 'journalctl -f' (pid 23221) terminated abnormally (code 0)
2020-05-07 03:57:46,657 process          L0604 INFO | Running 'kill -19 23231'
2020-05-07 03:57:46,660 process          L0686 INFO | Command 'kill -19 23231' finished with 0 after 0.0009305477142333984s
2020-05-07 03:57:46,744 process          L0604 INFO | Running 'kill -9 23231'
2020-05-07 03:57:46,747 process          L0686 INFO | Command 'kill -9 23231' finished with 0 after 0.0010216236114501953s
2020-05-07 03:57:46,748 process          L0604 INFO | Running 'kill -18 23231'
2020-05-07 03:57:46,751 process          L0686 INFO | Command 'kill -18 23231' finished with 0 after 0.0009374618530273438s
2020-05-07 03:57:46,752 test             L1034 ERROR| FAIL 1-avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_dlpar;lpar_2-url-10ec -> TestFail: lshwres still lists the drc after dlpar remove

```

**Comment by abdhaleegit** [comment]
it fails for tg3 adapter too

**Comment by abdhaleegit** [comment]
@smruti77 this will be taken by @Naresh-ibm

**Comment by Naresh-ibm** [comment]
@abdhaleegit this looks to me either setup(HMC rmc connection issue) or the actual issue itself.
I have tried this manually on fleet2 with NVMe adapter and it failed.

hscroot@ltchmcv4:~> chhwres -r io -m ltcfleet2 -o r --id 4 -l 21010018
HSCL2929 The dynamic removal of I/O resources failed: The I/O slot dynamic partitioning operation failed.  Here are the I/O slot IDs that failed and the reasons for failure:
   
May 15 01:50:27 caDlparCommand:execv to drmgr
Validating PHB DLPAR capability...yes.
Isolation failed for 20000018 with -9001
Valid outstanding translations exist.

[root@ltcfleet2-lp4 ~]# lspci -nnD
0018:01:00.0 Non-Volatile memory controller [0108]: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983 [144d:a808]
[root@ltcfleet2-lp4 ~]#

The OS return code is 255.  U78D5.ND1.CSS130E-P2-C1 (21010018)       
hscroot@ltchmcv4:~> 
hscroot@ltchmcv4:~> 
hscroot@ltchmcv4:~> 
hscroot@ltchmcv4:~> lshwres -r io -m ltcfleet2 --rsubtype slot --filter lpar_names=ltcfleet2-lp4-Naresh
unit_phys_loc=U78D5.ND1.CSS130E,bus_id=24,phys_loc=C1,drc_index=21010018,lpar_name=ltcfleet2-lp4-Naresh,lpar_id=4,slot_io_pool_id=none,description=800GB NVMe Gen3 U.2 Slim SSD,"feature_codes=59B4,EC5J",pci_vendor_id=144D,pci_device_id=A808,pci_subs_vendor_id=1014,pci_subs_device_id=0637,pci_class=0108,pci_revision_id=00,bus_grouping=0,iop=0,parent_slot_drc_index=none,drc_name=U78D5.ND1.CSS130E-P2-C1,interposer_present=0,interposer_pcie=0,lpar_assignment_capable=1,dynamic_lpar_assignment_capable=1
hscroot@ltchmcv4:~> 

[root@ltcfleet2-lp4 ~]# lspci -nnD
[root@ltcfleet2-lp4 ~]#


=====>>> this removes the adapter from the lpar but still list in HMC.
and while running remove operation from HMC it errors out as pasted above.

getting following error  while trying to add back the adapter.

hscroot@ltchmcv4:~> chhwres -r io -m ltcfleet2 -o a --id 4 -l 21010018
HSCL2928 The dynamic addition of I/O resources failed: The I/O slot dynamic partitioning operation failed.  Here are the I/O slot IDs that failed and the reasons for failure:
  The slot U78D5.ND1.CSS130E-P2-C1 (21010018)  is currently assigned to partition ltcfleet2-lp4-Naresh.      
hscroot@ltchmcv4:~> 

can you please let me know the lpar where you have ran this test, I want to check if we are running on the same HMC ?

**Comment by narasimhan-v** [comment]
@Naresh-ibm Looks like an HMC issue, please raise
```
[root@ltcfleet2-lp4 ~]# drmgr  -r -c phb -s "PHB 24" -w 5 -d 5

########## May 15 07:57:13 2020 ##########
drmgr: -r -c phb -s PHB 24 -w 5 -d 5 
Validating PHB DLPAR capability...yes.
Getting node types 0x00000010

DR nodes list
==============
/proc/device-tree/pci@800000020000018: 
	drc index: 0x20000018        description: Unknown slot type
	drc name: PHB 24
	loc code: U78D5.ND1.CSS130E-P1-C19
/proc/device-tree/pci@800000020000018: 
	drc index: 0x22010018        description: U.2 PCI-E capable, Rev 4, 4x lanes with 4x lanes connected
	drc name: U78D5.ND1.CSS130E-P2-C1
	loc code: U78D5.ND1.CSS130E-P1-C19

Retrieving hotplug nodes
hp adapter status for U78D5.ND1.CSS130E-P2-C1 is 1
setting hp adapter status to UNCONFIG adapter for U78D5.ND1.CSS130E-P2-C1
hp adapter status for U78D5.ND1.CSS130E-P2-C1 is 2
Removing device-tree node /proc/device-tree/pci@800000020000018/pci1014,637@0
performing kernel op for PHB 24, file is /sys/bus/pci/slots/control/remove_slot
Removing device-tree node /proc/device-tree/pci@800000020000018
Removing device-tree node /proc/device-tree/interrupt-controller@800000025000018
Releasing drc index 0x20000018
get-sensor for 20000018: 0, 1
Setting isolation state to 'isolate'
Isolation failed for 20000018 with -9001
Valid outstanding translations exist.
########## May 15 07:57:45 2020 ##########
[root@ltcfleet2-lp4 ~]# echo $?
255
[root@ltcfleet2-lp4 ~]# 
[root@ltcfleet2-lp4 ~]# 
[root@ltcfleet2-lp4 ~]# 
[root@ltcfleet2-lp4 ~]# lsslot -c phb
[root@ltcfleet2-lp4 ~]# lspci
[root@ltcfleet2-lp4 ~]#
```

```
hscroot@ltchmcv4:~> lshwres -r io -m ltcfleet2 --rsubtype slot --filter lpar_names=ltcfleet2-lp4-Naresh
unit_phys_loc=U78D5.ND1.CSS130E,bus_id=24,phys_loc=C1,drc_index=21010018,lpar_name=ltcfleet2-lp4-Naresh,lpar_id=4,slot_io_pool_id=none,description=800GB NVMe Gen3 U.2 Slim SSD,"feature_codes=59B4,EC5J",pci_vendor_id=144D,pci_device_id=A808,pci_subs_vendor_id=1014,pci_subs_device_id=0637,pci_class=0108,pci_revision_id=00,bus_grouping=0,iop=0,parent_slot_drc_index=none,drc_name=U78D5.ND1.CSS130E-P2-C1,interposer_present=0,interposer_pcie=0,lpar_assignment_capable=1,dynamic_lpar_assignment_capable=1
hscroot@ltchmcv4:~> 
```

**Comment by narasimhan-v** [comment]
System is left in this above mentioned state

**Comment by abdhaleegit** [comment]
Closing this as this is a Code issue
