### ISSUE TITLE
lpm.py : vnic ping_check fails with error

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1707]
```
[root@ltc1 ~]# ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 9.40.x.x
Control socket connect(/root/.ssh/avocado-master-root@9.40.x.x.x:22): Connection refused

```
```
2020-05-07 13:41:32,711 process          L0686 INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 9.40.x.x ''' finished with 255 after 0.004294157028198242s
2020-05-07 13:41:32,711 process          L0436 DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-root@9.40.x.x:22): Connection refused
2020-05-07 13:41:32,713 stacktrace       L0039 ERROR|
2020-05-07 13:41:32,713 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:854
2020-05-07 13:41:32,714 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-07 13:41:32,714 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py", line 89, in setUp
2020-05-07 13:41:32,714 stacktrace       L0045 ERROR|     password=self.peer_password)
2020-05-07 13:41:32,714 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/network/hosts.py", line 105, in __init__
2020-05-07 13:41:32,714 stacktrace       L0045 ERROR|     self.remote_session = self._connect()
2020-05-07 13:41:32,714 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/network/hosts.py", line 117, in _connect
2020-05-07 13:41:32,714 stacktrace       L0045 ERROR|     raise NWException(msg)
2020-05-07 13:41:32,715 stacktrace       L0045 ERROR| avocado.utils.network.exceptions.NWException: Failed connecting 9.40.x.x.x:22

```

**Comment by abdhaleegit** [comment]
closing this as it is working fine now
