### ISSUE TITLE
iopingtest : test suite compilation fails

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1710]
```
         L0686 INFO | Command 'rpm -q make' finished with 0 after 0.011298418045043945s
2020-05-07 20:41:53,800 asset            L0322 INFO | Asset not in cache, fetching it.
2020-05-07 20:41:53,800 download         L0070 INFO | Fetching https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ioping/ioping-0.8.tar.gz -> /home/ioci/avocado-fvt-wrapper/data/cache/by_location/47e7f6a7fc0348c5aa6c4e24e9fc1b2fdcfc467b/ioping-0.8.tar.gz._i1qds55
2020-05-07 20:41:53,970 download         L0054 DEBUG| Retrieved URL "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ioping/ioping-0.8.tar.gz": content-length 10590, date: "Fri, 08 May 2020 03:41:52 GMT", last-modified: "Sat, 23 Jan 2016 05:48:19 GMT"
2020-05-07 20:41:54,003 process          L0604 INFO | Running 'make'
2020-05-07 20:41:54,010 process          L0436 DEBUG| [stdout] cc -std=gnu99 -g -Wall -Wextra -pedantic -DVERSION=\"0.8\" -c -o ioping.o ioping.c
2020-05-07 20:41:54,282 process          L0436 DEBUG| [stderr] ioping.c: In function ‘parse_device’:
2020-05-07 20:41:54,282 process          L0436 DEBUG| [stderr] ioping.c:518:7: warning: implicit declaration of function ‘makedev’ [-Wimplicit-function-declaration]
2020-05-07 20:41:54,283 process          L0436 DEBUG| [stderr]    if (makedev(major, minor) != dev)
2020-05-07 20:41:54,283 process          L0436 DEBUG| [stderr]        ^~~~~~~
2020-05-07 20:41:54,283 process          L0436 DEBUG| [stderr] ioping.c:518:29: warning: comparison of integer expressions of different signedness: ‘int’ and ‘dev_t’ {aka ‘long unsigned int’} [-Wsign-compare]
2020-05-07 20:41:54,284 process          L0436 DEBUG| [stderr]    if (makedev(major, minor) != dev)
2020-05-07 20:41:54,284 process          L0436 DEBUG| [stderr]                              ^~
2020-05-07 20:41:54,417 process          L0436 DEBUG| [stdout] cc -o ioping ioping.o -std=gnu99 -g -Wall -Wextra -pedantic  -lm
2020-05-07 20:41:54,531 process          L0436 DEBUG| [stderr] ioping.o: In function `parse_device':
2020-05-07 20:41:54,532 process          L0436 DEBUG| [stderr] /var/tmp/avocado_2yqlv6_r/ioping-0.8/ioping.c:518: undefined reference to `makedev'
2020-05-07 20:41:54,532 process          L0436 DEBUG| [stderr] collect2: error: ld returned 1 exit status
2020-05-07 20:41:54,532 process          L0436 DEBUG| [stderr] make: *** [Makefile:58: ioping] Error 1
2020-05-07 20:41:54,533 process          L0686 INFO | Command 'make' finished with 2 after 0.5265171527862549s
2020-05-07 20:41:54,536 stacktrace       L0039 ERROR|
2020-05-07 20:41:54,537 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:854
2020-05-07 20:41:54,549 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-07 20:41:54,550 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/ioping.py", line 62, in setUp
2020-05-07 20:41:54,550 stacktrace       L0045 ERROR|     build.make(self.sourcedir)
2020-05-07 20:41:54,550 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/build.py", line 118, in make
2020-05-07 20:41:54,550 stacktrace       L0045 ERROR|     result = run_make(path, make, extra_args, kwargs)
2020-05-07 20:41:54,550 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/build.py", line 84, in run_make
2020-05-07 20:41:54,551 stacktrace       L0045 ERROR|     make_process = process.run(cmd, **process_kwargs)
2020-05-07 20:41:54,551 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/process.py", line 1037, in run
2020-05-07 20:41:54,551 stacktrace       L0045 ERROR|     raise CmdError(cmd, sp.result)
2020-05-07 20:41:54,551 stacktrace       L0045 ERROR| avocado.utils.process.CmdError: Command 'make' failed.
2020-05-07 20:41:54,551 stacktrace       L0045 ERROR| stdout: b'cc -std=gnu99 -g -Wall -Wextra -pedantic -DVERSION=\\"0.8\\" -c -o ioping.o ioping.c\ncc -o ioping ioping.o -std=gnu99 -g -Wall -Wextra -pedantic  -lm\n'
2020-05-07 20:41:54,551 stacktrace       L0045 ERROR| stderr: b"ioping.c: In function \xe2\x80\x98parse_device\xe2\x80\x99:\nioping.c:518:7: warning: implicit declaration of function \xe2\x80\x98makedev\xe2\x80\x99 [-Wimplicit-function-declaration]\n   if (makedev(major, minor) != dev)\n       ^~~~~~~\nioping.c:518:29: warning: comparison of integer expressions of different signedness: \xe2\x80\x98int\xe2\x80\x99 and \xe2\x80\x98dev_t\xe2\x80\x99 {aka \xe2\x80\x98long unsigned int\xe2\x80\x99} [-Wsign-compare]\n   if (makedev(major, minor) != dev)\n                             ^~\nioping.o: In function `parse_device':\n/var/tmp/avocado_2yqlv6_r/ioping-0.8/ioping.c:518: undefined reference to `makedev'\ncollect2: error: ld returned 1 exit status\nmake: *** [Makefile:58: ioping] Error 1\n"
2020-05-07 20:41:54,552 stacktrace       L0045 ERROR| additional_info: None
2020-05-07 20:41:54,552 stacktrace       L0046 ERROR|
2020-05-07 20:41:54,553 test             L1034 ERROR| ERROR 1-avocado-misc-tests/io/disk/ioping.py:Ioping.test;cache_io-f700 -> TestSetupFail: Command 'make' failed.
stdout: b'cc -std=gnu99 -g -Wall -Wextra -pedantic -DVERSION=\\"0.8\\" -c -o ioping.o ioping.c\ncc -o ioping ioping.o -std=gnu99 -g -Wall -Wextra -pedantic  -lm\n'
stderr: b"ioping.c: In function \xe2\x80\x98parse_device\xe2\x80\x99:\nioping.c:518:7: warning: implicit declaration of function \xe2\x80\x98makedev\xe2\x80\x99 [-Wimplicit-function-declaration]\n   if (makedev(major, minor) != dev)\n       ^~~~~~~\nioping.c:518:29: warning: comparison of integer expressions of different signedness: \xe2\x80\x98int\xe2\x80\x99 and \xe2\x80\x98dev_t\xe2\x80\x99 {aka \xe2\x80\x98long unsigned int\xe2\x80\x99} [-Wsign-compare]\n   if (makedev(major, minor) != dev)\n                             ^~\nioping.o: In function `parse_device':\n/var/tmp/avocado_2yqlv6_r/ioping-0.8/ioping.c:518: undefined reference to `makedev'\ncollect2: error: ld returned 1 exit status\nmake: *** [Makefile:58: ioping] Error 1\n"

```

**Comment by abdhaleegit** [comment]
@PraveenPenguin please have a look

**Comment by PraveenPenguin** [comment]
@abdhaleegit above commit will fix the issue, if it works please close this issue

**Comment by abdhaleegit** [comment]
Problem is fixed
