### ISSUE TITLE
smartctl : few tests are failing 

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1711]
```
2020-05-07 20:43:51,203 process          L0686 INFO | Command '/usr/bin/dnf -y install smartmontools' finished with 0 after 3.166163206100464s
2020-05-07 20:43:51,205 parameters       L0143 DEBUG| PARAMS (key=option, path=*, default=None) => '--test=long'
2020-05-07 20:43:51,205 parameters       L0143 DEBUG| PARAMS (key=disk, path=*, default=None) => '/dev/sdf'
2020-05-07 20:43:51,205 process          L0604 INFO | Running 'df -h /boot | grep /dev/sdf'
2020-05-07 20:43:51,210 process          L0686 INFO | Command 'df -h /boot | grep /dev/sdf' finished with 1 after 0.0027213096618652344s
2020-05-07 20:43:51,210 smartctl         L0063 INFO | option --test=long on /dev/sdf Disks
2020-05-07 20:43:51,211 process          L0604 INFO | Running 'smartctl --test=long /dev/sdf && sleep 120 && smartctl -X /dev/sdf && smartctl -A /dev/sdf'
2020-05-07 20:43:51,238 process          L0436 DEBUG| [stdout] smartctl 6.6 2017-11-05 r4594 [ppc64le-linux-5.7.0-rc4+] (local build)
2020-05-07 20:43:51,238 process          L0436 DEBUG| [stdout] Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org
2020-05-07 20:43:51,239 process          L0436 DEBUG| [stdout]
2020-05-07 20:43:51,266 process          L0436 DEBUG| [stdout] Long (extended) offline self test failed [unsupported field in scsi command]
2020-05-07 20:43:51,267 process          L0686 INFO | Command 'smartctl --test=long /dev/sdf && sleep 120 && smartctl -X /dev/sdf && smartctl -A /dev/sdf' finished with 4 after 0.05412435531616211s
2020-05-07 20:43:51,269 stacktrace       L0039 ERROR|
2020-05-07 20:43:51,269 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:865
2020-05-07 20:43:51,271 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-07 20:43:51,271 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/smartctl.py", line 70, in test
2020-05-07 20:43:51,271 stacktrace       L0045 ERROR|     self.fail("Smartctl option %s FAILS" % self.option)
2020-05-07 20:43:51,271 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 1054, in fail
2020-05-07 20:43:51,271 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-05-07 20:43:51,272 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: Smartctl option --test=long FAILS
2020-05-07 20:43:51,272 stacktrace       L0046 ERROR|
2020-05-07 20:43:51,272 test             L0870 DEBUG| Local variables:
2020-05-07 20:43:51,356 test             L0873 DEBUG|  -> cmd <class 'str'>: smartctl --test=long /dev/sdf && sleep 120 && smartctl -X /dev/sdf && smartctl -A /dev/sdf
2020-05-07 20:43:51,357 test             L0873 DEBUG|  -> self <class 'smartctl.SmartctlTest'>: 01-avocado-misc-tests/io/disk/smartctl.py:SmartctlTest.test;self_test-test1-ec24

```

**Comment by abdhaleegit** [comment]
FAIL: Smartctl option --test=long FAILS (5.01 s)
FAIL: Smartctl option -s on FAILS
FAIL: Smartctl option -S off FAILS
FAIL: Smartctl option --smart=off -T verypermissive FAILS
FAIL: Smartctl option --smart=on -T permissive FAILS
FAIL: Smartctl option --smart=on -T normal FAILS
FAIL: Smartctl option --smart=on -T conservative FAILS
FAIL: Smartctl option --attributes --log=selftest --quietmode=errorsonly FAILS
FAIL: Smartctl option --smart=on --offlineauto=on --saveauto=on FAILS
FAIL: Smartctl option --all FAILS 
FAIL: Smartctl option -x FAILS

**Comment by abdhaleegit** [comment]
@manvanthar Could you please have a look

**Comment by manvanthar** [comment]
@abdhaleegit can you please attach complete logs please.     Depending on the drive we are using some of the behavior can be expected.  But i can check that.

**Comment by abdhaleegit** [comment]
duplicate of https://github.com/avocado-framework-tests/avocado-misc-tests/issues/1810
