### ISSUE TITLE
ethtool:  tests FAIL for austin tg3 device

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1713]
ethtool;SelfTest-175f:  FAIL: failed 
test_ethtool;Get-dump-4634:  FAIL: failed 
test_ethtool;Get-phy-tunable-0250:  FAIL: failed
test_ethtool;Autonegotiation-a091:  FAIL: failed
ethtool;Get-phy-tunable-0250:  FAIL

```
2020-05-07 21:02:05,441 process          L0436 DEBUG| [stdout] 64 bytes from 102.10.10.193: icmp_seq=3 ttl=64 time=0.107 ms
2020-05-07 21:02:06,481 process          L0436 DEBUG| [stdout] 64 bytes from 102.10.10.193: icmp_seq=4 ttl=64 time=0.103 ms
2020-05-07 21:02:07,521 process          L0436 DEBUG| [stdout] 64 bytes from 102.10.10.193: icmp_seq=5 ttl=64 time=0.100 ms
2020-05-07 21:02:07,522 process          L0436 DEBUG| [stdout]
2020-05-07 21:02:07,522 process          L0436 DEBUG| [stdout] --- 102.10.10.193 ping statistics ---
2020-05-07 21:02:07,522 process          L0436 DEBUG| [stdout] 5 packets transmitted, 5 received, 0% packet loss, time 182ms
2020-05-07 21:02:07,523 process          L0436 DEBUG| [stdout] rtt min/avg/max/mdev = 0.099/0.125/0.218/0.047 ms
2020-05-07 21:02:07,523 process          L0686 INFO | Command 'ping -I enP19p96s0f0 102.10.10.193 -c 5' finished with 0 after 4.18169641494751s
2020-05-07 21:02:07,526 parameters       L0143 DEBUG| PARAMS (key=arg, path=*, default=) => '-r'
2020-05-07 21:02:07,527 parameters       L0143 DEBUG| PARAMS (key=action_elapse, path=*, default=) => ''
2020-05-07 21:02:07,527 parameters       L0143 DEBUG| PARAMS (key=privflag_test, path=*, default=False) => False
2020-05-07 21:02:07,528 process          L0604 INFO | Running 'ip link set dev enP19p96s0f0 down'
2020-05-07 21:02:07,614 process          L0686 INFO | Command 'ip link set dev enP19p96s0f0 down' finished with 0 after 0.08444714546203613s
2020-05-07 21:02:07,614 process          L0604 INFO | Running 'ethtool enP19p96s0f0'
2020-05-07 21:02:07,618 process          L0436 DEBUG| [stdout] Settings for enP19p96s0f0:
2020-05-07 21:02:07,618 process          L0686 INFO | Command 'ethtool enP19p96s0f0' finished with 0 after 0.002028942108154297s
2020-05-07 21:02:07,619 process          L0436 DEBUG| [stdout]  Supported ports: [ TP ]
2020-05-07 21:02:07,619 process          L0436 DEBUG| [stdout]  Supported link modes:   10baseT/Half 10baseT/Full
2020-05-07 21:02:07,619 process          L0436 DEBUG| [stdout]                          100baseT/Half 100baseT/Full
2020-05-07 21:02:07,620 process          L0436 DEBUG| [stdout]                          1000baseT/Half 1000baseT/Full
2020-05-07 21:02:07,620 process          L0436 DEBUG| [stdout]  Supported pause frame use: No
2020-05-07 21:02:07,620 process          L0436 DEBUG| [stdout]  Supports auto-negotiation: Yes
2020-05-07 21:02:07,621 process          L0436 DEBUG| [stdout]  Supported FEC modes: Not reported
2020-05-07 21:02:07,621 process          L0436 DEBUG| [stdout]  Advertised link modes:  10baseT/Half 10baseT/Full
2020-05-07 21:02:07,621 process          L0436 DEBUG| [stdout]                          100baseT/Half 100baseT/Full
2020-05-07 21:02:07,622 process          L0436 DEBUG| [stdout]                          1000baseT/Half 1000baseT/Full
2020-05-07 21:02:07,622 process          L0436 DEBUG| [stdout]  Advertised pause frame use: Symmetric
2020-05-07 21:02:07,622 process          L0436 DEBUG| [stdout]  Advertised auto-negotiation: Yes
2020-05-07 21:02:07,623 process          L0436 DEBUG| [stdout]  Advertised FEC modes: Not reported
2020-05-07 21:02:07,623 process          L0436 DEBUG| [stdout]  Speed: Unknown!
2020-05-07 21:02:07,623 process          L0436 DEBUG| [stdout]  Duplex: Unknown! (255)
2020-05-07 21:02:07,623 process          L0436 DEBUG| [stdout]  Port: Twisted Pair
2020-05-07 21:02:07,624 process          L0436 DEBUG| [stdout]  PHYAD: 1
2020-05-07 21:02:07,624 process          L0436 DEBUG| [stdout]  Transceiver: internal
2020-05-07 21:02:07,624 process          L0436 DEBUG| [stdout]  Auto-negotiation: on
2020-05-07 21:02:07,625 process          L0436 DEBUG| [stdout]  MDI-X: Unknown
2020-05-07 21:02:07,625 process          L0436 DEBUG| [stdout]  Supports Wake-on: g
2020-05-07 21:02:07,625 process          L0436 DEBUG| [stdout]  Wake-on: g
2020-05-07 21:02:07,626 process          L0436 DEBUG| [stdout]  Current message level: 0x000000ff (255)
2020-05-07 21:02:07,626 process          L0436 DEBUG| [stdout]                         drv probe link timer ifdown ifup rx_err tx_err
2020-05-07 21:02:07,626 process          L0436 DEBUG| [stdout]  Link detected: no
2020-05-07 21:02:07,628 process          L0604 INFO | Running 'ethtool -r enP19p96s0f0 '
2020-05-07 21:02:07,631 process          L0436 DEBUG| [stderr] Cannot restart autonegotiation: Resource temporarily unavailable
2020-05-07 21:02:07,632 process          L0686 INFO | Command 'ethtool -r enP19p96s0f0 ' finished with 255 after 0.0019316673278808594s
2020-05-07 21:02:07,634 stacktrace       L0039 ERROR|
2020-05-07 21:02:07,634 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:865
2020-05-07 21:02:07,635 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-07 21:02:07,635 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/ethtool_test.py", line 140, in test_ethtool
2020-05-07 21:02:07,636 stacktrace       L0045 ERROR|     self.fail("failed")
2020-05-07 21:02:07,636 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 1054, in fail
2020-05-07 21:02:07,636 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-05-07 21:02:07,636 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: failed
2020-05-07 21:02:07,636 stacktrace       L0046 ERROR|
2020-05-07 21:02:07,637 test             L0870 DEBUG| Local variables:
2020-05-07 21:02:07,723 test             L0873 DEBUG|  -> ret <class 'avocado.utils.process.CmdResult'>: command: 'ethtool -r enP19p96s0f0 '
exit_status: 255
duration: 0.0019316673278808594
interrupted: False
pid: 13343
encoding: 'UTF-8'
stdout: b''
stderr: b'Cannot restart autonegotiation: Resource temporarily unavailable\n'

```

**Comment by smruti77** [comment]
this is not script issue, options are not supported so this is failing.

**Comment by abdhaleegit** [comment]
@smruti77 I will debug this agian.. and update

**Comment by abdhaleegit** [comment]
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1740
