### ISSUE TITLE
bridge : bridge test fails on tg3 interface

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1714]
```
2020-05-07 21:11:05,604 parameters       L0143 DEBUG| PARAMS (key=interface, path=*, default=None) => 'enP19p96s0f0'
2020-05-07 21:11:05,604 parameters       L0143 DEBUG| PARAMS (key=peer_ip, path=*, default=None) => '102.10.10.193'
2020-05-07 21:11:05,605 parameters       L0143 DEBUG| PARAMS (key=host_ip, path=*, default=) => '102.10.10.188'
2020-05-07 21:11:05,605 parameters       L0143 DEBUG| PARAMS (key=netmask, path=*, default=) => '255.255.255.0'
2020-05-07 21:11:05,605 parameters       L0143 DEBUG| PARAMS (key=bridge_interface, path=*, default=br0) => 'br0'
2020-05-07 21:11:05,606 process          L0604 INFO | Running 'ip link add dev br0 type bridge'
2020-05-07 21:11:05,610 process          L0436 DEBUG| [stderr] RTNETLINK answers: File exists
2020-05-07 21:11:05,610 process          L0686 INFO | Command 'ip link add dev br0 type bridge' finished with 2 after 0.002592325210571289s
2020-05-07 21:11:05,614 stacktrace       L0039 ERROR|
2020-05-07 21:11:05,614 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:865
2020-05-07 21:11:05,615 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-07 21:11:05,615 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/bridge.py", line 62, in test_bridge_create
2020-05-07 21:11:05,616 stacktrace       L0045 ERROR|     % self.bridge_interface)
2020-05-07 21:11:05,616 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/bridge.py", line 34, in check_failure
2020-05-07 21:11:05,616 stacktrace       L0045 ERROR|     self.fail("Command %s failed" % cmd)
2020-05-07 21:11:05,616 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 1054, in fail
2020-05-07 21:11:05,616 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-05-07 21:11:05,616 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: Command ip link add dev br0 type bridge failed
2020-05-07 21:11:05,617 stacktrace       L0046 ERROR|
2020-05-07 21:11:05,617 test             L0870 DEBUG| Local variables:

```

**Comment by smruti77** [comment]
@abdhaleegit  this one is working fine. saw this error in old script,new one is working fine.

**Comment by smruti77** [comment]
JOB ID     : 441bd2357510f6b541469531c184ff95f738d0fe
JOB LOG    : /home/ioci/avocado-fvt-wrapper/results/job-2020-05-12T02.37-441bd23/job.log
 (1/3) bridge.py:Bridging.test_bridge_create;run-45ed: PASS (0.62 s)
 (2/3) bridge.py:Bridging.test_bridge_run;run-45ed: PASS (4.81 s)
 (3/3) bridge.py:Bridging.test_bridge_delete;run-45ed: PASS (0.92 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 6.58 s
JOB HTML   : /home/ioci/avocado-fvt-wrapper/results/job-2020-05-12T02.37-441bd23/results.html

**Comment by abdhaleegit** [comment]
@smruti77 which PR fixes this ... please paste here

**Comment by smruti77** [comment]
@abdhaleegit for latest module change for nic, that one is working fine for me.

**Comment by narasimhan-v** [comment]
@smruti77 please paste the avocado PR link here

**Comment by smruti77** [comment]
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1588
