### ISSUE TITLE
distro_tools: rework on tools test

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1715]
(02/26) avocado-misc-tests/io/pci/distro_tools.py:DisrtoTool.test;lsslot_pci_-a-85d0:  FAIL: Failed to display hot plug slots (1.95 s)
 (25/26) avocado-misc-tests/io/pci/distro_tools.py:DisrtoTool.test;ofpathname_l-ec8d:  FAIL: ofpathname failed (1.97 s)
 (26/26) avocado-misc-tests/io/pci/distro_tools.py:DisrtoTool.test;ofpathname_a-0ab3:  FAIL: ofpathname failed (2.12 s)

**Comment by abdhaleegit** [comment]
```
2020-05-07 21:26:13,481 process          L0686 INFO | Command 'rpm -q pciutils' finished with 0 after 0.011739253997802734s
2020-05-07 21:26:13,484 process          L0604 INFO | Running 'lsslot -c pci -a'
2020-05-07 21:26:13,520 process          L0686 INFO | Command 'lsslot -c pci -a' finished with 1 after 0.03348493576049805s
2020-05-07 21:26:13,520 stacktrace       L0039 ERROR|
2020-05-07 21:26:13,520 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:865
2020-05-07 21:26:13,522 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-07 21:26:13,522 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/distro_tools.py", line 148, in test
2020-05-07 21:26:13,522 stacktrace       L0045 ERROR|     getattr(self, self.tool)()
2020-05-07 21:26:13,522 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/distro_tools.py", line 61, in lsslot
2020-05-07 21:26:13,523 stacktrace       L0045 ERROR|     self.fail("Failed to display hot plug slots")
2020-05-07 21:26:13,523 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 1054, in fail
2020-05-07 21:26:13,523 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-05-07 21:26:13,523 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: Failed to display hot plug slots
2020-05-07 21:26:13,523 stacktrace       L0046 ERROR|
2020-05-07 21:26:13,524 test             L0870 DEBUG| Local variables:
2020-05-07 21:26:13,608 test             L0873 DEBUG|  -> self <class 'distro_tools.DisrtoTool'>: 02-avocado-misc-tests/io/pci/distro_tools.py:DisrtoTool.test;lsslot_pci_-a-85d0
2020-05-07 21:26:13,609 test             L0299 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)

```

**Comment by abdhaleegit** [comment]
```
2020-05-07 21:28:12,795 process          L0436 DEBUG| [stdout] pciutils-3.5.6-4.el8.ppc64le
2020-05-07 21:28:12,796 process          L0686 INFO | Command 'rpm -q pciutils' finished with 0 after 0.011427164077758789s
2020-05-07 21:28:12,799 process          L0604 INFO | Running 'ofpathname -a enP19p96s0f0'
2020-05-07 21:28:13,015 process          L0436 DEBUG| [stdout] No aliases found.
2020-05-07 21:28:13,015 process          L0686 INFO | Command 'ofpathname -a enP19p96s0f0' finished with 1 after 0.21439623832702637s
2020-05-07 21:28:13,017 stacktrace       L0039 ERROR|
2020-05-07 21:28:13,018 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:865
2020-05-07 21:28:13,019 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-07 21:28:13,019 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/distro_tools.py", line 148, in test
2020-05-07 21:28:13,019 stacktrace       L0045 ERROR|     getattr(self, self.tool)()
2020-05-07 21:28:13,020 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/distro_tools.py", line 142, in ofpathname
2020-05-07 21:28:13,020 stacktrace       L0045 ERROR|     self.fail("ofpathname failed")
2020-05-07 21:28:13,020 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 1054, in fail
2020-05-07 21:28:13,020 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-05-07 21:28:13,020 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: ofpathname failed

```

**Comment by abdhaleegit** [comment]
@smruti77 

tools which require pci bus id will go in to
/io/pci/pci_tools.py
tools which do not require pci_bus id will go to
/io/common/distro_tools.py

**Comment by abdhaleegit** [comment]
lsprop, lparstat , lssrc , lsdevinfo. etc   these wiil 
virtual device tools :
lsslot
ls-veth
lsvio
ls-vscsi
ls-vdev


all virtual will go in /io/common/virtual_tools.py
all common to /io/common/distro_tools.py
all pci tools to /io/pci/pci_tools.py

**Comment by smruti77** [comment]
lsprop, lparstat , lssrc , lsdevinfo this will be commion ..?

**Comment by narasimhan-v** [comment]
@smruti77 please work on getting the PR merged

**Comment by smruti77** [comment]
@narasimhan-v its done already.
