### ISSUE TITLE
all network related test are failing at avocado.utils.network.exceptions.NWException: Failed connecting 101.10.10.193:22

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1717]
```
Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 101.10.10.193 ''
12:45
2020-05-10 19:02:22,146 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:854
2020-05-10 19:02:22,147 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-10 19:02:22,147 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/network_test.py", line 84, in setUp
2020-05-10 19:02:22,147 stacktrace       L0045 ERROR|     password=self.peer_password)
2020-05-10 19:02:22,148 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/network/hosts.py", line 105, in __init__
2020-05-10 19:02:22,148 stacktrace       L0045 ERROR|     self.remote_session = self._connect()
2020-05-10 19:02:22,148 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/network/hosts.py", line 117, in _connect
2020-05-10 19:02:22,148 stacktrace       L0045 ERROR|     raise NWException(msg)
2020-05-10 19:02:22,148 stacktrace       L0045 ERROR| avocado.utils.network.exceptions.NWException: Failed connecting 101.10.10.193:22
```

**Comment by narasimhan-v** [comment]
@smruti77 can you please check and updated if this failure is still seen ?

**Comment by smruti77** [comment]
@narasimhan-v you can close this issue here, issue was open in utills for this.not releated to test script this one.

**Comment by narasimhan-v** [comment]
@smruti77 please paste that issue link, so that it serves as a reference.

**Comment by smruti77** [comment]
#3810
