### ISSUE TITLE
[virtual] pci_hotplug.py : Errno 2 No such file or directory: '/sys/bus/pci/devices//devspec'

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1726]
pci_hotplug test fails for virtual devices
```
2020-04-23 17:31:18,481 software_manager L0498 ERROR| dnf module for Python is required. Using the basic support from rpm and dnf commands
2020-04-23 17:31:18,481 process          L0604 INFO | Running 'rpm -q pciutils'
2020-04-23 17:31:18,490 process          L0436 DEBUG| [stdout] pciutils-3.5.6-4.el8.ppc64le
2020-04-23 17:31:18,491 process          L0686 INFO | Command 'rpm -q pciutils' finished with 0 after 0.007971525192260742s
2020-04-23 17:31:18,493 stacktrace       L0039 ERROR|
2020-04-23 17:31:18,493 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:854
2020-04-23 17:31:18,493 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-04-23 17:31:18,494 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/pci_hotplug.py", line 71, in setUp
2020-04-23 17:31:18,494 stacktrace       L0045 ERROR|     slot = self.get_slot(pci_addr)
2020-04-23 17:31:18,494 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/pci_hotplug.py", line 82, in get_slot
2020-04-23 17:31:18,494 stacktrace       L0045 ERROR|     % pci_addr)
2020-04-23 17:31:18,494 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/genio.py", line 62, in read_file
2020-04-23 17:31:18,494 stacktrace       L0045 ERROR|     with open(filename, 'r') as file_obj:
2020-04-23 17:31:18,494 stacktrace       L0045 ERROR| FileNotFoundError: [Errno 2] No such file or directory: '/sys/bus/pci/devices//devspec'
2020-04-23 17:31:18,494 stacktrace       L0046 ERROR|
2020-04-23 17:31:18,495 test             L1034 ERROR| ERROR 1-avocado-misc-tests/io/pci/pci_hotplug.py:PCIHotPlugTest.test;run-eca1 -> TestSetupFail: [Errno 2] No such file or directory: '/sys/bus/pci/devices//devspec'
2020-04-23 17:31:18,495 test             L1023 INFO |
2020-04-23 17:31:18,507 job              L0620 INFO | Test results available in /home/ioci/logs/io_network/results/job-2020-04-23T17.31-1567128
```

**Comment by narasimhan-v** [comment]
@abdhaleegit pci_hotplug test yaml parameter changed to `pci_devices`. Please try and update

**Comment by PraveenPenguin** [comment]
@abdhaleegit is this still a issue
