### ISSUE TITLE
[nvme] software raid test Failed to create a MD device

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1728]
```
2020-04-23 17:42:13,919 process          L0436 DEBUG| [stderr] mdadm - v4.1 - 2018-10-01
2020-04-23 17:42:13,919 process          L0686 INFO | Command 'mdadm -V' finished with 0 after 0.001375436782836914s
2020-04-23 17:42:13,921 parameters       L0143 DEBUG| PARAMS (key=disks, path=*, default=) => '/dev/nvme0n1 /dev/nvme0n2 /dev/nvme0n3 /dev/nvme0n4'
2020-04-23 17:42:13,921 parameters       L0143 DEBUG| PARAMS (key=raidname, path=*, default=/dev/md/mdsraid) => '/dev/md/mdsraid'
2020-04-23 17:42:13,922 parameters       L0143 DEBUG| PARAMS (key=raid, path=*, default=0) => 'linear'
2020-04-23 17:42:13,922 parameters       L0143 DEBUG| PARAMS (key=metadata, path=*, default=1.2) => 0.9
2020-04-23 17:42:13,922 parameters       L0143 DEBUG| PARAMS (key=setup, path=*, default=True) => True
2020-04-23 17:42:13,922 parameters       L0143 DEBUG| PARAMS (key=run_test, path=*, default=False) => True
2020-04-23 17:42:13,922 parameters       L0143 DEBUG| PARAMS (key=cleanup, path=*, default=True) => True
2020-04-23 17:42:13,923 parameters       L0143 DEBUG| PARAMS (key=force, path=*, default=False) => True
2020-04-23 17:42:13,924 process          L0604 INFO | Running 'echo 'yes' | mdadm --create --verbose --assume-clean             /dev/md/mdsraid --level=linear --raid-devices=4 /dev/nvme0n1 /dev/nvme0n2 /dev/nvme0n3 /dev/nvme0n4 --metadata 0.9 --force'
2020-04-23 17:42:13,929 process          L0436 DEBUG| [stderr] mdadm: super0.90 cannot open /dev/nvme0n2: Device or resource busy
2020-04-23 17:42:13,929 process          L0436 DEBUG| [stderr] mdadm: /dev/nvme0n2 is not suitable for this array.
2020-04-23 17:42:13,929 process          L0436 DEBUG| [stderr] mdadm: partition table exists on /dev/nvme0n3
2020-04-23 17:42:13,930 process          L0436 DEBUG| [stderr] mdadm: partition table exists on /dev/nvme0n3 but will be lost or
2020-04-23 17:42:13,930 process          L0686 INFO | Command 'echo 'yes' | mdadm --create --verbose --assume-clean             /dev/md/mdsraid --level=linear --raid-devices=4 /dev/nvme0n1 /dev/nvme0n2 /dev/nvme0n3 /dev/nvme0n4 --metadata 0.9 --force' finished with 1 after 0.004708528518676758s
2020-04-23 17:42:13,930 process          L0436 DEBUG| [stderr]        meaningless after creating array
2020-04-23 17:42:13,930 process          L0436 DEBUG| [stderr] mdadm: super0.90 cannot open /dev/nvme0n4: Device or resource busy
2020-04-23 17:42:13,931 process          L0436 DEBUG| [stderr] mdadm: /dev/nvme0n4 is not suitable for this array.
2020-04-23 17:42:13,931 process          L0436 DEBUG| [stderr] mdadm: create aborted
2020-04-23 17:42:13,932 stacktrace       L0039 ERROR|
2020-04-23 17:42:13,932 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:865
2020-04-23 17:42:13,933 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-04-23 17:42:13,933 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/softwareraid.py", line 77, in test_run
2020-04-23 17:42:13,934 stacktrace       L0045 ERROR|     self.create_raid()
2020-04-23 17:42:13,934 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/softwareraid.py", line 94, in create_raid
2020-04-23 17:42:13,934 stacktrace       L0045 ERROR|     self.check_pass(cmd, "Failed to create a MD device")
2020-04-23 17:42:13,934 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/softwareraid.py", line 146, in check_pass
2020-04-23 17:42:13,934 stacktrace       L0045 ERROR|     self.fail(errmsg)
2020-04-23 17:42:13,934 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 1054, in fail
2020-04-23 17:42:13,934 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-04-23 17:42:13,934 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: Failed to create a MD device
2020-04-23 17:42:13,935 stacktrace       L0046 ERROR|
2020-04-23 17:42:13,935 test             L0870 DEBUG| Local variables:
2020-04-23 17:42:13,992 test             L0873 DEBUG|  -> self <class 'softwareraid.SoftwareRaid'>: 01-avocado-misc-tests/io/disk/softwareraid.py:SoftwareRaid.test_run;superblock-0.90-raidlinear-9697
2020-04-23 17:42:13,993 process          L0604 INFO | Running 'mdadm --manage /dev/md/mdsraid --stop'

```

**Comment by narasimhan-v** [comment]
Investigating. Recently, metadata 0.90 is causing some issues.

**Comment by smruti77** [comment]
software raid test is working fine.
```
JOB ID     : 44d9109e8dcbc9c0a8db212d41236ba0ec50ef92
JOB LOG    : /root/avocado/job-results/job-2020-06-11T00.17-44d9109/job.log
 (01/24) softwareraid.py:SoftwareRaid.test_run;superblock-0.90-raidlinear-bb3f: PASS (1.48 s)
 (02/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raidlinear-fde2: PASS (1.39 s)
 (03/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.1-raidlinear-47cf: PASS (1.26 s)
 (04/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.2-raidlinear-bcf8: PASS (1.37 s)
 (05/24) softwareraid.py:SoftwareRaid.test_run;superblock-0.90-raid0-5787: PASS (1.74 s)
 (06/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raid0-c69e: PASS (1.65 s)
 (07/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.1-raid0-8f2c: PASS (1.53 s)
 (08/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.2-raid0-bbc6: PASS (1.46 s)
 (09/24) softwareraid.py:SoftwareRaid.test_run;superblock-0.90-raid1-ab99: PASS (152.21 s)
 (10/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raid1-061f: PASS (152.39 s)
 (11/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.1-raid1-4326: PASS (152.48 s)
 (12/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.2-raid1-8036: PASS (152.21 s)
 (13/24) softwareraid.py:SoftwareRaid.test_run;superblock-0.90-raid5-21ce: PASS (153.05 s)
 (14/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raid5-fb33: PASS (152.98 s)
 (15/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.1-raid5-180c: PASS (152.88 s)
 (16/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.2-raid5-2523: PASS (152.85 s)
 (17/24) softwareraid.py:SoftwareRaid.test_run;superblock-0.90-raid10-5bf7: PASS (152.56 s)
 (18/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raid10-c8c0: PASS (152.33 s)
 (19/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.1-raid10-109e: PASS (152.49 s)
 (20/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.2-raid10-c75c: PASS (153.06 s)
 (21/24) softwareraid.py:SoftwareRaid.test_run;superblock-0.90-raid6-33e2: PASS (152.94 s)
 (22/24) softwareraid.py:SoftwareRaid.test_run;superblock-1.0-raid6-13d4: PASS (152.86 s)
```
