### ISSUE TITLE
[nvme] lvsetup.py : fdisk: cannot open /dev/nvme1n2: Input/output error

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1729]
```
2020-04-23 17:42:43,338 parameters       L0143 DEBUG| PARAMS (key=lv_disks, path=*, default=None) => '/dev/nvme1n1 /dev/nvme1n2 /dev/nvme1n3 /dev/nvme1n4'
2020-04-23 17:42:43,338 parameters       L0143 DEBUG| PARAMS (key=vg_name, path=*, default=avocado_vg) => 'avocado_vg'
2020-04-23 17:42:43,338 parameters       L0143 DEBUG| PARAMS (key=lv_name, path=*, default=avocado_lv) => 'avocado_lv'
2020-04-23 17:42:43,339 parameters       L0143 DEBUG| PARAMS (key=fs, path=*, default=ext4) => 'ext2'
2020-04-23 17:42:43,340 parameters       L0143 DEBUG| PARAMS (key=lv_snapshot_name, path=*, default=avocado_sn) => 'avocado_sn'
2020-04-23 17:42:43,341 parameters       L0143 DEBUG| PARAMS (key=ramdisk_basedir, path=*, default=/var/tmp/avocado_dlgf_8fc/avocado_job_1krgxouz/01-avocado-misc-tests_io_disk_lvsetup.py_Lvsetup.test_ext2-5a6a/ramdisk) => '/var/tmp/avocado_dlgf_8fc/avocado_job_1krgxouz/01-avocado-misc-tests_io_disk_lvsetup.py_Lvsetup.test_ext2-5a6a/ramdisk'
2020-04-23 17:42:43,341 parameters       L0143 DEBUG| PARAMS (key=ramdisk_sparse_filename, path=*, default=virtual_hdd) => 'virtual_hdd'
2020-04-23 17:42:43,341 process          L0604 INFO | Running 'vgdisplay avocado_vg'
2020-04-23 17:42:43,357 process          L0436 DEBUG| [stderr]   Volume group "avocado_vg" not found
2020-04-23 17:42:43,358 process          L0436 DEBUG| [stderr]   Cannot process volume group avocado_vg
2020-04-23 17:42:43,488 process          L0686 INFO | Command 'vgdisplay avocado_vg' finished with 5 after 0.1454305648803711s
2020-04-23 17:42:43,490 lv_utils         L0241 ERROR| Command 'vgdisplay avocado_vg' failed.
stdout: b''
stderr: b'  Volume group "avocado_vg" not found\n  Cannot process volume group avocado_vg\n'
additional_info: None
2020-04-23 17:42:43,491 process          L0604 INFO | Running 'lvdisplay avocado_vg'
2020-04-23 17:42:43,505 process          L0436 DEBUG| [stderr]   Volume group "avocado_vg" not found
2020-04-23 17:42:43,506 process          L0436 DEBUG| [stderr]   Cannot process volume group avocado_vg
2020-04-23 17:42:43,678 process          L0686 INFO | Command 'lvdisplay avocado_vg' finished with 5 after 0.185683012008667s
2020-04-23 17:42:43,681 process          L0604 INFO | Running 'lvdisplay avocado_vg'
2020-04-23 17:42:43,695 process          L0436 DEBUG| [stderr]   Volume group "avocado_vg" not found
2020-04-23 17:42:43,696 process          L0436 DEBUG| [stderr]   Cannot process volume group avocado_vg
2020-04-23 17:42:43,828 process          L0686 INFO | Command 'lvdisplay avocado_vg' finished with 5 after 0.14595365524291992s
2020-04-23 17:42:43,833 process          L0604 INFO | Running 'fdisk -l /dev/nvme1n1 /dev/nvme1n2 /dev/nvme1n3 /dev/nvme1n4'
2020-04-23 17:42:43,836 process          L0436 DEBUG| [stderr] fdisk: cannot open /dev/nvme1n1: Input/output error
2020-04-23 17:42:43,836 process          L0436 DEBUG| [stdout]
2020-04-23 17:42:43,836 process          L0686 INFO | Command 'fdisk -l /dev/nvme1n1 /dev/nvme1n2 /dev/nvme1n3 /dev/nvme1n4' finished with 1 after 0.0016148090362548828s
2020-04-23 17:42:43,836 process          L0436 DEBUG| [stderr] fdisk: cannot open /dev/nvme1n2: Input/output error
2020-04-23 17:42:43,837 process          L0436 DEBUG| [stdout]
2020-04-23 17:42:43,837 process          L0436 DEBUG| [stderr] fdisk: cannot open /dev/nvme1n3: Input/output error
2020-04-23 17:42:43,837 process          L0436 DEBUG| [stdout]
2020-04-23 17:42:43,838 process          L0436 DEBUG| [stderr] fdisk: cannot open /dev/nvme1n4: Input/output error
2020-04-23 17:42:43,838 process          L0436 DEBUG| [stdout]
2020-04-23 17:42:43,838 process          L0436 DEBUG| [stdout]
2020-04-23 17:42:43,838 process          L0436 DEBUG| [stdout]
2020-04-23 17:42:43,840 stacktrace       L0039 ERROR|
2020-04-23 17:42:43,840 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:854
2020-04-23 17:42:43,841 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-04-23 17:42:43,841 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/lvsetup.py", line 97, in setUp
2020-04-23 17:42:43,841 stacktrace       L0045 ERROR|     self.lv_size = int(lv_utils.get_diskspace(self.disk)) / 2330168
2020-04-23 17:42:43,842 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/lv_utils.py", line 49, in get_diskspace
2020-04-23 17:42:43,842 stacktrace       L0045 ERROR|     env={"LANG": "C"}, sudo=True).stdout_text
2020-04-23 17:42:43,842 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/process.py", line 1037, in run
2020-04-23 17:42:43,842 stacktrace       L0045 ERROR|     raise CmdError(cmd, sp.result)
2020-04-23 17:42:43,842 stacktrace       L0045 ERROR| avocado.utils.process.CmdError: Command 'fdisk -l /dev/nvme1n1 /dev/nvme1n2 /dev/nvme1n3 /dev/nvme1n4' failed.
2020-04-23 17:42:43,842 stacktrace       L0045 ERROR| stdout: b'\n\n\n\n\n\n'
2020-04-23 17:42:43,842 stacktrace       L0045 ERROR| stderr: b'fdisk: cannot open /dev/nvme1n1: Input/output error\nfdisk: cannot open /dev/nvme1n2: Input/output error\nfdisk: cannot open /dev/nvme1n3: Input/output error\nfdisk: cannot open /dev/nvme1n4: Input/output error\n'

```

**Comment by narasimhan-v** [comment]
system access details please. have not seen this issue elsewhere.

**Comment by narasimhan-v** [comment]
@abdhaleegit pinging for notification

**Comment by smruti77** [comment]
not getting this issue, test is working fine.
```
JOB ID     : dfd340230bd4a6c373d9f377b44b0c844746f3d2
JOB LOG    : /root/avocado/job-results/job-2020-06-11T04.47-dfd3402/job.log
 (01/25) lvsetup.py:Lvsetup.test;ext2-1a7b: PASS (4.00 s)
 (02/25) lvsetup.py:Lvsetup.test_vg_recreate;ext2-1a7b: PASS (44.97 s)
 (03/25) lvsetup.py:Lvsetup.test_lv_snapshot;ext2-1a7b: PASS (7.91 s)
 (04/25) lvsetup.py:Lvsetup.test_create_lv;ext2-1a7b: PASS (2.51 s)
 (05/25) lvsetup.py:Lvsetup.test_delete_lv;ext2-1a7b: PASS (2.30 s)
 (06/25) lvsetup.py:Lvsetup.test;ext3-ca44: PASS (3.93 s)
 (07/25) lvsetup.py:Lvsetup.test_vg_recreate;ext3-ca44: PASS (44.89 s)
 (08/25) lvsetup.py:Lvsetup.test_lv_snapshot;ext3-ca44: PASS (7.40 s)
 (09/25) lvsetup.py:Lvsetup.test_create_lv;ext3-ca44: PASS (2.30 s)
 (10/25) lvsetup.py:Lvsetup.test_delete_lv;ext3-ca44: PASS (1.92 s)
 (11/25) lvsetup.py:Lvsetup.test;ext4-50f2: PASS (3.44 s)
 (12/25) lvsetup.py:Lvsetup.test_vg_recreate;ext4-50f2: PASS (44.31 s)
 (13/25) lvsetup.py:Lvsetup.test_lv_snapshot;ext4-50f2: PASS (7.03 s)
 (14/25) lvsetup.py:Lvsetup.test_create_lv;ext4-50f2: PASS (2.42 s)
 (15/25) lvsetup.py:Lvsetup.test_delete_lv;ext4-50f2: PASS (2.01 s)
 (16/25) lvsetup.py:Lvsetup.test;xfs-1c8e: PASS (3.96 s)
 (17/25) lvsetup.py:Lvsetup.test_vg_recreate;xfs-1c8e: PASS (45.21 s)
 (18/25) lvsetup.py:Lvsetup.test_lv_snapshot;xfs-1c8e: PASS (7.65 s)
 (19/25) lvsetup.py:Lvsetup.test_create_lv;xfs-1c8e: PASS (2.98 s)
 (20/25) lvsetup.py:Lvsetup.test_delete_lv;xfs-1c8e: PASS (2.79 s)
 (21/25) lvsetup.py:Lvsetup.test;btrfs-b48d: CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.01 s)
 (22/25) lvsetup.py:Lvsetup.test_vg_recreate;btrfs-b48d: CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.01 s)
 (23/25) lvsetup.py:Lvsetup.test_lv_snapshot;btrfs-b48d: CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.01 s)
 (24/25) lvsetup.py:Lvsetup.test_create_lv;btrfs-b48d: CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.01 s)
 (25/25) lvsetup.py:Lvsetup.test_delete_lv;btrfs-b48d: CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.01 s)
RESULTS    : PASS 20 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 5
JOB HTML   : /root/avocado/job-results/job-2020-06-11T04.47-dfd3402/results.html
JOB TIME   : 245.14 s
```

**Comment by narasimhan-v** [comment]
@abdhaleegit Please close this if we are not seeing this issue anymore

**Comment by Naresh-ibm** [comment]
re-checked this and it is working fine. please open a new issue if you still see this.
