### ISSUE TITLE
[nvme] blkdiscard test fails on nvme disk :Operation not supported

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1731]
```
2020-04-23 17:57:46,163 process          L0604 INFO | Running 'ls /dev/nvme0n1'
2020-04-23 17:57:46,165 process          L0436 DEBUG| [stdout] /dev/nvme0n1
2020-04-23 17:57:46,165 process          L0686 INFO | Command 'ls /dev/nvme0n1' finished with 0 after 0.0009481906890869141s
2020-04-23 17:57:46,167 process          L0604 INFO | Running 'blkdiscard -V'
2020-04-23 17:57:46,169 process          L0436 DEBUG| [stdout] blkdiscard from util-linux 2.32.1
2020-04-23 17:57:46,170 process          L0686 INFO | Command 'blkdiscard -V' finished with 0 after 0.0011224746704101562s
2020-04-23 17:57:46,172 process          L0604 INFO | Running 'fdisk -l /dev/nvme0n1'
2020-04-23 17:57:46,175 process          L0436 DEBUG| [stdout] Disk /dev/nvme0n1: 91.6 GiB, 98304000000 bytes, 24000000 sectors
2020-04-23 17:57:46,175 process          L0686 INFO | Command 'fdisk -l /dev/nvme0n1' finished with 0 after 0.0016779899597167969s
2020-04-23 17:57:46,175 process          L0436 DEBUG| [stdout] Units: sectors of 1 * 4096 = 4096 bytes
2020-04-23 17:57:46,176 process          L0436 DEBUG| [stdout] Sector size (logical/physical): 4096 bytes / 4096 bytes
2020-04-23 17:57:46,176 process          L0436 DEBUG| [stdout] I/O size (minimum/optimal): 4096 bytes / 4096 bytes
2020-04-23 17:57:46,178 process          L0604 INFO | Running 'blkdiscard /dev/nvme0n1 -o 0 -v -l 98304000000'
2020-04-23 17:57:46,180 process          L0436 DEBUG| [stderr] blkdiscard: /dev/nvme0n1: BLKDISCARD ioctl failed: Operation not supported
2020-04-23 17:57:46,180 process          L0686 INFO | Command 'blkdiscard /dev/nvme0n1 -o 0 -v -l 98304000000' finished with 1 after 0.0014998912811279297s
2020-04-23 17:57:46,182 stacktrace       L0039 ERROR|
2020-04-23 17:57:46,182 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:865
2020-04-23 17:57:46,183 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-04-23 17:57:46,183 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/decorators.py", line 51, in wrapper
2020-04-23 17:57:46,183 stacktrace       L0045 ERROR|     return func(*args, **kwargs)
2020-04-23 17:57:46,184 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/ssd/blkdiscard.py", line 66, in test
2020-04-23 17:57:46,184 stacktrace       L0045 ERROR|     process.run(cmd, shell=True)
2020-04-23 17:57:46,184 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/process.py", line 1037, in run
2020-04-23 17:57:46,184 stacktrace       L0045 ERROR|     raise CmdError(cmd, sp.result)
2020-04-23 17:57:46,184 stacktrace       L0045 ERROR| avocado.utils.process.CmdError: Command 'blkdiscard /dev/nvme0n1 -o 0 -v -l 98304000000' failed.
2020-04-23 17:57:46,184 stacktrace       L0045 ERROR| stdout: b''
2020-04-23 17:57:46,184 stacktrace       L0045 ERROR| stderr: b'blkdiscard: /dev/nvme0n1: BLKDISCARD ioctl failed: Operation not supported\n'
2020-04-23 17:57:46,184 stacktrace       L0045 ERROR| additional_info: None
2020-04-23 17:57:46,185 stacktrace       L0045 ERROR|
2020-04-23 17:57:46,185 stacktrace       L0045 ERROR| The above exception was the direct cause of the following exception:
2020-04-23 17:57:46,185 stacktrace       L0045 ERROR|
2020-04-23 17:57:46,185 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-04-23 17:57:46,185 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/decorators.py", line 55, in wrapper
2020-04-23 17:57:46,185 stacktrace       L0045 ERROR|     raise signal(repr(details)) from details
2020-04-23 17:57:46,185 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: CmdError('blkdiscard /dev/nvme0n1 -o 0 -v -l 98304000000', <avocado.utils.process.CmdResult object at 0x7fff8e472160>)
2020-04-23 17:57:46,185 stacktrace       L0046 ERROR|
2020-04-23 17:57:46,186 test             L0870 DEBUG| Local variables:
2020-04-23 17:57:46,243 test             L0873 DEBUG|  -> kwargs <class 'dict'>: {}
2020-04-23 17:57:46,243 test             L0873 DEBUG|  -> args <class 'tuple'>: (Test('1-avocado-misc-tests/io/disk/ssd/blkdiscard.py:Blkdiscard.test;scenario-6a88'),)
2020-04-23 17:57:46,243 test             L0873 DEBUG|  -> signal <class 'type'>: <class 'avocado.core.exceptions.TestFail'>
2020-04-23 17:57:46,243 test             L0873 DEBUG|  -> func <class 'function'>: <function Blkdiscard.test at 0x7fff8e47a400>
2020-04-23 17:57:46,243 test             L0873 DEBUG|  -> exceptions <class 'type'>: <class 'Exception'>

```

**Comment by narasimhan-v** [comment]
@abdhaleegit can you please point me to the system or get me the output of `nvme id-ctrl /dev/nvme0 -H | grep oncs -A7`

**Comment by smruti77** [comment]
this is also running fine.
```JOB ID     : 471fc898687af03adff022b0ff6a6edbacca913f
JOB LOG    : /root/avocado/job-results/job-2020-06-09T00.59-471fc89/job.log
 (1/1) blkdiscard.py:Blkdiscard.test;scenario-6a88: PASS (1.12 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-06-09T00.59-471fc89/results.html
JOB TIME   : 1.86 s
```

**Comment by narasimhan-v** [comment]
@smruti77 is this on the system it failed ?

**Comment by smruti77** [comment]
on different system

**Comment by Naresh-ibm** [comment]
localhost:~/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/ssd # avocado run --max-parallel-tasks=1 blkdiscard.py -m blkdiscard.py.data/blkdiscard.yaml
JOB ID     : 30dd36aa0afd8ff6de2e63068ea421d94da7059a
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-01-19T04.38-30dd36a/job.log
 (1/1) blkdiscard.py:Blkdiscard.test;run-scenario-d915: STARTED
 (1/1) blkdiscard.py:Blkdiscard.test;run-scenario-d915: PASS (1.30 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-01-19T04.38-30dd36a/results.html
JOB TIME   : 25.48 s
localhost:~/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/ssd # 



working fine. hence closing
