### ISSUE TITLE
[nvme] firmware upgrade test: make fail for upstream cli

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1732]
```
2020-04-23 17:57:49,450 process          L0436 DEBUG| [stdout]     CC util/argconfig.o
2020-04-23 17:57:49,489 process          L0436 DEBUG| [stdout]     CC util/suffix.o
2020-04-23 17:57:49,616 process          L0436 DEBUG| [stdout]     CC util/json.o
2020-04-23 17:57:49,621 process          L0436 DEBUG| [stdout]     CC util/parser.o
2020-04-23 17:57:50,977 process          L0436 DEBUG| [stderr] cc1: all warnings being treated as errors
2020-04-23 17:57:50,981 process          L0436 DEBUG| [stderr] make: *** [Makefile:93: plugins/wdc/wdc-nvme.o] Error 1
2020-04-23 17:57:50,981 process          L0436 DEBUG| [stderr] make: *** Waiting for unfinished jobs....
2020-04-23 17:57:51,502 process          L0686 INFO | Command 'make' finished with 2 after 2.5859975814819336s
2020-04-23 17:57:51,508 stacktrace       L0039 ERROR|
2020-04-23 17:57:51,508 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:854
2020-04-23 17:57:51,509 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-04-23 17:57:51,509 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/ssd/nvmetest.py", line 61, in setUp
2020-04-23 17:57:51,509 stacktrace       L0045 ERROR|     build.make(".")
2020-04-23 17:57:51,509 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/build.py", line 118, in make
2020-04-23 17:57:51,510 stacktrace       L0045 ERROR|     result = run_make(path, make, extra_args, kwargs)
2020-04-23 17:57:51,510 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/build.py", line 84, in run_make
2020-04-23 17:57:51,510 stacktrace       L0045 ERROR|     make_process = process.run(cmd, **process_kwargs)
2020-04-23 17:57:51,510 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/process.py", line 1037, in run
2020-04-23 17:57:51,510 stacktrace       L0045 ERROR|     raise CmdError(cmd, sp.result)
2020-04-23 17:57:51,510 stacktrace       L0045 ERROR| avocado.utils.process.CmdError: Command 'make' failed.
2020-04-23 17:57:51,510 stacktrace       L0045 ERROR| stdout: b'    CC nvme-print.o\n    CC nvme-ioctl.o\n    CC nvme-lightnvm.o\n    CC fabrics.o\n    CC nvme-models.o\n    CC plugin.o\n    CC nvme-status.o\n    CC nvme-filters.o\n    CC nvme-topology.o\n    CC plugins/intel/intel-nvme.o\n    CC plugins/lnvm/lnvm-nvme.o\n    CC plugins/memblaze/memblaze-nvme.o\n    CC plugins/wdc/wdc-nvme.o\n    CC plugins/wdc/wdc-utils.o\n    CC plugins/huawei/huawei-nvme.o\n    CC plugins/netapp/netapp-nvme.o\n    CC plugins/toshiba/toshiba-nvme.o\n    CC plugins/micron/micron-nvme.o\n    CC plugins/seagate/seagate-nvme.o\n    CC plugins/virtium/virtium-nvme.o\n    CC plugins/shannon/shannon-nvme.o\n    CC plugins/dera/dera-nvme.o\n    CC plugins/transcend/transcend-nvme.o\n    CC util/argconfig.o\n    CC util/suffix.o\n    CC util/json.o\n    CC util/parser.o\n'
2020-04-23 17:57:51,510 stacktrace       L0045 ERROR| stderr: b'plugins/wdc/wdc-nvme.c: In function \xe2\x80\x98wdc_do_cap_dui\xe2\x80\x99:\nplugins/wdc/wdc-nvme.c:1657:51: error: format \xe2\x80\x98%llx\xe2\x80\x99 expects argument of type \xe2\x80\x98long long unsigned int\xe2\x80\x99, but argument 4 has type \xe2\x80\x98__u64\xe2\x80\x99 {aka \xe2\x80\x98long unsigned int\xe2\x80\x99} [-Werror=format=]\n     fprintf(stderr, "%s: INFO : WDC : Offset 0x%llx exceeds total size 0x%llx, no data retrieved\\n",\n                                                ~~~^\n                                                %lx\n      __func__, offset, total_size);\n                ~~~~~~                              \nplugins/wdc/wdc-nvme.c:1657:77: error: format \xe2\x80\x98%llx\xe2\x80\x99 expects argument of type \xe2\x80\x98long long unsigned int\xe2\x80\x99, but argument 5 has type \xe2\x80\x98__s64\xe2\x80\x99 {aka \xe2\x80\x98long int\xe2\x80\x99} [-Werror=format=]\n     fprintf(stderr, "%s: INFO : WDC : Offset 0x%llx exceeds total size 0x%llx, no data retrieved\\n",\n                                                                          ~~~^\n                                                                          %lx\n      __func__, offset, total_size);\n                        ~~~~~~~~~~                                            \nplugins/wdc/wdc-nvme.c:1689:52: error: format \xe2\x80\x98%llx\xe2\x80\x99 expects argument of type \xe2\x80\x98long long unsigned int\xe2\x80\x99, but argument 4 has type \xe2\x80\x98__u64\xe2\x80\x99 {aka \xe2\x80\x98long unsigned int\xe2\x80\x99} [-Werror=format=]\n      fprintf(stderr, "%s: INFO : WDC : Offset 0x%llx, file size 0x%llx, total size 0x%llx, log size 0x%llx\\n",\n                                                 ~~~^\n                                                 %lx\n       __func__, offset, file_size, total_size, log_size);\n                 ~~~~~~                              \nplugins/wdc/wdc-nvme.c:1689:70: error: format \xe2\x80\x98%llx\xe2\x80\x99 expects argument of type \xe2\x80\x98long long unsigned int\xe2\x80\x99, but argument 5 has type \xe2\x80\x98__u64\xe2\x80\x99 {aka \xe2\x80\x98long unsigned int\xe2\x80\x99} [-Werror=format=]\n      fprintf(stderr, "%s: INFO : WDC : Offset 0x%llx, file size 0x%llx, total size 0x%llx, log size 0x%llx\\n",\n                                                                   ~~~^\n                                                                   %lx\n       __func__, offset, file_size, total_size, log_size);\n                         ~~~~~~~~~                                     \nplugins/wdc/wdc-nvme.c:1689:89: error: format \xe2\x80\x98%llx\xe2\x80\x99 expects argument of type \xe2\x80\x98long long unsigned int\xe2\x80\x99, but argument 6 has type \xe2\x80\x98__s64\xe2\x80\x99 {aka \xe2\x80\x98long int\xe2\x80\x99} [-Werror=format=]\n      fprintf(stderr, "%s: INFO : WDC : Offset 0x%llx, file size 0x%llx, total size 0x%llx, log size 0x%llx\\n",\n                                                                                      ~~~^\n                                                                                      %lx\n       __func__, offset, file_size, total_size, log_size);\n                                    ~~~~~~~~~~                                            \nplugins/wdc/wdc-nvme.c:1689:106: error: format \xe2\x80\x98%llx\xe2\x80\x99 expects argument of type \xe2\x80\x98long long unsigned int\xe2\x80\x99, but argument 7 has type \xe2\x80\x98__s64\xe2\x80\x99 {aka \xe2\x80\x98long int\xe2\x80\x99} [-Werror=format=]\n      fprintf(stderr, "%s: INFO : WDC : Offset 0x%llx, file size 0x%llx, total size 0x%llx, log size 0x%llx\\n",\n                                                                                                       ~~~^\n                                                                                                       %lx\n       __func__, offset, file_size, total_size, log_size);\n                                                ~~~~~~~~                                                   \ncc1: all warnings being treated as errors\nmake: *** [Makefile:93: plugins/wdc/wdc-nvme.o] Error 1\nmake: *** Waiting for unfinished jobs....\n'
2020-04-23 17:57:51,511 stacktrace       L0045 ERROR| additional_info: None

```

**Comment by narasimhan-v** [comment]
fixed by removing this from cfg for now. sent a patch for the same

**Comment by narasimhan-v** [comment]
Fixed via https://github.com/linux-nvme/nvme-cli/issues/716
