### ISSUE TITLE
[eeh/fc] eeh test failed with error  Unable to get 'Class' property of given pci address

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1733]
```
2020-05-05 08:55:31,931 parameters       L0143 DEBUG| PARAMS (key=pci_device, path=*, default=) => '0012:52:00.0'
2020-05-05 08:55:31,932 parameters       L0143 DEBUG| PARAMS (key=additional_command, path=*, default=) => ''
2020-05-05 08:55:31,932 process          L0604 INFO | Running 'echo 1 > /sys/kernel/debug/powerpc/eeh_max_freezes'
2020-05-05 08:55:31,935 process          L0686 INFO | Command 'echo 1 > /sys/kernel/debug/powerpc/eeh_max_freezes' finished with 0 after 0.0010952949523925781s
2020-05-05 08:55:31,936 parameters       L0143 DEBUG| PARAMS (key=function, path=*, default=None) => 4
2020-05-05 08:55:33,041 software_manager L0516 DEBUG| dnf version: 4.2.7
2020-05-05 08:55:33,042 software_manager L0498 ERROR| dnf module for Python is required. Using the basic support from rpm and dnf commands
2020-05-05 08:55:33,042 process          L0604 INFO | Running 'rpm -q pciutils'
2020-05-05 08:55:33,057 process          L0436 DEBUG| [stdout] pciutils-3.5.6-4.el8.ppc64le
2020-05-05 08:55:33,058 process          L0686 INFO | Command 'rpm -q pciutils' finished with 0 after 0.013656854629516602s
2020-05-05 08:55:33,068 PowerVMEEH       L0080 INFO | ===============Testing EEH Frozen PE==================
2020-05-05 08:55:33,069 process          L0604 INFO | Running 'lspci -bv -s 0012:52:00.0'
2020-05-05 08:55:33,073 process          L0686 INFO | Command 'lspci -bv -s 0012:52:00.0' finished with 0 after 0.0028183460235595703s
2020-05-05 08:55:33,074 process          L0604 INFO | Running 'lspci -vv -s 0012:52:00.0'
2020-05-05 08:55:33,080 process          L0686 INFO | Command 'lspci -vv -s 0012:52:00.0' finished with 0 after 0.0036919116973876953s
2020-05-05 08:55:33,080 process          L0604 INFO | Running 'lspci -Dnvmm -s 0012:52:00.0'
2020-05-05 08:55:33,086 process          L0686 INFO | Command 'lspci -Dnvmm -s 0012:52:00.0' finished with 0 after 0.0036432743072509766s
2020-05-05 08:55:33,086 stacktrace       L0039 ERROR|
2020-05-05 08:55:33,086 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:865
2020-05-05 08:55:33,087 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-05 08:55:33,088 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/PowerVMEEH.py", line 92, in test_eeh_basic_pe
2020-05-05 08:55:33,088 stacktrace       L0045 ERROR|     self.pci_class_name = pci.get_pci_class_name(self.addr)
2020-05-05 08:55:33,088 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/utils/pci.py", line 156, in get_pci_class_name
2020-05-05 08:55:33,088 stacktrace       L0045 ERROR|     "address %s" % pci_address)
2020-05-05 08:55:33,088 stacktrace       L0045 ERROR| ValueError: Unable to get 'Class' property of given pci address 0012:52:00.0
2020-05-05 08:55:33,088 stacktrace       L0046 ERROR|
2020-05-05 08:55:33,089 test             L0870 DEBUG| Local variables:
2020-05-05 08:55:33,174 test             L0873 DEBUG|  -> num_of_hit <class 'int'>: 0
2020-05-05 08:55:33,174 test             L0873 DEBUG|  -> num_of_miss <class 'int'>: 0
2020-05-05 08:55:33,174 test             L0873 DEBUG|  -> enter_loop <class 'bool'>: True
2020-05-05 08:55:33,175 test             L0873 DEBUG|  -> self <class 'PowerVMEEH.PowerVMEEH'>: 1-avocado-misc-tests/io/pci/PowerVMEEH.py:PowerVMEEH.test_eeh_basic_pe;scenario-7f64
2020-05-05 08:55:33,175 test             L0299 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2020-05-05 08:55:33,176 test             L0299 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2020-05-05 08:55:33,176 test             L0299 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2020-05-05 08:55:33,304 sysinfo          L0173 DEBUG| Not logging 'dmidecode' (command 'dmidecode' was not found)
2020-05-05 08:55:33,309 sysinfo          L0173 DEBUG| Not logging 'brctl show' (command 'brctl' was not found)
2020-05-05 08:55:33,314 sysinfo          L0105 DEBUG| Not logging /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor (file does not exist)
2020-05-05 08:55:33,319 sysinfo          L0105 DEBUG| Not logging /proc/pci (file does not exist)
2020-05-05 08:55:33,507 sysinfo          L0237 ERROR| Daemon process 'journalctl -f' (pid 19655) terminated abnormally (code 0)
2020-05-05 08:55:33,507 process          L0604 INFO | Running 'kill -19 19659'
2020-05-05 08:55:33,510 process          L0686 INFO | Command 'kill -19 19659' finished with 0 after 0.001010894775390625s
2020-05-05 08:55:33,584 process          L0604 INFO | Running 'kill -9 19659'
2020-05-05 08:55:33,587 process          L0686 INFO | Command 'kill -9 19659' finished with 0 after 0.0009548664093017578s
2020-05-05 08:55:33,588 process          L0604 INFO | Running 'kill -18 19659'
2020-05-05 08:55:33,591 process          L0686 INFO | Command 'kill -18 19659' finished with 0 after 0.0009229183197021484s
2020-05-05 08:55:33,592 test             L1018 ERROR| Traceback (most recent call last):

2020-05-05 08:55:33,592 test             L1018 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocad
```

**Comment by narasimhan-v** [comment]
@abdhaleegit some newer pci classes needs to be added into the avocado utils.
Can you get me the system access or `lspci -nnvmm -s <pci address>` output so that I can send a patch.

**Comment by smruti77** [comment]
@abdhaleegit this test is working fine, we will get this error when pci address will not pass as string.
```JOB ID     : c1bf7824264502edee9d9505144bcf00d305a5f1
JOB LOG    : /root/avocado/job-results/job-2020-06-09T00.47-c1bf782/job.log
 (1/1) PowerVMEEH.py:PowerVMEEH.test_eeh_basic_pe;scenario-b7a8: WARN: Test passed but there were warnings during execution. Check the log for details. (51.14 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 1 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-06-09T00.47-c1bf782/results.html
JOB TIME   : 51.68 s
```

**Comment by narasimhan-v** [comment]
@smruti77 there are still some pci devices for which we need to add class names in avocado utils. So, let us confirm if that is the case with the system on which this error is seen.

**Comment by smruti77** [comment]
@narasimhan-v i tried on different system.

**Comment by narasimhan-v** [comment]
Waiting for ssytem and adapter details to add to avocado utils @abdhaleegit

**Comment by abdhaleegit** [comment]
closing as this is fixed
