### ISSUE TITLE
FIO run failed on fc multipath device 

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1738]
```
2020-05-14 18:00:45,828 fiotest          L0212 INFO | Test will run on /dev/mapper/mpatha
2020-05-14 18:00:45,828 parameters       L0143 DEBUG| PARAMS (key=fio_job, path=*, default=fio-simple.job) => 'fio-simple.job'
2020-05-14 18:00:45,829 test             L0295 DEBUG| DATA (filename=fio-simple.job) => /home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/fiotest.py.data/fio-simple.job (found at file source dir)
2020-05-14 18:00:45,830 process          L0607 INFO | Running '/var/tmp/avocado_7_62_8yu/fio/fio /home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/fiotest.py.data/fio-simple.job /dev/mapper/mpatha --filename=fiotest-image'
2020-05-14 18:00:45,998 process          L0439 DEBUG| [stderr] fio: option <�> outside of [] job section
2020-05-14 18:00:46,027 process          L0439 DEBUG| [stdout] file1: (g=0): rw=randrw, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=sync, iodepth=1
2020-05-14 18:00:46,027 process          L0689 INFO | Command '/var/tmp/avocado_7_62_8yu/fio/fio /home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/fiotest.py.data/fio-simple.job /dev/mapper/mpatha --filename=fiotest-image' finished with 1 after 0.19475412368774414s
2020-05-14 18:00:46,027 process          L0439 DEBUG| [stdout] file2: (g=1): rw=randrw, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=posixaio, iodepth=4
2020-05-14 18:00:46,028 process          L0439 DEBUG| [stdout] file3: (g=2): rw=randrw, bs=(R) 512MiB-512MiB, (W) 512MiB-512MiB, (T) 512MiB-512MiB, ioengine=mmap, iodepth=1
2020-05-14 18:00:46,028 process          L0439 DEBUG| [stdout] file4: (g=3): rw=randrw, bs=(R) 1024MiB-1024MiB, (W) 1024MiB-1024MiB, (T) 1024MiB-1024MiB, ioengine=splice, iodepth=1
2020-05-14 18:00:46,028 process          L0439 DEBUG| [stdout] seq-write: (g=4): rw=write, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=posixaio, iodepth=4
2020-05-14 18:00:46,029 process          L0439 DEBUG| [stdout] rand-write: (g=5): rw=randwrite, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=splice, iodepth=1
2020-05-14 18:00:46,029 process          L0439 DEBUG| [stdout] seq-readwrite: (g=6): rw=rw, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=mmap, iodepth=1
2020-05-14 18:00:46,029 process          L0439 DEBUG| [stdout] rand-readwrite: (g=7): rw=randrw, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=mmap, iodepth=1
2020-05-14 18:00:46,033 stacktrace       L0039 ERROR|
2020-05-14 18:00:46,033 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py:865
2020-05-14 18:00:46,034 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-05-14 18:00:46,035 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/fiotest.py", line 218, in test
2020-05-14 18:00:46,035 stacktrace       L0045 ERROR|     self.fail("fio run failed")
2020-05-14 18:00:46,035 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-78.0-py3.6.egg/avocado/core/test.py", line 1054, in fail
2020-05-14 18:00:46,035 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-05-14 18:00:46,035 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: fio run failed
2020-05-14 18:00:46,036 stacktrace       L0046 ERROR|
2020-05-14 18:00:46,036 test             L0870 DEBUG| Local variables:
2020-05-14 18:00:46,123 test             L0873 DEBUG|  -> cmd <class 'str'>: /var/tmp/avocado_7_62_8yu/fio/fio /home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/fiotest.py.data/fio-simple.job /dev/mapper/mpatha --filename=fiotest-image

```

**Comment by abdhaleegit** [comment]
@Naresh-ibm take a look

**Comment by Naresh-ibm** [comment]
> @Naresh-ibm take a look

sure

**Comment by narasimhan-v** [comment]
This is a generic issue with all devices, when run on raw disk, randrw tests fail
