### ISSUE TITLE
After run livepatch.py in Rhel8.1 with Avocado(version:79.0), it shows " ERROR: Command 'make' failed."

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1750]
【Test Result】
After run livepatch.py in Rhel8.1 with Avocado(version:79.0), it shows " ERROR: Command 'make' failed.". 

《SOL log》
(1/1) livepatch.py:Livepatch.test: ERROR: Command 'make' failed.\nstdout: b'make -C /lib/modules/4.18.0-147.8.1.el8_1.ppc64le/build SUBDI                           RS=/var/tmp/tmps_b58vlc modules\n'\nstderr: b'make[1]: *** /lib/modules/4.18.0-147.8.1.el8_1.ppc64le/build: No such file or directory.  St                           op.\nmake: *** [Makefile...

《job log》
INFO | ============== Building livepatching Module =================
INFO | Asset not in cache, fetching it.
INFO | Fetching https://raw.githubusercontent.com/torvalds/linux/master/samples/livepatch/livepatch-sample.c -> /root/tests/data/cache/by_location/7a183b884fa2e313f5ee9ba0e8bd65fbdd6adf2d/livepatch-sample.c.wqs0vxp7
DEBUG| Retrieved URL "https://raw.githubusercontent.com/torvalds/linux/master/samples/livepatch/livepatch-sample.c": content-length 1370, date: "Wed, 27 May 2020 01:28:00 GMT", last-modified: "UNKNOWN"
INFO | Running 'make'
DEBUG| [stdout] make -C /lib/modules/4.18.0-147.8.1.el8_1.ppc64le/build SUBDIRS=/var/tmp/tmpab08acre modules
INFO | Command 'make' finished with 2 after 0.005547285079956055s
DEBUG| [stderr] make[1]: *** /lib/modules/4.18.0-147.8.1.el8_1.ppc64le/build: No such file or directory.  Stop.
DEBUG| [stderr] make: *** [Makefile:5: default] Error 2
ERROR|
ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-79.0-py3.6.egg/avocado/core/test.py:865
ERROR| Traceback (most recent call last):
ERROR|   File "/root/tests/tests/avocado-misc-tests/kernel/livepatch.py", line 167, in test
ERROR|     self.build_module()
ERROR|   File "/root/tests/tests/avocado-misc-tests/kernel/livepatch.py", line 111, in build_module
ERROR|     if build.make(self.sourcedir) >= 1:
ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-79.0-py3.6.egg/avocado/utils/build.py", line 118, in make
ERROR|     result = run_make(path, make, extra_args, kwargs)
ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-79.0-py3.6.egg/avocado/utils/build.py", line 84, in run_make
ERROR|     make_process = process.run(cmd, **process_kwargs)
ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-79.0-py3.6.egg/avocado/utils/process.py", line 1040, in run
ERROR|     raise CmdError(cmd, sp.result)
ERROR| avocado.utils.process.CmdError: Command 'make' failed.
ERROR| stdout: b'make -C /lib/modules/4.18.0-147.8.1.el8_1.ppc64le/build SUBDIRS=/var/tmp/tmpab08acre modules\n'
ERROR| stderr: b'make[1]: *** /lib/modules/4.18.0-147.8.1.el8_1.ppc64le/build: No such file or directory.  Stop.\nmake: *** [Makefile:5: default] Error 2\n'
ERROR| additional_info: None
ERROR|
DEBUG| Local variables:
DEBUG|  -> self <class 'livepatch.Livepatch'>: 1-livepatch.py:Livepatch.test
DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
DEBUG| Not logging 'dmidecode' (command 'dmidecode' was not found)
DEBUG| Not logging /proc/pci (file does not exist)
DEBUG| Not logging 'brctl show' (command 'brctl' was not found)

【Expect Result】
After run livepatch.py, it should show PASS. 

【Test Steps】
Run livepatch.py via cmd “avocado run livepatch.py”.

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW configuration]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW configuration]
CPU DD2.3 20core *2
Samsung (M393A8K40B22-CWD6Y) 64G *32
Seagate Jaguar 400GB *1
PSU ACBEL 2000w *2

【Test log】: 
[20200527_livepatch_Test-log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4686046/20200527_livepatch_Test-log.zip)

**Comment by PraveenPenguin** [comment]
@Gene-Lo here seems me the issue with kernel-devel and running kernel mismatch that's why it not able to get build directory please check that, as I am not able to reproduce this issue in my setup

**Comment by Gene-Lo** [comment]
@PraveenPenguin 
Excuse me that what kernel-level (EX. 4.18.0-147.8.1.el8_1.ppc64le) did you adopt and run PASS?

**Comment by sacsant** [comment]
I was execute the test correctly on a RHEL 8.x.

 # avocado run kernel/livepatch.py 
JOB ID     : 20f60e5b1a9e541e0bb34ee47af905d65b434b8b
JOB LOG    : /home/results/job-2020-09-01T16.46-20f60e5/job.log
 (1/1) kernel/livepatch.py:Livepatch.test: PASS (183.15 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/results/job-2020-09-01T16.46-20f60e5/results.html
JOB TIME   : 183.84 s
# 

Make sure you have installed correct kernel-level package corresponding to level displayed by uname -r output

**Comment by PraveenPenguin** [comment]
Thanks @sacsant , closing it
