### ISSUE TITLE
After run kprobe.py in Rhel8.1 with Avocado(version:79.0), it shows " FAIL: kprobe probing issues, check dmesg for more information "

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1753]
【Test Result】
After run kprobe.py in Rhel8.1 with Avocado(version:79.0), it shows " FAIL: kprobe probing issues, check dmesg for more information ". 

《SOL-log》
(1/1) kprobe.py:Kprobe.test:  [  694.297479] kprobe_example: loading out-of-tree module taints kernel.
[  694.299511] kprobe_example: module verification failed: signature and/or required key missing - tainting kernel
[  694.302102] Planted kprobe at 00000000bb0f8522
FAIL: kprobe probing issues, check dmesg for more information (3.41 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

《job.log》
INFO | ============== Testing kprobe =================
INFO | Running 'dmesg -C '
INFO | Command 'dmesg -C ' finished with 0 after 0.0012733936309814453s
INFO | executing ============== insmod ./kprobe_example.ko =================
INFO | Running 'insmod ./kprobe_example.ko'
INFO | Command 'insmod ./kprobe_example.ko' finished with 0 after 0.006311893463134766s
INFO | Running 'dmesg |grep -i planted'
DEBUG| [stdout] [  694.302102] Planted kprobe at 00000000bb0f8522
INFO | Command 'dmesg |grep -i planted' finished with 0 after 0.0017857551574707031s
INFO | executing ============== date =================
INFO | Running 'date'
DEBUG| [stdout] Wed May 20 10:27:17 CST 2020
INFO | Command 'date' finished with 0 after 0.0014128684997558594s
INFO | Running 'dmesg |grep -i _do_fork'
INFO | Command 'dmesg |grep -i _do_fork' finished with 1 after 0.0017242431640625s
ERROR|
ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-79.0-py3.6.egg/avocado/core/test.py:865
ERROR| Traceback (most recent call last):
ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/kprobe.py", line 163, in test
ERROR|     self.execute_test()
ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/kprobe.py", line 129, in execute_test
ERROR|     self.fail("kprobe probing issues, check dmesg for more information")
ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-79.0-py3.6.egg/avocado/core/test.py", line 1054, in fail
ERROR|     raise exceptions.TestFail(message)
ERROR| avocado.core.exceptions.TestFail: kprobe probing issues, check dmesg for more information
ERROR|
DEBUG| Local variables:
DEBUG|  -> self <class 'kprobe.Kprobe'>: 1-kprobe.py:Kprobe.test
DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)

【Expect Result】
After run kprobe.py, it should show PASS. 

【Test Steps】
Run kprobe.py via cmd “avocado run kprobe.py”.

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW config]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW config]
CPU DD2.3 20core *2
Micron (MTA18ASF2G72PZ-2G9E1) 16G *4
Seagate Jaguar 400GB *1
PSU ACBEL 2000w *2

【Test log】: 
[202005201027_kprobe_JOB-LOG.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4686513/202005201027_kprobe_JOB-LOG.txt)

**Comment by Gene-Lo** [comment]
After we re-test kprobe.py in Rhel8.2 with Avocado (Version: 80), it shows the same fail:

(1/1) kprobe.py:Kprobe.test:  FAIL: kprobe probing issues, check dmesg for more information (198.77 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

【Test log】
[20200812-RAS-kprobe-job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5081819/20200812-RAS-kprobe-job.log)

【Configuration】

[Rhel8.2 Kernel]
4.18.0-193.14.3.el8_2.ppc64le

[FW config]
BMC: op940.00.mih-5-0-g86f9791c2
PNOR: OP9-v2.4-4.37-prod

[HW config]
CPU DD2.3 20core *2
Micron (MTA18ASF2G72PZ-2G9E1) 16G *16
Samsung PM985 960GB *1
PSU ACBEL 2000w *2
Broadcom 9300-8i SAS/SATA HBA PCIe Gen3 x8 LP @ slot5

**Comment by Gene-Lo** [comment]
After we re-test kprobe.py in Rhel8.2 with Avocado (Version: 82), it shows the same fail:

 (1/1) kprobe.py:Kprobe.test:  FAIL: kprobe probing issues, check dmesg for more information (144.77 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

【job.log】
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5369025/job.log)
L0086 INFO | ============== Building kprobe Module =================
L0320 INFO | Asset not in cache, fetching it.
L0067 INFO | Fetching https://raw.githubusercontent.com/torvalds/linux/master/samples/kprobes/kprobe_example.c -> /root/tests/data/cache/by_location/84d0a6769cb0569c52065a2ce18b92c3a18a42da/kprobe_example.c.f6d822oa
L0051 DEBUG| Retrieved URL "https://raw.githubusercontent.com/torvalds/linux/master/samples/kprobes/kprobe_example.c": content-length 3635, date: "Tue, 13 Oct 2020 04:25:00 GMT", last-modified: "UNKNOWN"
L0604 INFO | Running 'make'
L0416 DEBUG| [stdout] make -C /lib/modules/4.18.0-193.19.1.el8_2.ppc64le/build SUBDIRS=/var/tmp/tmpg13g99jm modules
L0416 DEBUG| [stdout] make[1]: Entering directory '/usr/src/kernels/4.18.0-193.19.1.el8_2.ppc64le'
L0416 DEBUG| [stdout]   CC [M]  /var/tmp/tmpg13g99jm/kprobe_example.o
L0416 DEBUG| [stderr] perl: warning: Setting locale failed.
L0416 DEBUG| [stderr] perl: warning: Please check that your locale settings:
L0416 DEBUG| [stderr] 	LANGUAGE = (unset),
L0416 DEBUG| [stderr] 	LC_ALL = (unset),
L0416 DEBUG| [stderr] 	LC_MEASUREMENT = "lzh_TW",
L0416 DEBUG| [stderr] 	LC_PAPER = "lzh_TW",
L0416 DEBUG| [stderr] 	LC_MONETARY = "lzh_TW",
L0416 DEBUG| [stderr] 	LC_NAME = "lzh_TW",
L0416 DEBUG| [stderr] 	LC_COLLATE = "C",
L0416 DEBUG| [stderr] 	LC_CTYPE = "C.UTF-8",
L0416 DEBUG| [stderr] 	LC_ADDRESS = "lzh_TW",
L0416 DEBUG| [stderr] 	LC_NUMERIC = "C",
L0416 DEBUG| [stderr] 	LC_TELEPHONE = "lzh_TW",
L0416 DEBUG| [stderr] 	LC_IDENTIFICATION = "lzh_TW",
L0416 DEBUG| [stderr] 	LC_TIME = "lzh_TW",
L0416 DEBUG| [stderr] 	LANG = "en_US.UTF-8"
L0416 DEBUG| [stderr]     are supported and installed on your system.
L0416 DEBUG| [stderr] perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
L0416 DEBUG| [stdout]   Building modules, stage 2.
L0416 DEBUG| [stdout]   MODPOST 1 modules
L0416 DEBUG| [stdout]   CC      /var/tmp/tmpg13g99jm/kprobe_example.mod.o
L0416 DEBUG| [stdout]   LD [M]  /var/tmp/tmpg13g99jm/kprobe_example.ko
L0416 DEBUG| [stdout] make[1]: Leaving directory '/usr/src/kernels/4.18.0-193.19.1.el8_2.ppc64le'
L0686 INFO | Command 'make' finished with 0 after 1.1542632579803467s
L0113 INFO | ============== Testing kprobe =================
L0604 INFO | Running 'dmesg -C '
L0686 INFO | Command 'dmesg -C ' finished with 0 after 0.00048422813415527344s
L0038 INFO | executing ============== insmod ./kprobe_example.ko =================
L0604 INFO | Running 'insmod ./kprobe_example.ko'
L0686 INFO | Command 'insmod ./kprobe_example.ko' finished with 0 after 0.006605386734008789s
L0604 INFO | Running 'dmesg |grep -i planted'
L0416 DEBUG| [stdout] [76124.827670] Planted kprobe at 00000000f437b42c
L0686 INFO | Command 'dmesg |grep -i planted' finished with 0 after 0.002098560333251953s
L0038 INFO | executing ============== date =================
L0604 INFO | Running 'date'
L0416 DEBUG| [stdout] Tue Oct 13 12:25:01 CST 2020
L0686 INFO | Command 'date' finished with 0 after 0.0018584728240966797s
L0604 INFO | Running 'dmesg |grep -i _do_fork'
L0686 INFO | Command 'dmesg |grep -i _do_fork' finished with 1 after 0.0018839836120605469s
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:767
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/kprobe.py", line 162, in test
L0045 ERROR|     self.execute_test()
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/kprobe.py", line 128, in execute_test
L0045 ERROR|     self.fail("kprobe probing issues, check dmesg for more information")
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 953, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: kprobe probing issues, check dmesg for more informatio

【Manual-Test】
[Manual-Test-log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5369028/Manual-Test-log.txt)
When we try to manually run commands of job.log, some files are missed, which cannot duplicate the issue of job.log by manual:

[root@sut5 ~]# cd /root/tests/data/cache/by_location/84d0a6769cb0569c52065a2ce18b92c3a18a42da
[root@sut5 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# ls
kprobe_example.c  kprobe_example.c-CHECKSUM
[root@sut5 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# make
make: *** No targets specified and no makefile found.  Stop.
[root@sut5 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# chmod 777 -R *
[root@sut5 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# make
make: *** No targets specified and no makefile found.  Stop.
[root@sut5 84d0a6769cb0569c52065a2ce18b92c3a18a42da]#

[root@sut5 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# insmod ./kprobe_example.ko
insmod: ERROR: could not load module ./kprobe_example.ko: No such file or directory
[root@sut5 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# updatedb
[root@sut5 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# locate kprobe_example.ko
[root@sut5 84d0a6769cb0569c52065a2ce18b92c3a18a42da]#

[root@sut5 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# insmod ./kprobe_example.c
insmod: ERROR: could not insert module ./kprobe_example.c: Invalid module format
[root@sut5 84d0a6769cb0569c52065a2ce18b92c3a18a42da]#

【Configuration】
[Kernel]
4.18.0-193.19.1.el8_2.ppc64le

[FW Config] 
BMC: op940.00.mih-5-0-g86f9791c2
Pnor: OP9-v2.4-4.37-prod

[HW Config]
CPU DD2.3 20 core *2
Samsung Electronics(M393A8K40B22-CWD)64GiB x16
Samsung PM985 960GB *1
PSU ACBEL 2000w *2
Slot1: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP

**Comment by Gene-Lo** [comment]
After we re-test kprobe.py in Rhel8.2 with Avocado (Version: 82) with different Mihawk system, it shows the same fail:

【SOL-log】
 (1/1) kprobe.py:Kprobe.test:  FAIL: kprobe probing issues, check dmesg for more information (145.62 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/tests/results/job-2020-10-14T18.48-3de35a7/results.html
JOB TIME   : 147.29 s

【job.log】
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5382154/job.log)
2020-10-14 18:49:00,446 process          L0604 INFO | Running 'dmesg |grep -i _do_fork'
2020-10-14 18:49:00,448 process          L0686 INFO | Command 'dmesg |grep -i _do_fork' finished with 1 after 0.0016937255859375s
2020-10-14 18:49:00,449 stacktrace       L0039 ERROR| 
2020-10-14 18:49:00,449 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:767
2020-10-14 18:49:00,450 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-10-14 18:49:00,450 stacktrace       L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/kprobe.py", line 162, in test
2020-10-14 18:49:00,450 stacktrace       L0045 ERROR|     self.execute_test()
2020-10-14 18:49:00,450 stacktrace       L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/kprobe.py", line 128, in execute_test
2020-10-14 18:49:00,450 stacktrace       L0045 ERROR|     self.fail("kprobe probing issues, check dmesg for more information")
2020-10-14 18:49:00,450 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 953, in fail
2020-10-14 18:49:00,450 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-10-14 18:49:00,450 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: kprobe probing issues, check dmesg for more information

【Manual-Test-log】
When we run job.log's commands by manual, the files "kprobe_example.o" & "kprobe_example.ko" are not found, which makes us not duplicate the issues of job.log.
If necessary, please give us the files so that we can do manual-test for you to check.
[Manual-Test-log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5382170/Manual-Test-log.txt)
[root@sut3 ~]# cd /root/tests/data/cache/by_location/84d0a6769cb0569c52065a2ce18b92c3a18a42da
[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# ls
kprobe_example.c  kprobe_example.c-CHECKSUM
[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# make
make: *** No targets specified and no makefile found.  Stop.
[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# updatedb
[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# locate kprobe_example.o
[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# chmod 777 -R *
[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# make
make: *** No targets specified and no makefile found.  Stop.

[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# insmod ./kprobe_example.ko
insmod: ERROR: could not load module ./kprobe_example.ko: No such file or directory
[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# locate kprobe_example.ko
[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# 

[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# ls
kprobe_example.c  kprobe_example.c-CHECKSUM
[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# wget https://raw.githubusercontent.com/torvalds/linux/master/samples/kprobes/kprobe_example.c
--2020-10-15 10:47:59--  https://raw.githubusercontent.com/torvalds/linux/master/samples/kprobes/kprobe_example.c
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3647 (3.6K) [text/plain]
Saving to: 'kprobe_example.c.1'


kprobe_example.c.1                          0%[                                                                                   ]       0  --.-KB/s               
kprobe_example.c.1                        100%[==================================================================================>]   3.56K  --.-KB/s    in 0s      

2020-10-15 10:48:04 (50.2 MB/s) - 'kprobe_example.c.1' saved [3647/3647]

[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# ls
kprobe_example.c  kprobe_example.c-CHECKSUM  kprobe_example.c.1
[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# make
make: *** No targets specified and no makefile found.  Stop.
[root@sut3 84d0a6769cb0569c52065a2ce18b92c3a18a42da]# 

【Configuration】
[Kernel]
4.18.0-193.14.3.el8_2.ppc64le

[FW Config]
BMC: op940.00.mih-5-0-g86f9791c2
Pnor: OP9-v2.4-4.37-prod

[HW Config]
CPU DD2.3 20 core *2
SK Hynix(HMA82GR7CJR4N-VK)16GiB x16
Seagate Jaguar 400GB *2
PSU ACBEL 2000w *2
Slot1: Storage1 - Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot3: Network6 - Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot4: Network10 - Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot5: Storage3 - Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
00VN497; HDD; 2400GB; 2.5"; 10k; SAS; 12Gb/s; 4Kn/512e; Non-SED *24

**Comment by Gene-Lo** [comment]
Tag ssant@in.ibm.com
Sachin, please kindly track issue.
