### ISSUE TITLE
[nvme] lvsetup.py: getting avocado crashed after test

### ISSUE THREAD

**Issue by smruti77** [avocado-framework-tests/avocado-misc-tests#1768]
```2020-06-10 06:32:32,693 process          L0607 INFO | Running 'lvcreate --name avocado_lv --size 100G avocado_vg -y'
2020-06-10 06:32:32,743 process          L0439 DEBUG| [stderr]   Volume group "avocado_vg" has insufficient free space (7153 extents): 25600 required.
2020-06-10 06:32:32,832 process          L0689 INFO | Command 'lvcreate --name avocado_lv --size 100G avocado_vg -y' finished with 5 after 0.13526105880737305s
2020-06-10 06:32:32,833 lv_utils         L0456 ERROR| Command 'lvcreate --name avocado_lv --size 100G avocado_vg -y' failed.
stdout: b''
stderr: b'  Volume group "avocado_vg" has insufficient free space (7153 extents): 25600 required.\n'
additional_info: None
2020-06-10 06:32:32,833 stacktrace       L0039 ERROR| 
2020-06-10 06:32:32,834 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py:779
2020-06-10 06:32:32,835 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-06-10 06:32:32,835 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/utils/lv_utils.py", line 454, in lv_create
2020-06-10 06:32:32,836 stacktrace       L0045 ERROR|     process.run(lv_cmd, sudo=True)
2020-06-10 06:32:32,836 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/utils/process.py", line 1040, in run
2020-06-10 06:32:32,836 stacktrace       L0045 ERROR|     raise CmdError(cmd, sp.result)
2020-06-10 06:32:32,836 stacktrace       L0045 ERROR| avocado.utils.process.CmdError: Command 'lvcreate --name avocado_lv --size 100G avocado_vg -y' failed.
2020-06-10 06:32:32,836 stacktrace       L0045 ERROR| stdout: b''
2020-06-10 06:32:32,836 stacktrace       L0045 ERROR| stderr: b'  Volume group "avocado_vg" has insufficient free space (7153 extents): 25600 required.\n'
2020-06-10 06:32:32,836 stacktrace       L0045 ERROR| additional_info: None
2020-06-10 06:32:32,836 stacktrace       L0045 ERROR| 
2020-06-10 06:32:32,836 stacktrace       L0045 ERROR| During handling of the above exception, another exception occurred:
2020-06-10 06:32:32,837 stacktrace       L0045 ERROR| 
2020-06-10 06:32:32,837 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-06-10 06:32:32,837 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/decorators.py", line 51, in wrapper
2020-06-10 06:32:32,837 stacktrace       L0045 ERROR|     return func(*args, **kwargs)
2020-06-10 06:32:32,837 stacktrace       L0045 ERROR|   File "/root/avocado/avocado-misc-tests/io/disk/lvsetup.py", line 118, in create_lv
2020-06-10 06:32:32,837 stacktrace       L0045 ERROR|     lv_utils.lv_create(self.vg_name, self.lv_name, self.lv_size)
2020-06-10 06:32:32,837 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/utils/lv_utils.py", line 457, in lv_create
2020-06-10 06:32:32,837 stacktrace       L0045 ERROR|     raise LVException("Create thin volume failed.")
2020-06-10 06:32:32,837 stacktrace       L0045 ERROR| avocado.utils.lv_utils.LVException: Create thin volume failed.
2020-06-10 06:32:32,838 stacktrace       L0045 ERROR| 
2020-06-10 06:32:32,838 stacktrace       L0045 ERROR| The above exception was the direct cause of the following exception:
2020-06-10 06:32:32,838 stacktrace       L0045 ERROR| 
2020-06-10 06:32:32,838 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-06-10 06:32:32,838 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/decorators.py", line 53, in wrapper
2020-06-10 06:32:32,838 stacktrace       L0045 ERROR|     raise exc
2020-06-10 06:32:32,838 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/decorators.py", line 51, in wrapper
2020-06-10 06:32:32,838 stacktrace       L0045 ERROR|     return func(*args, **kwargs)
2020-06-10 06:32:32,838 stacktrace       L0045 ERROR|   File "/root/avocado/avocado-misc-tests/io/disk/lvsetup.py", line 149, in test
2020-06-10 06:32:32,839 stacktrace       L0045 ERROR|     self.create_lv()
2020-06-10 06:32:32,839 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/decorators.py", line 55, in wrapper
2020-06-10 06:32:32,839 stacktrace       L0045 ERROR|     raise signal(repr(details)) from details
2020-06-10 06:32:32,839 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: LVException('Create thin volume failed.',)
2020-06-10 06:32:32,839 stacktrace       L0046 ERROR| 
2020-06-10 06:32:32,839 test             L0784 DEBUG| Local variables:
2020-06-10 06:32:32,899 test             L0787 DEBUG|  -> kwargs <class 'dict'>: {}
2020-06-10 06:32:32,899 test             L0787 DEBUG|  -> args <class 'tuple'>: (Test('01-lvsetup.py:Lvsetup.test;ext2-4b18'),)
2020-06-10 06:32:32,899 test             L0787 DEBUG|  -> signal <class 'type'>: <class 'avocado.core.exceptions.TestFail'>
2020-06-10 06:32:32,899 test             L0787 DEBUG|  -> func <class 'function'>: <function Lvsetup.test at 0x7fff92928f28>
2020-06-10 06:32:32,899 test             L0787 DEBUG|  -> exceptions <class 'type'>: <class 'avocado.utils.lv_utils.LVException'>
2020-06-10 06:32:32,900 test             L0218 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2020-06-10 06:32:32,900 test             L0218 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2020-06-10 06:32:32,900 test             L0218 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2020-06-10 06:32:32,901 test             L0946 ERROR| FAIL 01-lvsetup.py:Lvsetup.test;ext2-4b18 -> TestFail: LVException('Create thin volume failed.',)
```
```
Avocado crashed unexpectedly: [Errno 16] Device or resource busy: 'avocado_vg'
```

**Comment by smruti77** [comment]
@narasimhan-v  @Naresh-ibm

**Comment by narasimhan-v** [comment]
@smruti77 can you please share :
1. yaml
2. job.log fully
3. lsblk output

**Comment by smruti77** [comment]
[lvsetup.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4763587/lvsetup.log)
```
yaml :
# btrfs needs minimum LV size of 641M
lv_disks: /dev/nvme0n1
lv_size: "100G"
filesystem: !mux
    ext2:
        fs: ext2
    ext3:
        fs: ext3
    ext4:
        fs: ext4
    xfs:
        fs: xfs
    btrfs:
        fs: btrfs
```
```
NAME                           MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sda                              8:0    0  100G  0 disk  
├─sda1                           8:1    0    7M  0 part  
├─sda2                           8:2    0  2.8G  0 part  
└─sda3                           8:3    0 97.2G  0 part  
  ├─rhel_ltc--zzci--3-root     253:12   0 95.3G  0 lvm   
  └─rhel_ltc--zzci--3-swap     253:13   0  1.9G  0 lvm   
sdb                              8:16   0   40G  0 disk  
└─mpatha                       253:4    0   40G  0 mpath 
  ├─mpatha1                    253:6    0    4M  0 part  
  ├─mpatha2                    253:7    0    1G  0 part  /boot
  └─mpatha3                    253:10   0   39G  0 part  
    ├─rhel_ltc--zzci--300-root 253:9    0   35G  0 lvm   /
    └─rhel_ltc--zzci--300-swap 253:11   0    4G  0 lvm   [SWAP]
sdc                              8:32   0   40G  0 disk  
└─mpathb                       253:3    0   40G  0 mpath 
sdd                              8:48   0   40G  0 disk  
└─mpathc                       253:2    0   40G  0 mpath 
sde                              8:64   0   50G  0 disk  
└─mpathd                       253:0    0   50G  0 mpath 
  └─mpathd1                    253:1    0   50G  0 part  
sdf                              8:80   0   50G  0 disk  
└─mpathe                       253:5    0   50G  0 mpath 
sdg                              8:96   0   50G  0 disk  
└─mpathf                       253:8    0   50G  0 mpath 
sdh                              8:112  0   40G  0 disk  
└─mpatha                       253:4    0   40G  0 mpath 
  ├─mpatha1                    253:6    0    4M  0 part  
  ├─mpatha2                    253:7    0    1G  0 part  /boot
  └─mpatha3                    253:10   0   39G  0 part  
    ├─rhel_ltc--zzci--300-root 253:9    0   35G  0 lvm   /
    └─rhel_ltc--zzci--300-swap 253:11   0    4G  0 lvm   [SWAP]
sdi                              8:128  0   40G  0 disk  
└─mpathb                       253:3    0   40G  0 mpath 
sdj                              8:144  0   40G  0 disk  
└─mpathc                       253:2    0   40G  0 mpath 
sdk                              8:160  0   50G  0 disk  
└─mpathd                       253:0    0   50G  0 mpath 
  └─mpathd1                    253:1    0   50G  0 part  
sdl                              8:176  0   50G  0 disk  
└─mpathe                       253:5    0   50G  0 mpath 
sdm                              8:192  0   50G  0 disk  
└─mpathf                       253:8    0   50G  0 mpath 
sdn                              8:208  0   40G  0 disk  
└─mpatha                       253:4    0   40G  0 mpath 
  ├─mpatha1                    253:6    0    4M  0 part  
  ├─mpatha2                    253:7    0    1G  0 part  /boot
  └─mpatha3                    253:10   0   39G  0 part  
    ├─rhel_ltc--zzci--300-root 253:9    0   35G  0 lvm   /
    └─rhel_ltc--zzci--300-swap 253:11   0    4G  0 lvm   [SWAP]
sdo                              8:224  0   40G  0 disk  
└─mpathb                       253:3    0   40G  0 mpath 
sdp                              8:240  0   40G  0 disk  
└─mpathc                       253:2    0   40G  0 mpath 
sr0                             11:0    1 1024M  0 rom   
sdq                             65:0    0   40G  0 disk  
└─mpatha                       253:4    0   40G  0 mpath 
  ├─mpatha1                    253:6    0    4M  0 part  
  ├─mpatha2                    253:7    0    1G  0 part  /boot
  └─mpatha3                    253:10   0   39G  0 part  
    ├─rhel_ltc--zzci--300-root 253:9    0   35G  0 lvm   /
    └─rhel_ltc--zzci--300-swap 253:11   0    4G  0 lvm   [SWAP]
sdr                             65:16   0   40G  0 disk  
└─mpathb                       253:3    0   40G  0 mpath 
sds                             65:32   0   40G  0 disk  
└─mpathc                       253:2    0   40G  0 mpath 
sdt                             65:48   0   50G  0 disk  
└─mpathd                       253:0    0   50G  0 mpath 
  └─mpathd1                    253:1    0   50G  0 part  
sdu                             65:64   0   50G  0 disk  
└─mpathe                       253:5    0   50G  0 mpath 
sdv                             65:80   0   50G  0 disk  
└─mpathf                       253:8    0   50G  0 mpath 
sdw                             65:96   0   50G  0 disk  
└─mpathd                       253:0    0   50G  0 mpath 
  └─mpathd1                    253:1    0   50G  0 part  
sdx                             65:112  0   50G  0 disk  
└─mpathe                       253:5    0   50G  0 mpath 
sdy                             65:128  0   50G  0 disk  
└─mpathf                       253:8    0   50G  0 mpath 
nvme0n1                        259:0    0   28G  0 disk  
nvme0n2                        259:1    0   28G  0 disk  
nvme0n3                        259:2    0   28G  0 disk  
nvme0n4                        259:3    0   28G  0 disk  
nvme0n5                        259:4    0   28G  0 disk  
nvme0n6                        259:5    0   28G  0 disk  
nvme0n7                        259:6    0   28G  0 disk  
nvme0n8                        259:7    0   28G  0 disk  
nvme0n9                        259:8    0   28G  0 disk  
nvme0n10                       259:9    0   28G  0 disk  
nvme0n11                       259:10   0   28G  0 disk  
nvme0n12                       259:11   0   28G  0 disk  
nvme0n13                       259:12   0   28G  0 disk  
nvme0n14                       259:13   0   28G  0 disk  
nvme0n15                       259:14   0   28G  0 disk  
nvme0n16                       259:15   0   28G  0 disk  
nvme0n17                       259:16   0   28G  0 disk  
nvme0n18                       259:17   0   28G  0 disk  
nvme0n19                       259:18   0   28G  0 disk  
nvme0n20                       259:19   0   28G  0 disk  
nvme0n21                       259:20   0   28G  0 disk  
nvme0n22                       259:21   0   28G  0 disk  
nvme0n23                       259:22   0   28G  0 disk  
nvme0n24                       259:23   0   28G  0 disk  
nvme0n25                       259:24   0   28G  0 disk  
nvme0n26                       259:25   0   28G  0 disk  
nvme0n27                       259:26   0   28G  0 disk  
nvme0n28                       259:27   0   28G  0 disk  
nvme0n29                       259:28   0   28G  0 disk  
nvme0n30                       259:29   0   28G  0 disk  
nvme0n31                       259:30   0   28G  0 disk  
nvme0n32                       259:31   0   28G  0 disk  
```

**Comment by narasimhan-v** [comment]
@smruti77 That is the issue there. You are running tests which creates 100G LV on 28G disk. remove lv_size param from yaml and run please

**Comment by smruti77** [comment]
@narasimhan-v ohh, sorry. yesterday i forget to run after i saw this. and created issue.

**Comment by smruti77** [comment]
@narasimhan-v test is working fine but getting avocado crash.

**Comment by smruti77** [comment]
```
JOB ID     : dfd340230bd4a6c373d9f377b44b0c844746f3d2
JOB LOG    : /root/avocado/job-results/job-2020-06-11T04.47-dfd3402/job.log
 (01/25) lvsetup.py:Lvsetup.test;ext2-1a7b: PASS (4.00 s)
 (02/25) lvsetup.py:Lvsetup.test_vg_recreate;ext2-1a7b: PASS (44.97 s)
 (03/25) lvsetup.py:Lvsetup.test_lv_snapshot;ext2-1a7b: PASS (7.91 s)
 (04/25) lvsetup.py:Lvsetup.test_create_lv;ext2-1a7b: PASS (2.51 s)
 (05/25) lvsetup.py:Lvsetup.test_delete_lv;ext2-1a7b: PASS (2.30 s)
 (06/25) lvsetup.py:Lvsetup.test;ext3-ca44: PASS (3.93 s)
 (07/25) lvsetup.py:Lvsetup.test_vg_recreate;ext3-ca44: PASS (44.89 s)
 (08/25) lvsetup.py:Lvsetup.test_lv_snapshot;ext3-ca44: PASS (7.40 s)
 (09/25) lvsetup.py:Lvsetup.test_create_lv;ext3-ca44: PASS (2.30 s)
 (10/25) lvsetup.py:Lvsetup.test_delete_lv;ext3-ca44: PASS (1.92 s)
 (11/25) lvsetup.py:Lvsetup.test;ext4-50f2: PASS (3.44 s)
 (12/25) lvsetup.py:Lvsetup.test_vg_recreate;ext4-50f2: PASS (44.31 s)
 (13/25) lvsetup.py:Lvsetup.test_lv_snapshot;ext4-50f2: PASS (7.03 s)
 (14/25) lvsetup.py:Lvsetup.test_create_lv;ext4-50f2: PASS (2.42 s)
 (15/25) lvsetup.py:Lvsetup.test_delete_lv;ext4-50f2: PASS (2.01 s)
 (16/25) lvsetup.py:Lvsetup.test;xfs-1c8e: PASS (3.96 s)
 (17/25) lvsetup.py:Lvsetup.test_vg_recreate;xfs-1c8e: PASS (45.21 s)
 (18/25) lvsetup.py:Lvsetup.test_lv_snapshot;xfs-1c8e: PASS (7.65 s)
 (19/25) lvsetup.py:Lvsetup.test_create_lv;xfs-1c8e: PASS (2.98 s)
 (20/25) lvsetup.py:Lvsetup.test_delete_lv;xfs-1c8e: PASS (2.79 s)
 (21/25) lvsetup.py:Lvsetup.test;btrfs-b48d: CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.01 s)
 (22/25) lvsetup.py:Lvsetup.test_vg_recreate;btrfs-b48d: CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.01 s)
 (23/25) lvsetup.py:Lvsetup.test_lv_snapshot;btrfs-b48d: CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.01 s)
 (24/25) lvsetup.py:Lvsetup.test_create_lv;btrfs-b48d: CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.01 s)
 (25/25) lvsetup.py:Lvsetup.test_delete_lv;btrfs-b48d: CANCEL: btrfs is not supported with RHEL 7.4 onwards (0.01 s)
RESULTS    : PASS 20 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 5
JOB HTML   : /root/avocado/job-results/job-2020-06-11T04.47-dfd3402/results.html
JOB TIME   : 245.14 s
Avocado crashed unexpectedly: [Errno 16] Device or resource busy: 'avocado_vg'
You can find details in /var/lib/avocado/data/crashes/avocado-traceback-2020-06-11_04:51:18-q4j5j_la.log
```

**Comment by narasimhan-v** [comment]
@smruti77 you need to run it with `--execution-order tests-per-variant`

**Comment by smruti77** [comment]
> @smruti77 you need to run it with `--execution-order tests-per-variant`

i run like that only.

**Comment by narasimhan-v** [comment]
And test_create_lv will give this issue, and this is expected. Crashes because lv is created, and avocado is not able to delete that.

It is expected.

**Comment by smruti77** [comment]
ok than.
