### ISSUE TITLE
bonding.py: bonding test fails with error Control socket connect(/root/.ssh/avocado-master-root@111.1.1.224:22):

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1785]
```
 Command 'route -n | grep enP18p80s0f0 | grep -w UG | awk '{ print $2 }'' finished with 0 after 0.0034809112548828125s
 Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 111.1.1.224 '''
 [stderr] Control socket connect(/root/.ssh/avocado-master-root@111.1.1.224:22): No such file or directory
 Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 111.1.1.224 ''' finished with 255 after 0.004424095153808594s

 Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py:768
 Traceback (most recent call last):
   File "/root/abdul/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/bonding.py", line 125, in setUp
     password=self.password)
   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/utils/network/hosts.py", line 105, in __init__
     self.remote_session = self._connect()
   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/utils/network/hosts.py", line 117, in _connect
     raise NWException(msg)
 avocado.utils.network.exceptions.NWException: Failed connecting 111.1.1.224:22

 ERROR 1-bonding.py:Bonding.test_setup;run-a69b -> TestSetupFail: Failed connecting 111.1.1.224:22
```

**Comment by abdhaleegit** [comment]
@smruti77 to track this for bonding

**Comment by abdhaleegit** [comment]
other test logs which uses same utility (ex network_test.py)

```
Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 111.1.1.224 '''
[stderr] Control socket connect(/root/.ssh/avocado-master-root@111.1.1.224:22): No such file or directory
Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 111.1.1.224 ''' finished with 255 after 0.004163503646850586s
Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 111.1.1.224 '''
[stderr] Master running (pid=4675)
Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -O check 111.1.1.224 ''' finished with 0 after 0.004489898681640625s
Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -p 22 -q 111.1.1.224 'ls /sys/class/net''
[stdout] enP34p1s0f0
[stdout] enP34p1s0f1
```

**Comment by abdhaleegit** [comment]
I see tcpdump and any other test is creating control files fine
 it is failing exactly at this step
`self.remotehost = RemoteHost(self.peer_first_ipinterface, self.user,
                                     password=self.password)`


if it is a network issue.. it should pass at least one time for bonding ... or fail once for other test... both are not happening

as this is only failing for bonding.. I want to rule out if it is bonding test spepci issue.. so we can focus on main issue

**Comment by abdhaleegit** [comment]
this https://github.com/avocado-framework-tests/avocado-misc-tests/pull/1786  fixes the issue
