### ISSUE TITLE
netperf : test failing after network utils changes (netserver not starting at peer)

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1798]
04:42:37 DEBUG| [stdout] make[2]: Nothing to be done for 'all-am'.
04:42:37 DEBUG| [stdout] make[2]: Leaving directory '/var/tmp/avocado_4_bwyzg9/netperf/netperf-netperf-2.7.0'
04:42:37 DEBUG| [stdout] make[1]: Leaving directory '/var/tmp/avocado_4_bwyzg9/netperf/netperf-netperf-2.7.0'
04:42:37 INFO | Command 'make' finished with 0 after 7.294034719467163s
04:42:37 DEBUG| PARAMS (key=EXPECTED_THROUGHPUT, path=*, default=90) => 80
04:42:37 DEBUG| PARAMS (key=duration, path=*, default=300) => 600
04:42:37 DEBUG| PARAMS (key=minimum_iterations, path=*, default=1) => 1
04:42:37 DEBUG| PARAMS (key=maximum_iterations, path=*, default=15) => 5
04:42:37 DEBUG| PARAMS (key=option, path=*, default=) => ''
04:42:37 INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -q 103.10.10.193 'chmod 777 /tmp/netperf-netperf-2.7.0/src''
04:42:37 INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -q 103.10.10.193 'chmod 777 /tmp/netperf-netperf-2.7.0/src'' finished with 0 after 0.020669221878051758s
04:42:37 INFO | Running '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -q 103.10.10.193 '/tmp/netperf-netperf-2.7.0/src/netserver''
04:42:37 DEBUG| [stdout] Starting netserver with host 'IN(6)ADDR_ANY' port '12865' and family AF_UNSPEC
04:42:37 INFO | Command '/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -q 103.10.10.193 '/tmp/netperf-netperf-2.7.0/src/netserver'' finished with 0 after 0.019900798797607422s
04:42:37 INFO | Running 'timeout 300 /var/tmp/avocado_4_bwyzg9/netperf/netperf-netperf-2.7.0/src/netperf -H 103.10.10.193 -l 600 -i 5,1'
04:47:37 INFO | Command 'timeout 300 /var/tmp/avocado_4_bwyzg9/netperf/netperf-netperf-2.7.0/src/netperf -H 103.10.10.193 -l 600 -i 5,1' finished with 124 after 300.01433658599854s
04:47:37 ERROR|
04:47:37 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py:778
04:47:37 ERROR| Traceback (most recent call last):
04:47:37 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/netperf_test.py", line 153, in test
04:47:37 ERROR|     self.fail("FAIL: Run failed")
04:47:37 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py", line 964, in fail
04:47:37 ERROR|     raise exceptions.TestFail(message)
04:47:37 ERROR| avocado.core.exceptions.TestFail: FAIL: Run failed
04:47:37 ERROR|
04:47:37 DEBUG| Local variables:
04:47:37 DEBUG|  -> result <class 'avocado.utils.process.CmdResult'>: command: 'timeout 300 /var/tmp/avocado_4_bwyzg9/netperf/netperf-netperf-2.7.0/src/netperf -H 103.10.10.193 -l 600 -i 5,1'
exit_status: 124
duration: 300.01433658599854
interrupted: False
pid: 31133
encoding: 'UTF-8'
stdout: b''
stderr: b''
04:47:37 DEBUG|  -> speed <class 'int'>: 10000
04:47:37 DEBUG|  -> output <class 'avocado.utils.process.CmdResult'>: command: "/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -q 103.10.10.193 '/tmp/netperf-netperf-2.7.0/src/netserver'"
exit_status: 0
duration: 0.019900798797607422
interrupted: False
pid: 31130
encoding: 'UTF-8'
stdout: b"Starting netserver with host 'IN(6)ADDR_ANY' port '12865' and family AF_UNSPEC\n"

I see these changes recently
`     def test(self):
         """
         netperf test
         """
         if self.netperf_run == '1':
             cmd = "chmod 777 /tmp/%s/src" % self.version
-            output, exitcode = self.run_command(cmd)
-            if exitcode != 0:
+            output = self.session.cmd(cmd)
+            if not output.exit_status == 0:
                 self.fail("test failed because netserver not available")
             cmd = "/tmp/%s/src/netserver" % self.version
-            output, exitcode = self.run_command(cmd)
-            if exitcode != 0:
+            output = self.session.cmd(cmd)
+            if not output.exit_status == 0:
                 self.fail("test failed because netserver not available")
         speed = int(read_file("/sys/class/net/%s/speed" % self.iface))
`

**Comment by abdhaleegit** [comment]
```
c_netperf_test_netperf_test_virt.yaml --force-job-id a2c1c167db74ae2a901a8cc1227442615d1cd977  --job-results-dir /home/ioci/logs/io_vnic/results --execution-order tests-per-variant
/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/plugins/run.py:285: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp.
  FutureWarning)
JOB ID     : a2c1c167db74ae2a901a8cc1227442615d1cd977
JOB LOG    : /home/ioci/logs/io_vnic/results/job-2020-07-01T04.40-a2c1c16/job.log
 (01/10) avocado-misc-tests/io/net/netperf_test.py:Netperf.test;1500-generic-7ef0: FAIL: FAIL: Run failed (401.95 s)
 (02/10) avocado-misc-tests/io/net/netperf_test.py:Netperf.test;9000-generic-4f33: FAIL: FAIL: Run failed (410.22 s)
 (03/10) avocado-misc-tests/io/net/netperf_test.py:Netperf.test;1500-tcp_stream-9d2a: FAIL: FAIL: Throughput Actual - 9.41%, Expected - 80%, Throughput Actual value - 941Mb/sec  (104.84 s)
 (04/10) avocado-misc-tests/io/net/netperf_test.py:Netperf.test;9000-tcp_stream-1da8: FAIL: FAIL: Throughput Actual - 9.89%, Expected - 80%, Throughput Actual value - 989Mb/sec  (120.22 s)
 (05/10) avocado-misc-tests/io/net/netperf_test.py:Netperf.test;1500-udp_stream-e5d2: FAIL: FAIL: Throughput Actual - 0.04%, Expected - 80%, Throughput Actual value - 4Mb/sec  (108.61 s)
 (06/10) avocado-misc-tests/io/net/netperf_test.py:Netperf.test;9000-udp_stream-c31c: FAIL: FAIL: Throughput Actual - 0.04%, Expected - 80%, Throughput Actual value - 4Mb/sec  (123.99 s)
 (07/10) avocado-misc-tests/io/net/netperf_test.py:Netperf.test;1500-tcp_rr-1e3a: \

**Comment by smruti77** [comment]
@abdhaleegit netperf is running fine for me, not a test script issue.
```
JOB ID     : 0f605e85cac0c77959633d46590e7bfbb21edb51
JOB LOG    : /root/avocado/job-results/job-2020-07-14T04.54-0f605e8/job.log
 (1/5) netperf_test.py:Netperf.test;1500-generic-8741: WARN: Test passed but there were warnings during execution. Check the log for details. (700.11 s)
 (2/5) netperf_test.py:Netperf.test;1500-tcp_stream-d395: PASS (102.05 s)
 (3/5) netperf_test.py:Netperf.test;1500-udp_stream-9d26: FAIL: FAIL: Throughput Actual - 46.13%, Expected - 90%, Throughput Actual value - 4613Mb/sec  (102.03 s)
 (4/5) netperf_test.py:Netperf.test;1500-tcp_rr-e237: WARN: Test passed but there were warnings during execution. Check the log for details. (691.96 s)
 (5/5) netperf_test.py:Netperf.test;1500-udp_rr-26c3: WARN: Test passed but there were warnings during execution. Check the log for details. (692.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 3 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2020-07-14T04.54-0f605e8/results.html
JOB TIME   : 2288.40 s
```

**Comment by abdhaleegit** [comment]
config issue, test works fine
