### ISSUE TITLE
vfc : fio fails for no_fs no_lv

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1805]
```
06:40:51 DEBUG| [stdout]       {"name": "/dev/nvme0n2", "maj:min": "259:6", "rm": "0", "size": "228.9G", "ro": "0", "type": "disk", "mountpoint": null}
06:40:51 DEBUG| [stdout]    ]
06:40:51 DEBUG| [stdout] }
06:40:51 INFO | Running 'make'
06:40:51 DEBUG| [stdout] make: Nothing to be done for 'all'.
06:40:51 INFO | Command 'make' finished with 0 after 0.06100797653198242s
06:40:51 INFO | Test will run on /dev/mapper/mpathi
06:40:51 DEBUG| PARAMS (key=fio_job, path=*, default=fio-simple.job) => 'fio-simple.job'
06:40:51 DEBUG| DATA (filename=fio-simple.job) => /home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/fiotest.py.data/fio-simple.job (found at file source dir)
06:40:51 INFO | Running '/var/tmp/avocado_rbztoao1/fio/fio /home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/fiotest.py.data/fio-simple.job /dev/mapper/mpathi --filename=fiotest-image'
06:40:51 DEBUG| [stderr] fio: option <id = "HQjCbe-Uu71-5SjF-FqXz-O5H7-v1zS-rps7Mh"> outside of [] job section
06:40:51 DEBUG| [stdout] file1: (g=0): rw=randrw, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=sync, iodepth=1
06:40:51 INFO | Command '/var/tmp/avocado_rbztoao1/fio/fio /home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/fiotest.py.data/fio-simple.job /dev/mapper/mpathi --filename=fiotest-image' finished with 1 after 0.14960622787475586s
06:40:51 DEBUG| [stdout] file2: (g=1): rw=randrw, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=posixaio, iodepth=4
06:40:51 DEBUG| [stdout] file3: (g=2): rw=randrw, bs=(R) 512MiB-512MiB, (W) 512MiB-512MiB, (T) 512MiB-512MiB, ioengine=mmap, iodepth=1
06:40:51 DEBUG| [stdout] file4: (g=3): rw=randrw, bs=(R) 1024MiB-1024MiB, (W) 1024MiB-1024MiB, (T) 1024MiB-1024MiB, ioengine=splice, iodepth=1
06:40:51 DEBUG| [stdout] seq-write: (g=4): rw=write, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=posixaio, iodepth=4
06:40:51 DEBUG| [stdout] rand-write: (g=5): rw=randwrite, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=splice, iodepth=1
06:40:51 DEBUG| [stdout] seq-readwrite: (g=6): rw=rw, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=mmap, iodepth=1
06:40:51 DEBUG| [stdout] rand-readwrite: (g=7): rw=randrw, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=mmap, iodepth=1
06:40:51 ERROR|
06:40:51 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py:778
06:40:51 ERROR| Traceback (most recent call last):
06:40:51 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/fiotest.py", line 204, in test
06:40:51 ERROR|     self.fail("fio run failed")
06:40:51 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py", line 964, in fail
06:40:51 ERROR|     raise exceptions.TestFail(message)
06:40:51 ERROR| avocado.core.exceptions.TestFail: fio run failed
06:40:51 ERROR|
06:40:51 DEBUG| Local variables:
06:40:51 DEBUG|  -> cmd <class 'str'>: /var/tmp/avocado_rbztoao1/fio/fio /home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/fiotest.py.data/fio-simple.job /dev/mapper/mpathi --filename=fiotest-image
06:40:51 DEBUG|  -> fio_job <class 'str'>: fio-simple.job
06:40:51 DEBUG|  -> self <class 'fiotest.FioTest'>: 8-avocado-misc-tests/io/disk/fiotest.py:FioTest.test;no_fs-no_lv-3010

**Comment by narasimhan-v** [comment]
@abdhaleegit This is a generic issue, though I have not seen this consistently.

There is already an issue open #1738 . Please check if see if they can be tracked via one issue.
