### ISSUE TITLE
vfc: multipath.py IndexError: list index out of range

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1806]
```
09:22:43 INFO | Running 'multipath -ll'
09:22:43 DEBUG| [stdout] mpathk (360050768028211d8b0000000000000de) dm-3 IBM,2145
09:22:43 INFO | Command 'multipath -ll' finished with 0 after 0.04676103591918945s
09:22:43 DEBUG| [stdout] size=50G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
09:22:43 DEBUG| [stdout] |-+- policy='service-time 0' prio=50 status=active
09:22:43 DEBUG| [stdout] | `- 1:0:1:3 sdp       8:240 active ready running
09:22:43 DEBUG| [stdout] `-+- policy='service-time 0' prio=10 status=enabled
09:22:43 DEBUG| [stdout]   `- 1:0:0:3 sdl       8:176 active ready running
09:22:43 DEBUG| [stdout] mpathj (360050768028211d8b0000000000000dd) dm-2 IBM,2145
09:22:43 DEBUG| [stdout] size=50G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
09:22:43 DEBUG| [stdout] |-+- policy='service-time 0' prio=50 status=active
09:22:43 DEBUG| [stdout] | `- 1:0:0:2 sdk       8:160 active ready running
09:22:43 DEBUG| [stdout] `-+- policy='service-time 0' prio=10 status=enabled
09:22:43 DEBUG| [stdout]   `- 1:0:1:2 sdo       8:224 active ready running
09:22:43 DEBUG| [stdout] mpathi (360050768028211d8b0000000000000dc) dm-1 IBM,2145
09:22:43 DEBUG| [stdout] size=50G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
09:22:43 DEBUG| [stdout] |-+- policy='service-time 0' prio=50 status=active
09:22:43 DEBUG| [stdout] | `- 1:0:1:1 sdn       8:208 active ready running
09:22:43 DEBUG| [stdout] `-+- policy='service-time 0' prio=10 status=enabled
09:22:43 DEBUG| [stdout]   `- 1:0:0:1 sdj       8:144 active ready running
09:22:43 DEBUG| [stdout] mpathh (360050768028211d8b0000000000000df) dm-0 IBM,2145
09:22:43 DEBUG| [stdout] size=50G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
09:22:43 DEBUG| [stdout] |-+- policy='service-time 0' prio=50 status=active
09:22:43 DEBUG| [stdout] | `- 1:0:1:0 sdm       8:192 active ready running
09:22:43 DEBUG| [stdout] `-+- policy='service-time 0' prio=10 status=enabled
09:22:43 DEBUG| [stdout]   `- 1:0:0:0 sdi       8:128 active ready running
09:22:43 DEBUG| [stdout] eui.335256304a3001760025384100000001 [nvme]:nvme0n1 NVMe,MZPLL1T6HEHP,MN14MN14
09:22:43 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
09:22:43 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
09:22:43 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live   
09:22:43 DEBUG| [stdout] eui.335256304a3001760025384100000002 [nvme]:nvme0n2 NVMe,MZPLL1T6HEHP,MN14MN14
09:22:43 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
09:22:43 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
09:22:43 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live   
09:22:43 INFO | Running 'multipath -l 360050768028211d8b0000000000000de'
09:22:43 DEBUG| [stdout] mpathk (360050768028211d8b0000000000000de) dm-3 IBM,2145
09:22:43 INFO | Command 'multipath -l 360050768028211d8b0000000000000de' finished with 0 after 0.04245710372924805s
09:22:43 DEBUG| [stdout] size=50G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
09:22:43 DEBUG| [stdout] |-+- policy='service-time 0' prio=0 status=active
09:22:43 DEBUG| [stdout] | `- 1:0:1:3 sdp       8:240 active undef running
09:22:43 DEBUG| [stdout] `-+- policy='service-time 0' prio=0 status=enabled
09:22:43 DEBUG| [stdout]   `- 1:0:0:3 sdl       8:176 active undef running
09:22:43 DEBUG| [stdout] eui.335256304a3001760025384100000001 [nvme]:nvme0n1 NVMe,MZPLL1T6HEHP,MN14MN14
09:22:43 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
09:22:43 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
09:22:43 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live   
09:22:43 DEBUG| [stdout] eui.335256304a3001760025384100000002 [nvme]:nvme0n2 NVMe,MZPLL1T6HEHP,MN14MN14
09:22:43 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
09:22:43 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
09:22:43 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live   
09:22:43 INFO | Running 'multipath -ll'
09:22:43 DEBUG| [stdout] mpathk (360050768028211d8b0000000000000de) dm-3 IBM,2145
09:22:43 INFO | Command 'multipath -ll' finished with 0 after 0.04808664321899414s
09:22:43 DEBUG| [stdout] size=50G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
09:22:43 DEBUG| [stdout] |-+- policy='service-time 0' prio=50 status=active
09:22:43 DEBUG| [stdout] | `- 1:0:1:3 sdp       8:240 active ready running
09:22:43 DEBUG| [stdout] `-+- policy='service-time 0' prio=10 status=enabled
09:22:43 DEBUG| [stdout]   `- 1:0:0:3 sdl       8:176 active ready running
09:22:43 DEBUG| [stdout] mpathj (360050768028211d8b0000000000000dd) dm-2 IBM,2145
09:22:43 DEBUG| [stdout] size=50G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
09:22:43 DEBUG| [stdout] |-+- policy='service-time 0' prio=50 status=active
09:22:43 DEBUG| [stdout] | `- 1:0:0:2 sdk       8:160 active ready running
09:22:43 DEBUG| [stdout] `-+- policy='service-time 0' prio=10 status=enabled
09:22:43 DEBUG| [stdout]   `- 1:0:1:2 sdo       8:224 active ready running
09:22:43 DEBUG| [stdout] mpathi (360050768028211d8b0000000000000dc) dm-1 IBM,2145
09:22:43 DEBUG| [stdout] size=50G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
09:22:43 DEBUG| [stdout] |-+- policy='service-time 0' prio=50 status=active
09:22:43 DEBUG| [stdout] | `- 1:0:1:1 sdn       8:208 active ready running
09:22:43 DEBUG| [stdout] `-+- policy='service-time 0' prio=10 status=enabled
09:22:43 DEBUG| [stdout]   `- 1:0:0:1 sdj       8:144 active ready running
09:22:43 DEBUG| [stdout] mpathh (360050768028211d8b0000000000000df) dm-0 IBM,2145
09:22:43 DEBUG| [stdout] size=50G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
09:22:43 DEBUG| [stdout] |-+- policy='service-time 0' prio=50 status=active
09:22:43 DEBUG| [stdout] | `- 1:0:1:0 sdm       8:192 active ready running
09:22:43 DEBUG| [stdout] `-+- policy='service-time 0' prio=10 status=enabled
09:22:43 DEBUG| [stdout]   `- 1:0:0:0 sdi       8:128 active ready running
09:22:43 DEBUG| [stdout] eui.335256304a3001760025384100000001 [nvme]:nvme0n1 NVMe,MZPLL1T6HEHP,MN14MN14
09:22:43 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
09:22:43 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
09:22:43 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live   
09:22:43 DEBUG| [stdout] eui.335256304a3001760025384100000002 [nvme]:nvme0n2 NVMe,MZPLL1T6HEHP,MN14MN14
09:22:43 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
09:22:43 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
09:22:43 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live   
09:22:43 INFO | Running 'multipath -ll 360050768028211d8b0000000000000de'
09:22:43 DEBUG| [stdout] mpathk (360050768028211d8b0000000000000de) dm-3 IBM,2145
09:22:43 INFO | Command 'multipath -ll 360050768028211d8b0000000000000de' finished with 0 after 0.04511904716491699s
09:22:43 DEBUG| [stdout] size=50G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
09:22:43 DEBUG| [stdout] |-+- policy='service-time 0' prio=50 status=active
09:22:43 DEBUG| [stdout] | `- 1:0:1:3 sdp       8:240 active ready running
09:22:43 DEBUG| [stdout] `-+- policy='service-time 0' prio=10 status=enabled
09:22:43 DEBUG| [stdout]   `- 1:0:0:3 sdl       8:176 active ready running
09:22:43 DEBUG| [stdout] eui.335256304a3001760025384100000001 [nvme]:nvme0n1 NVMe,MZPLL1T6HEHP,MN14MN14
09:22:43 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
09:22:43 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
09:22:43 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live   
09:22:43 DEBUG| [stdout] eui.335256304a3001760025384100000002 [nvme]:nvme0n2 NVMe,MZPLL1T6HEHP,MN14MN14
09:22:43 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
09:22:43 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
09:22:43 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live   
09:22:43 ERROR| 
09:22:43 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py:767
09:22:43 ERROR| Traceback (most recent call last):
09:22:43 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/multipath_test.py", line 105, in setUp
09:22:43 ERROR|     self.mpath_dic["paths"] = multipath.get_paths(wwid)
09:22:43 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/utils/multipath.py", line 166, in get_paths
09:22:43 ERROR|     paths.append(line.split()[-5])
09:22:43 ERROR| IndexError: list index out of range
09:22:43 ERROR| 
09:22:43 DEBUG| Setting ignore_status to True.
09:22:43 DEBUG| Setting sudo to True.
09:22:43 INFO | Running 'systemctl restart multipathd.service'
09:22:44 INFO | Command 'systemctl restart multipathd.service' finished with 0 after 0.6236109733581543s
09:22:44 DEBUG| Setting ignore_status to True.
09:22:44 INFO | Running 'systemctl status multipathd.service'
09:22:44 DEBUG| [stdout] ● multipathd.service - Device-Mapper Multipath Device Controller
09:22:44 INFO | Command 'systemctl status multipathd.service' finished with 0 after 0.008140325546264648s
09:22:44 DEBUG| [stdout]    Loaded: loaded (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
09:22:44 DEBUG| [stdout]    Active: active (running) since Wed 2020-07-01 09:22:44 EDT; 11ms ago
09:22:44 DEBUG| [stdout]   Process: 27933 ExecStartPre=/sbin/multipath -A (code=exited, status=0/SUCCESS)
09:22:44 DEBUG| [stdout]   Process: 27931 ExecStartPre=/sbin/modprobe -a scsi_dh_alua scsi_dh_emc scsi_dh_rdac dm-multipath (code=exited, status=0/SUCCESS)
09:22:44 DEBUG| [stdout]  Main PID: 27935 (multipathd)
09:22:44 DEBUG| [stdout]    Status: "up"

**Comment by Naresh-ibm** [comment]
it is working fine now. please open a new issue if you still see this.

localhost:~/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk # avocado run --max-parallel-tasks=1 multipath_test.py -m multipath_test.py.data/multipath_test.yaml
JOB ID     : 42321cab65c49a4550f7dabde88451d0ac006ab1
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-02-22T10.08-42321ca/job.log
 (01/18) multipath_test.py:MultipathTest.test;run-policy-queue-length-451e: STARTED
 (01/18) multipath_test.py:MultipathTest.test;run-policy-queue-length-451e: PASS (211.43 s)
 (02/18) multipath_test.py:MultipathTest.test;run-policy-service-time-a354: STARTED
 (02/18) multipath_test.py:MultipathTest.test;run-policy-service-time-a354: PASS (211.79 s)
 (03/18) multipath_test.py:MultipathTest.test;run-policy-round-robin-9e7b: STARTED
 (03/18) multipath_test.py:MultipathTest.test;run-policy-round-robin-9e7b: PASS (210.92 s)
 (04/18) multipath_test.py:MultipathTest.test_fail_reinstate_individual_paths;run-policy-queue-length-451e: STARTED
 (04/18) multipath_test.py:MultipathTest.test_fail_reinstate_individual_paths;run-policy-queue-length-451e: PASS (43.32 s)
 (05/18) multipath_test.py:MultipathTest.test_fail_reinstate_individual_paths;run-policy-service-time-a354: STARTED
 (05/18) multipath_test.py:MultipathTest.test_fail_reinstate_individual_paths;run-policy-service-time-a354: PASS (38.51 s)
 (06/18) multipath_test.py:MultipathTest.test_fail_reinstate_individual_paths;run-policy-round-robin-9e7b: STARTED
 (06/18) multipath_test.py:MultipathTest.test_fail_reinstate_individual_paths;run-policy-round-robin-9e7b: PASS (43.34 s)
 (07/18) multipath_test.py:MultipathTest.test_io_run_on_single_path;run-policy-queue-length-451e: STARTED
 (07/18) multipath_test.py:MultipathTest.test_io_run_on_single_path;run-policy-queue-length-451e: PASS (394.46 s)
 (08/18) multipath_test.py:MultipathTest.test_io_run_on_single_path;run-policy-service-time-a354: STARTED
 (08/18) multipath_test.py:MultipathTest.test_io_run_on_single_path;run-policy-service-time-a354: PASS (394.61 s)
 (09/18) multipath_test.py:MultipathTest.test_io_run_on_single_path;run-policy-round-robin-9e7b: STARTED

 (09/18) multipath_test.py:MultipathTest.test_io_run_on_single_path;run-policy-round-robin-9e7b: PASS (394.28 s)
 (10/18) multipath_test.py:MultipathTest.test_suspend_resume_individual_mpath;run-policy-queue-length-451e: STARTED
 (10/18) multipath_test.py:MultipathTest.test_suspend_resume_individual_mpath;run-policy-queue-length-451e: PASS (122.84 s)
 (11/18) multipath_test.py:MultipathTest.test_suspend_resume_individual_mpath;run-policy-service-time-a354: STARTED
 (11/18) multipath_test.py:MultipathTest.test_suspend_resume_individual_mpath;run-policy-service-time-a354: PASS (123.01 s)
 (12/18) multipath_test.py:MultipathTest.test_suspend_resume_individual_mpath;run-policy-round-robin-9e7b: STARTED
 (12/18) multipath_test.py:MultipathTest.test_suspend_resume_individual_mpath;run-policy-round-robin-9e7b: PASS (123.21 s)
 (13/18) multipath_test.py:MultipathTest.test_suspend_resume_all_mpath;run-policy-queue-length-451e: STARTED
 (13/18) multipath_test.py:MultipathTest.test_suspend_resume_all_mpath;run-policy-queue-length-451e: PASS (183.30 s)
 (14/18) multipath_test.py:MultipathTest.test_suspend_resume_all_mpath;run-policy-service-time-a354: STARTED
 (14/18) multipath_test.py:MultipathTest.test_suspend_resume_all_mpath;run-policy-service-time-a354: PASS (183.14 s)
 (15/18) multipath_test.py:MultipathTest.test_suspend_resume_all_mpath;run-policy-round-robin-9e7b: STARTED
 (15/18) multipath_test.py:MultipathTest.test_suspend_resume_all_mpath;run-policy-round-robin-9e7b: PASS (183.06 s)
 (16/18) multipath_test.py:MultipathTest.test_remove_add_mpath;run-policy-queue-length-451e: STARTED
 (16/18) multipath_test.py:MultipathTest.test_remove_add_mpath;run-policy-queue-length-451e: PASS (123.95 s)
 (17/18) multipath_test.py:MultipathTest.test_remove_add_mpath;run-policy-service-time-a354: STARTED
 (17/18) multipath_test.py:MultipathTest.test_remove_add_mpath;run-policy-service-time-a354: PASS (124.00 s)
 (18/18) multipath_test.py:MultipathTest.test_remove_add_mpath;run-policy-round-robin-9e7b: STARTED
 (18/18) multipath_test.py:MultipathTest.test_remove_add_mpath;run-policy-round-robin-9e7b: PASS (123.65 s)
RESULTS    : PASS 18 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2023-02-22T10.08-42321ca/results.html
JOB TIME   : 3257.10 s
localhost:~/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk # 
localhost:~/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk #
