### ISSUE TITLE
softwareraid: level 6 fails with less devices 

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1811]
```
11:44:56 DEBUG| PARAMS (key=disks, path=*, default=) => '/dev/mapper/mpathh /dev/mapper/mpathi /dev/mapper/mpathj /dev/mapper/mpathk'
11:44:56 DEBUG| PARAMS (key=raidname, path=*, default=/dev/md/mdsraid) => '/dev/md/mdsraid'
11:44:56 DEBUG| PARAMS (key=raid, path=*, default=0) => 6
11:44:56 DEBUG| PARAMS (key=metadata, path=*, default=1.2) => 0.9
11:44:56 DEBUG| PARAMS (key=setup, path=*, default=True) => True
11:44:56 DEBUG| PARAMS (key=run_test, path=*, default=False) => True
11:44:56 DEBUG| PARAMS (key=cleanup, path=*, default=True) => True
11:44:56 DEBUG| PARAMS (key=force, path=*, default=False) => True
11:44:56 INFO | Running 'echo 'yes' | mdadm --create --verbose --assume-clean             /dev/md/mdsraid --level=6 --raid-devices=3 /dev/mapper/mpathh /dev/mapper/mpathi /dev/mapper/mpathj --metadata 0.9 --spare-devices=1 /dev/mapper/mpathk  --force'
11:44:56 DEBUG| [stderr] mdadm: at least 4 raid-devices needed for level 6
11:44:56 INFO | Command 'echo 'yes' | mdadm --create --verbose --assume-clean             /dev/md/mdsraid --level=6 --raid-devices=3 /dev/mapper/mpathh /dev/mapper/mpathi /dev/mapper/mpathj --metadata 0.9 --spare-devices=1 /dev/mapper/mpathk  --force' finished with 1 after 0.002210378646850586s
11:44:56 ERROR|
11:44:56 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py:778
11:44:56 ERROR| Traceback (most recent call last):
11:44:56 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/softwareraid.py", line 76, in test_run
11:44:56 ERROR|     self.create_raid()
11:44:56 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/softwareraid.py", line 93, in create_raid
11:44:56 ERROR|     self.check_pass(cmd, "Failed to create a MD device")
11:44:56 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/softwareraid.py", line 145, in check_pass
11:44:56 ERROR|     self.fail(errmsg)
11:44:56 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py", line 964, in fail
11:44:56 ERROR|     raise exceptions.TestFail(message)
11:44:56 ERROR| avocado.core.exceptions.TestFail: Failed to create a MD device

**Comment by narasimhan-v** [comment]
@abdhaleegit what is the issue here ? The test works as expected.

**Comment by narasimhan-v** [comment]
@abdhaleegit Please check readme, where it states 5 disks are needed to run all levels. This is because one of the disk is used as spare.

**Comment by abdhaleegit** [comment]
working when correct devices are input
