### ISSUE TITLE
io/disk/scsi_add_remove.py : TestSetupFail: list index out of range

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1813]
```
2020-07-01 11:51:07,749 process          L0439 DEBUG| [stdout] eui.335256304a3001760025384100000001 [nvme]:nvme0n1 NVMe,MZPLL1T6HEHP,MN14MN14
2020-07-01 11:51:07,749 process          L0439 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
2020-07-01 11:51:07,750 process          L0439 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
2020-07-01 11:51:07,750 process          L0439 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live
2020-07-01 11:51:07,750 process          L0439 DEBUG| [stdout] eui.335256304a3001760025384100000002 [nvme]:nvme0n2 NVMe,MZPLL1T6HEHP,MN14MN14
2020-07-01 11:51:07,750 process          L0439 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
2020-07-01 11:51:07,750 process          L0439 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
2020-07-01 11:51:07,751 process          L0439 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live
2020-07-01 11:51:07,751 process          L0607 INFO | Running 'multipath -ll 360050768028211d8b0000000000000de'
2020-07-01 11:51:07,797 process          L0439 DEBUG| [stdout] mpathk (360050768028211d8b0000000000000de) dm-3 IBM,2145
2020-07-01 11:51:07,797 process          L0689 INFO | Command 'multipath -ll 360050768028211d8b0000000000000de' finished with 0 after 0.04396367073059082s
2020-07-01 11:51:07,797 process          L0439 DEBUG| [stdout] size=50G features='0' hwhandler='1 alua' wp=rw
2020-07-01 11:51:07,798 process          L0439 DEBUG| [stdout] |-+- policy='service-time 0' prio=50 status=active
2020-07-01 11:51:07,798 process          L0439 DEBUG| [stdout] | `- 1:0:1:3 sdp       8:240 active ready running
2020-07-01 11:51:07,798 process          L0439 DEBUG| [stdout] `-+- policy='service-time 0' prio=10 status=enabled
2020-07-01 11:51:07,798 process          L0439 DEBUG| [stdout]   `- 1:0:0:3 sdl       8:176 active ready running
2020-07-01 11:51:07,798 process          L0439 DEBUG| [stdout] eui.335256304a3001760025384100000001 [nvme]:nvme0n1 NVMe,MZPLL1T6HEHP,MN14MN14
2020-07-01 11:51:07,799 process          L0439 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
2020-07-01 11:51:07,799 process          L0439 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
2020-07-01 11:51:07,799 process          L0439 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live
2020-07-01 11:51:07,799 process          L0439 DEBUG| [stdout] eui.335256304a3001760025384100000002 [nvme]:nvme0n2 NVMe,MZPLL1T6HEHP,MN14MN14
2020-07-01 11:51:07,800 process          L0439 DEBUG| [stdout] size=480000000 features='n/a' hwhandler='n/a' wp=rw
2020-07-01 11:51:07,800 process          L0439 DEBUG| [stdout] `-+- policy='n/a' prio=n/a status=n/a
2020-07-01 11:51:07,800 process          L0439 DEBUG| [stdout]   `- 0:0:1   nvme0c0n1 0:0   n/a   n/a   live
2020-07-01 11:51:07,801 stacktrace       L0039 ERROR|
2020-07-01 11:51:07,801 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py:767
2020-07-01 11:51:07,801 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-07-01 11:51:07,802 stacktrace       L0045 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/scsi_add_remove.py", line 55, in setUp
2020-07-01 11:51:07,802 stacktrace       L0045 ERROR|     for path in multipath.get_paths(wwid):
2020-07-01 11:51:07,802 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/utils/multipath.py", line 166, in get_paths
2020-07-01 11:51:07,802 stacktrace       L0045 ERROR|     paths.append(line.split()[-5])
2020-07-01 11:51:07,802 stacktrace       L0045 ERROR| IndexError: list index out of range
2020-07-01 11:51:07,802 stacktrace       L0046 ERROR|
2020-07-01 11:51:07,837 sysinfo          L0115 DEBUG| Not logging /proc/pci (file does not exist)

**Comment by abdhaleegit** [comment]
unsupport config scsiadd/remove on nvme
