### ISSUE TITLE
virtual_bind_unbind.py :  fails for network test with error failed to detect the test disk

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1815]
03:14:38 DEBUG| PARAMS (key=virtual_slot, path=*, default=None) => ''
03:14:38 INFO | Running 'lsslot'
03:14:38 DEBUG| [stdout] # Slot                     Description       Linux Name    Device(s)
03:14:38 INFO | Command 'lsslot' finished with 0 after 0.03484749794006348s
03:14:38 DEBUG| [stdout] U9009.42A.13C6F1W-V3-C0    Virtual I/O Slot  30000000      vty
03:14:38 DEBUG| [stdout] U9009.42A.13C6F1W-V3-C2    Virtual I/O Slot  30000002      l-lan
03:14:38 DEBUG| [stdout] U9009.42A.13C6F1W-V3-C103  Virtual I/O Slot  30000067      v-scsi
03:14:38 DEBUG| PARAMS (key=count, path=*, default=1) => 1
03:14:38 DEBUG| PARAMS (key=peer_ip, path=*, default=None) => ''
03:14:38 DEBUG| PARAMS (key=host_ip, path=*, default=) => ''
03:14:38 DEBUG| PARAMS (key=netmask, path=*, default=) => ''
03:14:38 INFO | Running 'lsscsi'
03:14:38 DEBUG| [stdout] [0:0:1:0]    disk    AIX      VDASD            0001  /dev/sda
03:14:38 INFO | Command 'lsscsi' finished with 0 after 0.0016300678253173828s
03:14:38 DEBUG| [stdout] [0:0:2:0]    disk    AIX      VDASD            0001  /dev/sdb
03:14:38 DEBUG| [stdout] [0:0:3:0]    disk    AIX      VDASD            0001  /dev/sdc
03:14:38 DEBUG| [stdout] [0:0:4:0]    disk    AIX      VDASD            0001  /dev/sdd
03:14:38 DEBUG| [stdout] [0:0:5:0]    disk    AIX      VDASD            0001  /dev/sde
03:14:38 DEBUG| [stdout] [0:0:6:0]    disk    AIX      VDASD            0001  /dev/sdf
03:14:38 ERROR|
03:14:38 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py:775
03:14:38 ERROR| Traceback (most recent call last):
03:14:38 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/common/virtual_bind_unbind.py", line 97, in test
03:14:38 ERROR|     self.cancel("failed to detect the test disk")
03:14:38 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py", line 995, in cancel
03:14:38 ERROR|     raise exceptions.TestCancel(message)
03:14:38 ERROR| avocado.core.exceptions.TestCancel: failed to detect the test disk
03:14:38 ERROR|
03:14:39 DEBUG| Not logging /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor (file does not exist)
03:14:39 DEBUG| Not logging 'dmidecode' (command 'dmidecode' was not found)
03:14:39 DEBUG| Not logging 'brctl show' (command 'brctl' was not found)
03:14:39 DEBUG| Not logging /proc/pci (file does not exist)
03:14:39 INFO | Running 'kill -19 10876'
03:14:39 INFO | Command 'kill -19 10876' finished with 0 after 0.0006277561187744141s
03:14:39 INFO | Running 'kill -9 10876'
03:14:39 INFO | Command 'kill -9 10876' finished with 0 after 0.0006546974182128906s
03:14:39 INFO | Running 'kill -18 10876'

**Comment by abdhaleegit** [comment]
it did not had proper input param
