### ISSUE TITLE
htx_nic_devices fails

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#1866]
```
03:08:38 DEBUG| [stdout] Ping Test 187net193---->OK
03:08:38 DEBUG| [stdout] All networks ping Ok
03:08:38 INFO | Command 'pingum' finished with 0 after 0.028363943099975586s
03:09:08 INFO | Starting the N/W ping test for HTX in Peer
03:09:08 INFO | N/W ping test for HTX passed in both Host & Peer
03:09:08 INFO | Starting the HTX Deamon in Host
03:09:08 INFO | Running '/usr/lpp/htx/etc/scripts/htxd_run'
03:09:08 DEBUG| [stdout] makedumpfile value is found as 31, updating value as 23
03:09:08 DEBUG| [stdout] restarting kdump service...
03:09:08 DEBUG| [stderr] Redirecting to /bin/systemctl restart kdump.service
03:09:08 DEBUG| [stderr] Job for kdump.service failed because the control process exited with error code.
03:09:08 DEBUG| [stderr] See "systemctl status kdump.service" and "journalctl -xe" for details.
03:09:08 DEBUG| [stdout] kdump service is restarted...
03:09:08 DEBUG| [stdout] [Fri Aug 21 03:09:08 EDT 2020]: exported HTX_HOME_DIR=/usr/lpp/htx/
03:09:08 DEBUG| [stdout] [Fri Aug 21 03:09:08 EDT 2020]: exported PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/lpp/htx/bin:/usr/lpp/htx/etc/scripts_stx:/usr/lpp/htx/etc/scripts:/usr/lpp/htx/:/usr/lpp/htx//etc/scripts/:/usr/lpp/htx/:/usr/lpp/htx//etc/scripts:/usr/lpp/htx//etc:/usr/lpp/htx//etc/methods:/usr/lpp/htx//bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/ucb:/usr/bin/X11:/etc:/test/tools:/usr/local/bin:/usr/lpp/htx//test/tools:.
03:09:08 DEBUG| [stdout] [Fri Aug 21 03:09:08 EDT 2020]: 1st HTX message.
03:09:08 DEBUG| [stdout] HTX version installed:
03:09:09 DEBUG| [stdout]                ver - OS, HTX, Firmware and Machine details
03:09:09 DEBUG| [stdout]
03:09:09 DEBUG| [stdout]                            OS: GNU/Linux
03:09:09 DEBUG| [stdout]                    OS Version: Red Hat Enterprise Linux 8.1 (Ootpa)
03:09:09 DEBUG| [stdout]                Kernel Version: 5.9.0-rc1-autotest-g801980f64
03:09:09 DEBUG| [stdout]                   HTX Version: htxrhel8-544-LE.ppc64le
03:09:09 DEBUG| [stdout]                     Host Name: ltc-zz1b-lp1
03:09:09 DEBUG| [stdout]             Machine Serial No: IBM,0613C6F1W
03:09:09 DEBUG| [stdout]            Machine Type/Model: IBM,9009-42A
03:09:09 DEBUG| [stdout]               System FW Level: FW940.01 (VL940_030)
03:09:10 DEBUG| [stdout] [Fri Aug 21 03:09:10 EDT 2020]: exporting HTX_RELEASE=htxrhel8
03:09:10 DEBUG| [stdout] [Fri Aug 21 03:09:10 EDT 2020]: Setting ulimit -s(stack size) to 8MB. return=0
03:09:10 DEBUG| [stdout] [Fri Aug 21 03:09:10 EDT 2020]: Setting ulimit -c(core limit) to 'unlimited'. return=0
03:09:10 DEBUG| [stdout] [Fri Aug 21 03:09:10 EDT 2020]: Setting ulimit -v(virtual memory)  to 'unlimited'. return=0
03:09:10 DEBUG| [stdout] [Fri Aug 21 03:09:10 EDT 2020]: Setting ulimit -n(# open files) to '1024'. return=0
03:09:10 DEBUG| [stdout] [Fri Aug 21 03:09:10 EDT 2020]: HTXD_STARTUP_MODE was 'ON'. Turning it OFF and returning.
03:09:11 DEBUG| [stdout] Starting HTX Daemon...
03:09:11 DEBUG| [stdout] /usr/lpp/htx/bin/htxd > /tmp/htxd/htxd_ouput_log 2>&1
03:09:11 DEBUG| [stdout] HTXD is started
03:09:11 DEBUG| [stderr] iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (Operation not supported): chain INPUT
03:09:11 DEBUG| [stderr] iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (Operation not supported): chain INPUT
03:09:11 DEBUG| [stdout] opening port
03:09:11 DEBUG| [stderr] iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (Operation not supported): chain INPUT
03:09:13 INFO | Command '/usr/lpp/htx/etc/scripts/htxd_run' finished with 0 after 5.349787473678589s
03:09:13 INFO | Starting the HTX Deamon in Peer
03:09:13 INFO | Running the command on peer lpar: /usr/lpp/htx/etc/scripts/htxd_run
03:09:18 INFO | Shutdown active mdt in host
03:09:18 INFO | Running 'htxcmdline -shutdown'
03:09:18 DEBUG| [stdout]
03:09:18 INFO | Command 'htxcmdline -shutdown' finished with 255 after 0.002060413360595703s
03:09:18 DEBUG| [stdout] ######################## Result Starts Here ################################
03:09:18 DEBUG| [stdout] Daemon state is <IDLE>:No MDT is currently running,
03:09:18 DEBUG| [stdout] command option <-shutdown> is not supported at this daemon state
03:09:18 DEBUG| [stdout] ######################### Result Ends Here #################################
03:09:18 INFO | Shutdown active mdt in peer
03:09:18 INFO | Running the command on peer lpar: htxcmdline -shutdown
03:09:18 INFO | Selecting the htx net.mdt file in Host
03:09:18 INFO | Running 'htxcmdline -select -mdt net.mdt'
03:09:29 DEBUG| [stdout]
03:09:29 INFO | Command 'htxcmdline -select -mdt net.mdt' finished with 0 after 10.91749358177185s
03:09:29 DEBUG| [stdout] ######################## Result Starts Here ################################
03:09:29 DEBUG| [stdout] ECG (/usr/lpp/htx/mdt/net.mdt) is selected
03:09:29 DEBUG| [stdout] ######################### Result Ends Here #################################
03:09:29 INFO | Selecting the htx net.mdt file in Peer
03:09:29 INFO | Running the command on peer lpar: htxcmdline -select -mdt net.mdt
03:09:30 ERROR|
03:09:30 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py:767
03:09:30 ERROR| Traceback (most recent call last):
03:09:30 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py", line 243, in test_start
03:09:30 ERROR|     self.run_htx()
03:09:30 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py", line 478, in run_htx
03:09:30 ERROR|     self.select_net_mdt()
03:09:30 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py", line 499, in select_net_mdt
03:09:30 ERROR|     self.run_command(cmd)
03:09:30 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py", line 218, in run_command
03:09:30 ERROR|     raise CommandFailed(command, output, exitcode)
03:09:30 ERROR| htx_nic_devices.CommandFailed: Command 'htxcmdline -select -mdt net.mdt' exited with 255.
03:09:30 ERROR| Output:
03:09:30 ERROR| ['', '######################## Result Starts Here ################################', 'Daemon state is <SHUTTING_DOWN_MDT>:MDT shutdown is in progress,', 'command option <-select> is not supported at this daemon state', '######################### Result Ends Here #################################']
03:09:30 ERROR|
03:09:30 DEBUG| Local variables:
03:09:30 DEBUG|  -> self <class 'htx_nic_devices.HtxNicTest'>: 1-avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_start;run-2dd4
03:09:30 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
03:09:30 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
03:09:30 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
03:09:30 ERROR| Traceback (most recent call last):

03:09:30 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py", line 856, in _run_avocado
    raise test_exception

03:09:30 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/core/test.py", line 762, in _run_avocado
    testMethod()

03:09:30 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py", line 243, in test_start
    self.run_htx()

03:09:30 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py", line 478, in run_htx
    self.select_net_mdt()

03:09:30 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py", line 499, in select_net_mdt
    self.run_command(cmd)

03:09:30 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py", line 218, in run_command
    raise CommandFailed(command, output, exitcode)

03:09:30 ERROR| htx_nic_devices.CommandFailed: Command 'htxcmdline -select -mdt net.mdt' exited with 255.
Output:
['', '######################## Result Starts Here ################################', 'Daemon state is <SHUTTING_DOWN_MDT>:MDT shutdown is in progress,', 'command option <-select> is not supported at this daemon state', '######################### Result Ends Here #################################']

03:09:30 DEBUG| Not logging /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor (file does not exist)
03:09:30 DEBUG| Not logging /proc/pci (file does not exist)
03:09:30 INFO | Running 'kill -19 31744'
03:09:30 INFO | Command 'kill -19 31744' finished with 0 after 0.0006480216979980469s
03:09:30 INFO | Running 'kill -9 31744'

**Comment by smruti77** [comment]
@abdhaleegit system access.

**Comment by abdhaleegit** [comment]
fixed with latest PR from Tasmiya
