### ISSUE TITLE
After run ltrace.py in Rhel8.2 with Avocado(version: 82.0), it shows "ERROR: Command '/bin/git fetch -q -f -u -t git://git.debian.org/git/collab-maint"

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1918]
After run ltrace.py in Rhel8.2 with Avocado(version: 82.0), it shows "ERROR: Command '/bin/git fetch -q -f -u -t git://git.debian.org/git/collab-maint"
![image](https://user-images.githubusercontent.com/63998174/95035264-2311f400-06f7-11eb-94fb-ef908cd89e09.png)

【Test log】
1. job.log
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5324928/job.log)
《INIT 1-ltrace.py》
![image](https://user-images.githubusercontent.com/63998174/95697072-26b1f780-0c70-11eb-8118-43346dd56534.png)

《INIT 2-ltrace.py》
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
L0604 INFO | Running 'yumdownloader --assumeyes --verbose --source ltrace --destdir /var/tmp/avocado_software_managerrkop434v
L0416 DEBUG| [stdout] Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, product-id, repoclosure, repodiff, repograph, repomanage, reposync, subscription-manager, uploadprofil
L0416 DEBUG| [stdout] Updating Subscription Management repositories
L0416 DEBUG| [stdout] Unable to read consumer identit
L0416 DEBUG| [stdout] This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register
L0416 DEBUG| [stdout] DNF version: 4.2.
L0416 DEBUG| [stdout] cachedir: /var/cache/dn
L0416 DEBUG| [stdout] Unknown configuration value: failovermethod=priority in /etc/yum.repos.d/at13.0.repo; Configuration: OptionBinding with id "failovermethod" does not exis
L0416 DEBUG| [stdout] enabling epel-modular-source repositor
L0416 DEBUG| [stdout] enabling epel-source repositor
L0416 DEBUG| [stdout] repo: using cache for: at13.
L0416 DEBUG| [stdout] at13.0: using metadata from Fri 28 Aug 2020 06:15:17 PM CST
L0416 DEBUG| [stdout] repo: using cache for: avocad
L0416 DEBUG| [stdout] avocado: using metadata from Wed 10 Jun 2020 09:27:05 AM CST
L0416 DEBUG| [stdout] repo: using cache for: epel-modula
L0416 DEBUG| [stdout] epel-modular: using metadata from Wed 21 Feb 2018 03:13:38 AM CST
L0416 DEBUG| [stdout] repo: downloading from remote: epel-modular-sourc
L0416 DEBUG| [stdout] Extra Packages for Enterprise Linux Modular 8 - 542  B/s | 8.4 kB     00:15   
L0416 DEBUG| [stdout] epel-modular-source: using metadata from Thu 01 Oct 2020 09:31:22 AM CST
L0416 DEBUG| [stdout] repo: using cache for: epe
L0416 DEBUG| [stdout] epel: using metadata from Sat 03 Oct 2020 10:17:53 AM CST
L0416 DEBUG| [stdout] repo: downloading from remote: epel-sourc
L0416 DEBUG| [stdout] Extra Packages for Enterprise Linux 8 - ppc64le 107 kB/s | 1.7 MB     00:16   
L0416 DEBUG| [stdout] epel-source: using metadata from Sat 03 Oct 2020 10:17:50 AM CST
L0416 DEBUG| [stdout] repo: using cache for: InstallMedia-BaseO
L0416 DEBUG| [stdout] InstallMedia-BaseOS: using metadata from Tue 15 Oct 2019 09:27:42 PM CST
L0416 DEBUG| [stdout] repo: using cache for: InstallMedia-AppStrea
L0416 DEBUG| [stdout] InstallMedia-AppStream: using metadata from Tue 15 Oct 2019 09:27:25 PM CST
L0416 DEBUG| [stdout] Completion plugin: Generating completion cache..
L0416 DEBUG| [stderr] No package ltrace-0.7.91-27.el8.src available
L0416 DEBUG| [stderr] Exiting due to strict setting
L0416 DEBUG| [stdout]   --> Package : ltrace-0.7.91-27.el8.ppc64le Source : ltrace-0.7.91-27.el8.src.rp
L0416 DEBUG| [stderr] Error: No package ltrace-0.7.91-27.el8.src available
L0686 INFO | Command 'yumdownloader --assumeyes --verbose --source ltrace --destdir /var/tmp/avocado_software_managerrkop434v' finished with 1 after 35.34969449043274
L0260 ERROR| Command 'yumdownloader --assumeyes --verbose --source ltrace --destdir /var/tmp/avocado_software_managerrkop434v' failed
elog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, product-id, repoclosure, repodiff, repograph, repomanage, reposync, subscription-manager, uploadprofile\nUpdating Subscription Management repositories.\nUnable to read consumer identity\nThis system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.\nDNF version: 4.2.7\ncachedir: /var/cache/dnf\nUnknown configuration value: failovermethod=priority in /etc/yum.repos.d/at13.0.repo; Configuration: OptionBinding with id "failovermethod" does not exist\nenabling epel-modular-source repository\nenabling epel-source repository\nrepo: using cache for: at13.0\nat13.0: using metadata from Fri 28 Aug 2020 06:15:17 PM CST.\nrepo: using cache for: avocado\navocado: using metadata from Wed 10 Jun 2020 09:27:05 AM CST.\nrepo: using cache for: epel-modular\nepel-modular: using metadata from Wed 21 Feb 2018 03:13:38 AM CST.\nrepo: downloading from remote: epel-modular-source\nExtra Packages for Enterprise Linux Modular 8 - 542  B/s | 8.4 kB     00:15    \nepel-modular-source: using metadata from Thu 01 Oct 2020 09:31:22 AM CST.\nrepo: using cache for: epel\nepel: using metadata from Sat 03 Oct 2020 10:17:53 AM CST.\nrepo: downloading from remote: epel-source\nExtra Packages for Enterprise Linux 8 - ppc64le 107 kB/s | 1.7 MB     00:16    \nepel-source: using metadata from Sat 03 Oct 2020 10:17:50 AM CST.\nrepo: using cache for: InstallMedia-BaseOS\nInstallMedia-BaseOS: using metadata from Tue 15 Oct 2019 09:27:42 PM CST.\nrepo: using cache for: InstallMedia-AppStream\nInstallMedia-AppStream: using metadata from Tue 15 Oct 2019 09:27:25 PM CST.\nCompletion plugin: Generating completion cache...\n  --> Package : ltrace-0.7.91-27.el8.ppc64le Source : ltrace-0.7.91-27.el8.src.rpm\n
.src available.\nExiting due to strict setting.\nError: No package ltrace-0.7.91-27.el8.src available.\n
additional_info: Non
L0039 ERROR|
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:75
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

2. Manual-Test-log
[Manual-Test-log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5324929/Manual-Test-log.txt)

【Configuration】
[Rhel8.2 Kernel]
4.18.0-193.14.3.el8_2.ppc64le

[FW config]
BMC: op940.00.mih-5-0-g86f9791c2
PNOR: OP9-v2.4-4.37-prod

[HW config]
CPU DD2.3 20 core *2
Micron Technology(18ASF2G72PZ-2G9E1)16GiB x16
Samsung PM985 960GB *1
PSU ACBEL 2000w *2
Slot1: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP

**Comment by Gene-Lo** [comment]
After we use different Mihawk system to run ltrace.py in Rhel8.2 with Avocado(version: 82.0), it shows below error:

【SOL log】
 (1/2) ltrace.py:Ltrace.test;run-run_type-upstream-6628: INTERRUPTED: Test interrupted by SIGTERM\nRunner error occurred: Timeout reached\nOriginal status: ERROR\n{'name': '1-ltrace.py:Ltrace.test;run-run_type-upstream-6628', 'logdir': '/root/tests/results/job-2020-10-13T17.21-b1850dc/test-results/1-ltrace.py_Ltrace.test_run-r... (86401.52 s)
 (2/2) ltrace.py:Ltrace.test;run-run_type-distro-8228: ERROR: [Errno 2] No such file or directory: './autogen.sh' (./autogen.sh): './autogen.sh' (125.66 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 1 | CANCEL 0

【job.log】
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5398539/job.log)
《INIT 1-ltrace.py:Ltrace.test》
2020-10-13 17:21:49,587 process          L0416 DEBUG| [stdout] Running ./ltrace.main/filters.exp ...
2020-10-14 17:21:09,646 stacktrace       L0039 ERROR| 
2020-10-14 17:21:09,646 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:767
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/toolchain/ltrace.py", line 95, in test
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|     ret = build.make(self.src_lt, extra_args='check', ignore_status=True)
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/build.py", line 118, in make
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|     result = run_make(path, make, extra_args, kwargs)
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/build.py", line 84, in run_make
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|     make_process = process.run(cmd, **process_kwargs)
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1034, in run
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|     cmd_result = sp.run(timeout=timeout)
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 908, in run
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|     self.wait(timeout, sig)
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 822, in wait
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|     rc = self._popen.wait()
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|   File "/usr/lib64/python3.6/subprocess.py", line 1477, in wait
2020-10-14 17:21:09,648 stacktrace       L0045 ERROR|     (pid, sts) = self._try_wait(0)
2020-10-14 17:21:09,649 stacktrace       L0045 ERROR|   File "/usr/lib64/python3.6/subprocess.py", line 1424, in _try_wait
2020-10-14 17:21:09,649 stacktrace       L0045 ERROR|     (pid, sts) = os.waitpid(self.pid, wait_flags)
2020-10-14 17:21:09,649 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/plugins/runner.py", line 77, in sigterm_handler
2020-10-14 17:21:09,649 stacktrace       L0045 ERROR|     raise RuntimeError("Test interrupted by SIGTERM")
2020-10-14 17:21:09,649 stacktrace       L0045 ERROR| RuntimeError: Test interrupted by SIGTERM

《INIT 2-ltrace.py:Ltrace.test》
2020-10-14 17:23:15,422 process          L0604 INFO | Running './autogen.sh'
2020-10-14 17:23:15,423 stacktrace       L0039 ERROR| 
2020-10-14 17:23:15,423 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:756
2020-10-14 17:23:15,424 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-10-14 17:23:15,424 stacktrace       L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/toolchain/ltrace.py", line 87, in setUp
2020-10-14 17:23:15,424 stacktrace       L0045 ERROR|     process.run('./autogen.sh')
2020-10-14 17:23:15,424 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1034, in run
2020-10-14 17:23:15,424 stacktrace       L0045 ERROR|     cmd_result = sp.run(timeout=timeout)
2020-10-14 17:23:15,424 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 907, in run
2020-10-14 17:23:15,424 stacktrace       L0045 ERROR|     self._init_subprocess()
2020-10-14 17:23:15,424 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 621, in _init_subprocess
2020-10-14 17:23:15,424 stacktrace       L0045 ERROR|     raise details
2020-10-14 17:23:15,425 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 618, in _init_subprocess
2020-10-14 17:23:15,425 stacktrace       L0045 ERROR|     env=self.env)
2020-10-14 17:23:15,425 stacktrace       L0045 ERROR|   File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
2020-10-14 17:23:15,425 stacktrace       L0045 ERROR|     restore_signals, start_new_session)
2020-10-14 17:23:15,425 stacktrace       L0045 ERROR|   File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
2020-10-14 17:23:15,425 stacktrace       L0045 ERROR|     raise child_exception_type(errno_num, err_msg, err_filename)
2020-10-14 17:23:15,425 stacktrace       L0045 ERROR| FileNotFoundError: [Errno 2] No such file or directory: './autogen.sh' (./autogen.sh): './autogen.sh'

【Manual Test】
When we run job.log's commands by manual, it will suspended after run "make check":
[Manual-Test-log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/5398558/Manual-Test-log.txt)

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
[root@sut9 ~]# make check
Making check in sysdeps
make[1]: Entering directory '/root/sysdeps'
Making check in linux-gnu
make[2]: Entering directory '/root/sysdeps/linux-gnu'
Making check in ppc
make[3]: Entering directory '/root/sysdeps/linux-gnu/ppc'
make[3]: Nothing to be done for 'check'.
make[3]: Leaving directory '/root/sysdeps/linux-gnu/ppc'
make[3]: Entering directory '/root/sysdeps/linux-gnu'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/root/sysdeps/linux-gnu'
make[2]: Leaving directory '/root/sysdeps/linux-gnu'
make[2]: Entering directory '/root/sysdeps'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/root/sysdeps'
make[1]: Leaving directory '/root/sysdeps'
Making check in .
make[1]: Entering directory '/root'
make[1]: Nothing to be done for 'check-am'.
make[1]: Leaving directory '/root'
Making check in testsuite
make[1]: Entering directory '/root/testsuite'
make  check-recursive
make[2]: Entering directory '/root/testsuite'
Making check in ltrace.main
make[3]: Entering directory '/root/testsuite/ltrace.main'
make[3]: Nothing to be done for 'check'.
make[3]: Leaving directory '/root/testsuite/ltrace.main'
Making check in ltrace.minor
make[3]: Entering directory '/root/testsuite/ltrace.minor'
make[3]: Nothing to be done for 'check'.
make[3]: Leaving directory '/root/testsuite/ltrace.minor'
Making check in ltrace.torture
make[3]: Entering directory '/root/testsuite/ltrace.torture'
make[3]: Nothing to be done for 'check'.
make[3]: Leaving directory '/root/testsuite/ltrace.torture'
make[3]: Entering directory '/root/testsuite'
make  check-DEJAGNU
make[4]: Entering directory '/root/testsuite'
Making a new site.exp file ...
srcdir='.'; export srcdir; \
EXPECT=expect; export EXPECT; \
if /bin/sh -c "runtest --version" > /dev/null 2>&1; then \
  exit_status=0; l='ltrace'; for tool in $l; do \
    if runtest --srcdir .    ; \
    then :; else exit_status=1; fi; \
  done; \
else echo "WARNING: could not find 'runtest'" 1>&2; :;\
fi; \
exit $exit_status
WARNING: Couldn't find the global config file.
WARNING: No tool specified
Test run by root on Thu Oct 15 09:56:56 2020
Native configuration is powerpc64le-unknown-linux-gnu

===  tests ===

Schedule of variations:
    unix

Running target unix
Using /usr/share/dejagnu/baseboards/unix.exp as board description file for target.
Using /usr/share/dejagnu/config/unix.exp as generic interface file for target.
Using ./config/unix.exp as tool-and-target-specific interface file.
Running ./ltrace.main/XDG_CONFIG_DIRS.exp ...
Running ./ltrace.main/branch_func.exp ...
Running ./ltrace.main/dwarf.exp ...
FAIL: dwarf->treetest({ 1, { 2, nil, nil }, { 3, nil, { 4, nil, nil } } } <unfinished ...> in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: libdwarftest.so->treetest({ 2, nil, nil }) * = nil in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: libdwarftest.so->treetest({ 3, nil, { 4, nil, nil } } <unfinished ...> in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: libdwarftest.so->treetest({ 4, nil, nil }) * = nil in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: <... treetest resumed> ) * = { 5, nil, nil } in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: <... treetest resumed> ) * = { 2, { 3, nil, nil }, { 4, nil, { 5, nil, nil } } } in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: treetest@libdwarftest.so({ 1, { 2, nil, nil }, { 3, nil, { 4, nil, nil } } } <unfinished ...> in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: treetest@libdwarftest.so({ 2, nil, nil }) * = nil in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: treetest@libdwarftest.so({ 3, nil, { 4, nil, nil } } <unfinished ...> in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: treetest@libdwarftest.so({ 4, nil, nil }) * = nil in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: <... treetest resumed> ) * = { 5, nil, nil } in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: <... treetest resumed> ) * = { 2, { 3, nil, nil }, { 4, nil, { 5, nil, nil } } } in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: libdwarftest.so->treetest({ 2, nil, nil }) * = nil in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: libdwarftest.so->treetest({ 3, nil, { 4, nil, nil } } <unfinished ...> in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: libdwarftest.so->treetest({ 4, nil, nil }) * = nil in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: <... treetest resumed> ) * = { 5, nil, nil } in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: dwarf->usleep(33) * = 0 in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: strlen@libc.so.6(.* in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: usleep@libc.so.6(33 <unfinished ...> in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: <... usleep resumed> ) * = 0 in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: ftell@libc.so.6(0x[0-9a-z]*) * = -1 in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
FAIL: ftell@libc.so.6(0x[0-9a-z]*) * = -1 in /root/testsuite/ltrace.main/dwarf.ltrace for 0 times, should be 1
Running ./ltrace.main/filters.exp ...

（Suspended form here）
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

【Configuration】
[Kernel]
4.18.0-193.19.1.el8_2.ppc64le

[FW Config]
BMC: op940.00.mih-5-0-g86f9791c2
Pnor: OP9-v2.4-4.37-prod

[HW Config]
CPU DD2.3 16 core *2
Micron Technology(18ASF2G72PZ-2G9E1)16GiB x32
Samsung PM985 960GB *1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER

**Comment by PraveenPenguin** [comment]
closing this can be an issue even new URL adopted in test cases a did not face any issue @Gene-Lo if you still facing issue please raise new issue
