### ISSUE TITLE
Can't get rmdev_viosfailover test under network_virtualization.py to pass

### ISSUE THREAD

**Issue by cforno12** [avocado-framework-tests/avocado-misc-tests#1965]
I have a vNIC interface with one backing device. When the test removes the associated virtual interface in the VIOS, it fails over to the backing device as expect.

Now, when the test tries to add the virtual devices in the VIOS back, it fails with "Error initializing a device into the kernel."
Here are the logs: 
```
2020-11-25 15:02:54,036 process          L0604 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l hscroot -q 9.3.90.230 'lshwres -r virtualio -m ltczep10 --rsubtype vnic --level lpar                --filter lpar_names=ltczep10-lp3 -F slot_num,backing_device_states''
2020-11-25 15:02:54,075 process          L0416 DEBUG| [stdout] 3,sriov/27008009/1/Operational
2020-11-25 15:02:54,076 process          L0416 DEBUG| [stdout] 6,"sriov/2700802b/1/Operational,sriov/2700802c/0/Operational"
2020-11-25 15:02:54,076 process          L0686 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l hscroot -q 9.3.90.230 'lshwres -r virtualio -m ltczep10 --rsubtype vnic --level lpar                --filter lpar_names=ltczep10-lp3 -F slot_num,backing_device_states'' finished with 0 after 0.03842306137084961s
2020-11-25 15:02:54,077 network_virtuali L0400 DEBUG| Active backing device before : 2700802b
2020-11-25 15:02:54,077 process          L0604 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l padmin -q 9.40.194.228 'echo "rmdev -l vnicserver5" | ioscli oem_setup_env''
2020-11-25 15:02:54,500 process          L0416 DEBUG| [stdout] vnicserver5 Defined
2020-11-25 15:02:54,501 process          L0686 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l padmin -q 9.40.194.228 'echo "rmdev -l vnicserver5" | ioscli oem_setup_env'' finished with 0 after 0.4227631092071533s
2020-11-25 15:02:54,503 process          L0604 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l padmin -q 9.40.194.228 'echo "rmdev -l ent38" | ioscli oem_setup_env''
2020-11-25 15:02:54,664 process          L0416 DEBUG| [stdout] ent38 Defined
2020-11-25 15:02:54,665 process          L0686 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l padmin -q 9.40.194.228 'echo "rmdev -l ent38" | ioscli oem_setup_env'' finished with 0 after 0.16045093536376953s
2020-11-25 15:02:54,666 process          L0604 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l hscroot -q 9.3.90.230 'lshwres -r virtualio -m ltczep10 --rsubtype vnic --level lpar                --filter lpar_names=ltczep10-lp3 -F slot_num,backing_device_states''
2020-11-25 15:02:54,692 process          L0416 DEBUG| [stdout] 3,sriov/27008009/1/Operational
2020-11-25 15:02:54,692 process          L0416 DEBUG| [stdout] 6,"sriov/2700802b/0/Powered Off,sriov/2700802c/1/Operational"
2020-11-25 15:02:54,694 process          L0686 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l hscroot -q 9.3.90.230 'lshwres -r virtualio -m ltczep10 --rsubtype vnic --level lpar                --filter lpar_names=ltczep10-lp3 -F slot_num,backing_device_states'' finished with 0 after 0.025981903076171875s
2020-11-25 15:02:54,694 network_virtuali L0407 DEBUG| Active backing device after: 2700802c
2020-11-25 15:03:14,715 process          L0604 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l padmin -q 9.40.194.228 'echo "mkdev -l ent38" | ioscli oem_setup_env''
2020-11-25 15:03:18,970 process          L0416 DEBUG| [stderr] Method error (/usr/lib/methods/cfglnc2ent):
2020-11-25 15:03:18,970 process          L0416 DEBUG| [stderr] 	0514-040 Error initializing a device into the kernel.
2020-11-25 15:03:18,970 process          L0416 DEBUG| [stderr] 
2020-11-25 15:03:18,971 process          L0686 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l padmin -q 9.40.194.228 'echo "mkdev -l ent38" | ioscli oem_setup_env'' finished with 1 after 4.254676103591919s
2020-11-25 15:03:18,972 stacktrace       L0039 ERROR| 
2020-11-25 15:03:18,972 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-83.0-py3.6.egg/avocado/core/test.py:767
2020-11-25 15:03:18,973 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-11-25 15:03:18,973 stacktrace       L0045 ERROR|   File "/root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/virt-net/network_virtualization.py", line 414, in test_rmdev_viosfailover
2020-11-25 15:03:18,973 stacktrace       L0045 ERROR|     self.validate_vios_command('mkdev -l %s' % vnic_backing_device, 'Available')
2020-11-25 15:03:18,973 stacktrace       L0045 ERROR|   File "/root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/virt-net/network_virtualization.py", line 504, in validate_vios_command
2020-11-25 15:03:18,973 stacktrace       L0045 ERROR|     self.fail("command fail in vios")
2020-11-25 15:03:18,973 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-83.0-py3.6.egg/avocado/core/test.py", line 953, in fail
2020-11-25 15:03:18,973 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-11-25 15:03:18,974 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: command fail in vios
2020-11-25 15:03:18,974 stacktrace       L0046 ERROR| 
2020-11-25 15:03:18,974 test             L0772 DEBUG| Local variables:
2020-11-25 15:03:19,008 test             L0775 DEBUG|  -> after <class 'str'>: 2700802c
2020-11-25 15:03:19,008 test             L0775 DEBUG|  -> before <class 'str'>: 2700802b
2020-11-25 15:03:19,008 test             L0775 DEBUG|  -> line <class 'str'>: 
2020-11-25 15:03:19,008 test             L0775 DEBUG|  -> vnic_backing_device <class 'str'>: ent38
2020-11-25 15:03:19,008 test             L0775 DEBUG|  -> output <class 'avocado.utils.process.CmdResult'>: command: "/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l padmin -q 9.40.194.228 'ioscli lsmap -vnic -vadapter vnicserver5'"
exit_status: 0
duration: 0.09386205673217773
interrupted: False
pid: 132546
encoding: 'UTF-8'
stdout: b'Name          Physloc                            ClntID ClntName       ClntOS \n------------- ---------------------------------- ------ -------------- -------\nvnicserver5   U9040.MR9.132987X-V100-C32902           3 ltczep10-lp3.a Linux\n\nBacking device:ent38\nStatus:Available\nPhysloc:U78D4.ND1.CSS10LJ-P1-C5-T3-S43\nClient device name:env6\nClient device physloc:U9040.MR9.132987X-V3-C6\n\n'
stderr: b''
2020-11-25 15:03:19,009 test             L0775 DEBUG|  -> vnic_server <class 'str'>: vnicserver5
2020-11-25 15:03:19,009 test             L0775 DEBUG|  -> temp_idx <class 'int'>: 17
2020-11-25 15:03:19,009 test             L0775 DEBUG|  -> device <class 'str'>: env6
2020-11-25 15:03:19,009 test             L0775 DEBUG|  -> vnic_servers <class 'list'>: ['Name          Physloc                            ClntID ClntName       ClntOS ', '------------- ---------------------------------- ------ -------------- -------', 'vnicserver2   U9040.MR9.132987X-V100-C32899           3 ltczep10-lp3.a Linux', '', 'Backing device:ent31', 'Status:Available', 'Physloc:U78D4.ND1.CSS10LJ-P1-C5-T1-S9', 'Client device name:env3', 'Client device physloc:U9040.MR9.132987X-V3-C3', '', 'Name          Physloc                            ClntID ClntName       ClntOS ', '------------- ---------------------------------- ------ -------------- -------', 'vnicserver5   U9040.MR9.132987X-V100-C32902           3 ltczep10-lp3.a Linux', '', 'Backing device:ent38', 'Status:Available', 'Physloc:U78D4.ND1.CSS10LJ-P1-C5-T3-S43', 'Client device name:env6', 'Client device physloc:U9040.MR9.132987X-V3-C6', '', 'Name          Physloc                            ClntID ClntName       ClntOS ', '------------- ---------------------------------- ------ -------------- -------', 'vnicserver6   U9040.MR9.132987X-V100-C32903           3 N/A            N/A', '', 'Backing device:ent39', 'Status:Available', 'Physloc:U78D4.ND1.CSS10LJ-P1-C5-T4-S44', 'Client device name:N/A', 'Client device physloc:U9040.MR9.132987X-V3-C6', '']
2020-11-25 15:03:19,009 test             L0775 DEBUG|  -> cmd <class 'str'>: ioscli lsmap -vnic -vadapter vnicserver5
2020-11-25 15:03:19,009 test             L0775 DEBUG|  -> self <class 'network_virtualization.NetworkVirtualization'>: 1-avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_rmdev_viosfailover;run-5e84
2020-11-25 15:03:19,009 process          L0604 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l hscroot -O exit 9.3.90.230 '''
2020-11-25 15:03:19,015 process          L0416 DEBUG| [stderr] Exit request sent.
2020-11-25 15:03:19,015 process          L0686 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l hscroot -O exit 9.3.90.230 ''' finished with 0 after 0.0043182373046875s
2020-11-25 15:03:19,016 process          L0604 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l padmin -O exit 9.40.194.228 '''
2020-11-25 15:03:19,021 process          L0416 DEBUG| [stderr] Exit request sent.
2020-11-25 15:03:19,022 process          L0686 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l padmin -O exit 9.40.194.228 ''' finished with 0 after 0.0039713382720947266s
2020-11-25 15:03:19,023 process          L0604 INFO | Running 'echo 'module ibmvnic -p; func send_subcrq -p' > /sys/kernel/debug/dynamic_debug/control'
2020-11-25 15:03:19,025 process          L0686 INFO | Command 'echo 'module ibmvnic -p; func send_subcrq -p' > /sys/kernel/debug/dynamic_debug/control' finished with 0 after 0.0009462833404541016s
```

My question is, is this possible to re-add an already removed virtual interface on VIOS or is this a known issue that I'm not aware of? Any information would be helpful. Thank you!

**Comment by cforno12** [comment]
Closing this as it was found to be an EEH during mkdev.
