### ISSUE TITLE
bonding:  failed connecting to peer (135.78 s)

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#2032]
bond setup test pass but actual test fails for all bonding device

```
JOB ID     : a42735129c8f27551fc312cd212b0f81d30602c2
JOB LOG    : /home/ioci/avocado-fvt-wrapper/results/job-2021-04-05T09.25-a427351/job.log
 (1/6) bonding.py:Bonding.test_setup;run-Test-active-backup-8ec3: PASS (30.63 s)
 (2/6) bonding.py:Bonding.test_run;run-Test-active-backup-8ec3: CANCEL: failed connecting to peer (135.29 s)
```

logs of a (1/6):
```
09:25:41 INFO | Bond Test on IB Interface? = False
09:25:41 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -O check 206.20.20.179 '''
09:25:41 DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-root@206.20.20.179:22): No such file or directory
09:25:41 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -O check 206.20.20.179 ''' finished with 255 after 0.00483250617980957s
09:25:41 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -O check 206.20.20.179 '''
09:25:41 DEBUG| [stderr] Master running (pid=22102)
09:25:41 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -O check 206.20.20.179 ''' finished with 0 after 0.005085945129394531s
09:25:41 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -q 206.20.20.179 'ip addr show  | grep 206.20.20.179''
09:25:41 DEBUG| [stdout]     inet 206.20.20.179/24 brd 206.20.20.255 scope global noprefixroute vnic2
09:25:41 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -q 206.20.20.179 'ip addr show  | grep 206.20.20.179'' finished with 0 after 0.022355079650878906s
09:25:41 INFO | Running 'route -n | grep eth1 | grep -w UG | awk '{ print $2 }''
09:25:41 INFO | Command 'route -n | grep eth1 | grep -w UG | awk '{ print $2 }'' finished with 0 after 0.003482341766357422s

```
when no control path running , it checks and starts the control master daemon and connects to peer fine

but with (2/6) the control master fails to start

```
09:26:11 INFO | Bond Test on IB Interface? = False
09:26:11 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -O check 206.20.20.179 '''
09:26:11 DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-root@206.20.20.179:22): No such file or directory
09:26:11 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -O check 206.20.20.179 ''' finished with 255 after 0.004651784896850586s
09:28:25 ERROR| 
09:28:25 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-83.0-py3.6.egg/avocado/core/test.py:753
09:28:25 ERROR| Traceback (most recent call last):
09:28:25 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/bonding.py", line 122, in setUp
09:28:25 ERROR|     self.cancel("failed connecting to peer")
09:28:25 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-83.0-py3.6.egg/avocado/core/test.py", line 984, in cancel
09:28:25 ERROR|     raise exceptions.TestCancel(message)
09:28:25 ERROR| avocado.core.exceptions.TestCancel: failed connecting to peer
09:28:25 ERROR| 
09:28:25 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -O exit 206.20.20.179 '''
09:28:25 DEBUG| [stderr] Control socket connect(/root/.ssh/avocado-master-root@206.20.20.179:22): No such file or directory
09:28:25 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l root -O exit 206.20.20.179 ''' finished with 255 after 0.004928112030029297s
```

**Comment by vaishnavibhat** [comment]
I do not see the fix for handling control files that was included in other tests. I will send a patch for bonding.py for handling 
avocado-master-root@xxx.xx.xx.xx:22
