### ISSUE TITLE
net/sriov_device_test.py: fails to connect to HMC

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#2122]
The below test in cfg fails 

avocado-misc-tests/io/net/sriov_device_test.py:NetworkSriovDevice.test_add_migratable_sriov avocado-misc-tests/io/net/sriov_device_test.py.data/migratable_sriov_veth.yaml
```
03:52:09 DEBUG| [stdout] Variable Memory Capacity Weight              : 0
03:52:09 DEBUG| [stdout] Memory Pool ID                               : 65535
03:52:09 DEBUG| [stdout] Unallocated Variable Memory Capacity Weight  : 0
03:52:09 DEBUG| [stdout] Unallocated I/O Memory Entitlement           : 0
03:52:09 DEBUG| [stdout] Memory Group ID of LPAR                      : 32775
03:52:09 DEBUG| [stdout] Desired Variable Capacity Weight             : 0
03:52:09 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l  -O check a.b.cd.xyz '''
03:52:09 DEBUG| [stderr] ssh: Could not resolve hostname check: Name or service not known
03:52:09 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l  -O check a.b.cd.xyz ''' finished with 255 after 0.05068826675415039s
03:52:09 ERROR| 
03:52:09 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-83.0-py3.6.egg/avocado/core/test.py:753
03:52:09 ERROR| Traceback (most recent call last):
03:52:09 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/sriov_device_test.py", line 59, in setUp
03:52:09 ERROR|     self.cancel("failed connetion to HMC")
03:52:09 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-83.0-py3.6.egg/avocado/core/test.py", line 984, in cancel
03:52:09 ERROR|     raise exceptions.TestCancel(message)
03:52:09 ERROR| avocado.core.exceptions.TestCancel: failed connetion to HMC
03:52:09 ERROR| 
03:52:09 INFO | Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l  -O exit a.b.cd.xyz '''
03:52:09 DEBUG| [stderr] ssh: Could not resolve hostname exit: Name or service not known
03:52:09 INFO | Command '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l  -O exit a.b.cd.xyz ''' finished with 255 after 0.047545671463012695s
03:52:09 DEBUG| Not logging /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor (file does not exist)
03:52:09 DEBUG| Not logging /proc/pci (file does not exist)
```

**Comment by abdhaleegit** [comment]
[hmcfaillogs.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7030534/hmcfaillogs.txt)

**Comment by abdhaleegit** [comment]
The problem is when the sriov_add function is called explicitly like 
`avocado-misc-tests/io/net/sriov_device_test.py:NetworkSriovDevice.test_add_migratable_sriov avocado-misc-tests/io/net/sriov_device_test.py.data/migratable_sriov_veth.yaml`

ssh session to the hmc is not established and when it tries to check the connection to hmc ..it fails

Running '/usr/bin/ssh -o 'StrictHostKeyChecking=no' -o 'UpdateHostKeys=no' -o 'ControlPath=~/.ssh/avocado-master-%r@%h:%p' -l  -O check a.b.cd.xyz '''
03:52:09 DEBUG| [stderr] ssh: Could not resolve hostname check: Name or service not known

**Comment by abdhaleegit** [comment]
closing as config issue
