### ISSUE TITLE
ltp_fs.py : lvremove fails to remove logical volume 

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#2125]
```
16:47:56 INFO | Command 'lvdisplay avocado_vg' finished with 0 after 0.106662540s
16:47:56 DEBUG| Provided Logical volume avocado_lv exists in avocado_vg
16:47:56 INFO | Running 'lvremove -f avocado_vg/avocado_lv'
16:47:56 DEBUG| [stderr]   Logical volume avocado_vg/avocado_lv contains a filesystem in use.
16:47:56 INFO | Command 'lvremove -f avocado_vg/avocado_lv' finished with 5 after 0.086634835s
16:47:56 ERROR|
16:47:56 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/core/test.py:820
16:47:56 ERROR| Traceback (most recent call last):
16:47:56 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/ltp_fs.py", line 189, in tearDown
16:47:56 ERROR|     self.delete_lv()
16:47:56 ERROR|   File "/home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/ltp_fs.py", line 129, in delete_lv
16:47:56 ERROR|     lv_utils.lv_remove(vgname, lvname)
16:47:56 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/utils/lv_utils.py", line 479, in lv_remove
16:47:56 ERROR|     process.run(cmd, sudo=True)
16:47:56 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado_framework-90.0-py3.6.egg/avocado/utils/process.py", line 1082, in run
16:47:56 ERROR|     raise CmdError(cmd, sp.result)
16:47:56 ERROR| avocado.utils.process.CmdError: Command 'lvremove -f avocado_vg/avocado_lv' failed.
16:47:56 ERROR| stdout: b''
16:47:56 ERROR| stderr: b'  Logical volume avocado_vg/avocado_lv contains a filesystem in use.\n'
16:47:56 ERROR| additional_info: None
16:47:56 ERROR|
16:47:56 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
16:47:56 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
16:47:56 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
16:47:56 INFO | Running 'kill -19 20126'
16:47:56 INFO | Command 'kill -19 20126' finished with 0 after 0.000736975s
16:47:56 INFO | Running 'kill -9 20126'
```
I see after the test completes the lv is overwritten by dd

16:47:56 INFO | Running 'dd if=/dev/zero bs=512 count=512 of=/dev/avocado_vg/avocado_lv'
16:47:56 DEBUG| [stderr] 512+0 records in
16:47:56 INFO | Command 'dd if=/dev/zero bs=512 count=512 of=/dev/avocado_vg/avocado_lv' finished with 0 after 0.002715078s
16:47:56 DEBUG| [stderr] 512+0 records out
16:47:56 DEBUG| [stderr] 262144 bytes (262 kB, 256 KiB) copied, 0.00122062 s, 215 MB/s
16:47:56 INFO | Running 'vgdisplay avocado_vg'
16:47:56 DEBUG| [stdout]   --- Volume group ---

mount
/dev/mapper/avocado_vg-avocado_lv 73786976294833019236 73786976294574596124 258406728 100% /home/ioci/logs/io_vscsi/results/job-2021-09-01T16.44-12c84eb/test-results/tmp_dirhqg_h2ae/01-avocado-misc-tests_io_disk_ltp_fs.py_LtpFs.test_fs_run_run-args-fs_di-fs-ext4-lv-lv-raid-raid-a181
[root@ltc-zz1b-lp2 test-results]# mount | grep lv
/dev/mapper/avocado_vg-avocado_lv on /home/ioci/logs/io_vscsi/results/job-2021-09-01T16.44-12c84eb/test-results/tmp_dirhqg_h2ae/01-avocado-misc-tests_io_disk_ltp_fs.py_LtpFs.test_fs_run_run-args-fs_di-fs-ext4-lv-lv-raid-raid-a181 type ext4 (ro,relatime,errors=continue,stripe=128)
[root@ltc-zz1b-lp2 test-results]#

**Comment by abdhaleegit** [comment]
```
Fetching asset from /home/ioci/avocado-fvt-wrapper/tests/avocado-misc-tests/io/disk/ltp_fs.py:LtpFs.test_fs_run
JOB ID     : 12c84ebfca1cf796e8fdcfacc19c957c9f543ada
JOB LOG    : /home/ioci/logs/io_vscsi/results/job-2021-09-01T16.44-12c84eb/job.log
[  938.091599] md127: detected capacity change from 0 to 1171858432^M
[  944.086029] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.^M
 (01/80) avocado-misc-tests/io/disk/ltp_fs.py:LtpFs.test_fs_run;run-args-fs_di-fs-ext4-lv-lv-raid-raid-a181:  ERROR: Command 'lvremove -f avocado_vg/avocado_lv' failed.\nstdout: b''\nstderr: b'  Logical volume avocado_vg/avocado_lv contains a filesystem in use.\n'\nadditional_info: None (184.73 s)
[ 1125.836008] EXT4-fs error (device dm-0): ext4_map_blocks:594: inode #8: block 32540482: comm jbd2/dm-0-8: lblock 1858 mapped to illegal pblock 32540482 (length 1)^M
[ 1125.836027] jbd2_journal_bmap: journal block not found at offset 1858 on dm-0-8^M
[ 1125.836032] Aborting journal on device dm-0-8.^M
[ 1126.395953] EXT4-fs error (device dm-0): ext4_journal_check_start:83: comm ext4lazyinit: Detected aborted journal^M
[ 1126.408656] EXT4-fs (dm-0): Remounting filesystem read-only^M
 (02/80) avocado-misc-tests/io/disk/ltp_fs.py:LtpFs.test_fs_run;run-args-fs_di-fs-ext4-lv-lv-raid-no_raid-2ef1:  FAIL: No test failures detected, but LTP finished with 1 (7.23 s)
 (03/80) avocado-misc-tests/io/disk/ltp_fs.py:LtpFs.test_fs_run;run-args-fs_di-fs-ext4-lv-no_lv-raid-raid-aed9:  FAIL: No test failures detected, but LTP finished with 1 (7.21 s)
 (04/80) avocado-misc-tests/io/disk/ltp_fs.py:LtpFs.test_fs_run;run-args-fs_di-fs-ext4-lv-no_lv-raid-no_raid-5910:  FAIL: No test failures detected, but LTP finished with 1 (7.25 s)

**Comment by PraveenPenguin** [comment]
closing this as it already fixed
