### ISSUE TITLE
After running disk_info.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Partition(/dev/sda): Failed to mkfs: Command 'yes | mkfs -t ext4 /dev/sda' failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2144]
After running disk_info.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Partition(/dev/sda): Failed to mkfs: Command 'yes | mkfs -t ext4 /dev/sda' failed”.

**《yaml-File》**
![y](https://user-images.githubusercontent.com/63998174/140284017-423b8b87-3d50-4e0d-afae-5d8e896c9718.png)

**《SOL-Log》**
![S](https://user-images.githubusercontent.com/63998174/140284062-614d4c8b-227a-4066-aeda-6c38981c6402.png)

**《Debug-Log of UID 3》**
L0658 INFO | Running 'yes | mkfs -t ext4 /dev/sda'
L0470 DEBUG| [stderr] mke2fs 1.45.6 (20-Mar-2020)
L0470 DEBUG| [stderr] /dev/sda is apparently in use by the system; will not make a filesystem here!
L0740 INFO | Command 'yes | mkfs -t ext4 /dev/sda' finished with 1 after 0.003442380s
L0039 ERROR|
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/partition.py", line 196, in mkfs
L0045 ERROR|     process.system_output("yes | %s" % mkfs_cmd, shell=True)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1223, in system_output
L0045 ERROR|     encoding=encoding)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1093, in run
L0045 ERROR|     raise CmdError(cmd, sp.result)
L0045 ERROR| avocado.utils.process.CmdError: Command 'yes | mkfs -t ext4 /dev/sda' failed.
L0045 ERROR| stdout: b''
L0045 ERROR| stderr: b'mke2fs 1.45.6 (20-Mar-2020)\n/dev/sda is apparently in use by the system; will not make a filesystem here!\n'
L0045 ERROR| additional_info: None

**《Manual-Test-Log》**
It is PASS to run “yes | mkfs -t ext4 /dev/sda” by manual, while it is FAIL to run by Avocado.
![M](https://user-images.githubusercontent.com/63998174/140284193-df150d3b-e4df-40db-9fe6-609b87d82ea9.png)

**《Test Log》**
[20211104-Storage3-disk_info.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7473434/20211104-Storage3-disk_info.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
After use 90 version of Avocado to re-test, the result becomes PASS. Thanks!!
