### ISSUE TITLE
After running fiotest.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Partition(/dev/sda): Failed to mkfs: Command 'yes | mkfs -t xfs -f /dev/sda' failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2145]
After running fiotest.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Partition(/dev/sda): Failed to mkfs: Command 'yes | mkfs -t xfs -f /dev/sda' failed”.

**《yaml-File》**
![y](https://user-images.githubusercontent.com/63998174/140284716-e6aecac7-470b-439f-930d-3a5cb6ac343b.png)

**《SOL-Log》**
![S](https://user-images.githubusercontent.com/63998174/140284805-55f2f93b-f04e-45af-8878-49c23985632e.png)

**《Debug-Log of UID 8》**
L0658 INFO | Running 'yes | mkfs -t xfs  -f /dev/sda'
L0470 DEBUG| [stderr] mkfs.xfs: cannot open /dev/sda: Device or resource busy
L0740 INFO | Command 'yes | mkfs -t xfs  -f /dev/sda' finished with 1 after 0.003905279s
L0039 ERROR|
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:778
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/partition.py", line 196, in mkfs
L0045 ERROR|     process.system_output("yes | %s" % mkfs_cmd, shell=True)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1223, in system_output
L0045 ERROR|     encoding=encoding)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1093, in run
L0045 ERROR|     raise CmdError(cmd, sp.result)
L0045 ERROR| avocado.utils.process.CmdError: Command 'yes | mkfs -t xfs  -f /dev/sda' failed.
L0045 ERROR| stdout: b''
L0045 ERROR| stderr: b'mkfs.xfs: cannot open /dev/sda: Device or resource busy\n'
L0045 ERROR| additional_info: None

**《Manual-Test-Log》**
![M](https://user-images.githubusercontent.com/63998174/140284935-80b60198-fb3c-44f5-9858-b220f05b7f43.png)

**《Test Log》**
[20211104-Storage3-fiotest.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7473470/20211104-Storage3-fiotest.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
After use 90 version of Avocado to re-test, the result becomes PASS. Thanks!!
