### ISSUE TITLE
After running tiobench.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Partition(/dev/sda): Failed to mkfs: Command 'yes | mkfs -t ext4 /dev/sda' failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2146]
After running tiobench.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Partition(/dev/sda): Failed to mkfs: Command 'yes | mkfs -t ext4 /dev/sda' failed”.

**《yaml-File》**
![y](https://user-images.githubusercontent.com/63998174/140285292-98b992b4-ee65-4dad-a687-8d3d506128e3.png)

**《SOL-Log》**
![S](https://user-images.githubusercontent.com/63998174/140285345-3e7c3dac-b53c-4d3a-9851-78663773bac0.png)

**《Debug-Log of UID 7》**
L0465 DEBUG| Test workdir initialized at: /var/tmp/.avocado-taskpc5nytjz/test-results/tmp_dirtnusj8d_/1-Tiobench.test
L0305 DEBUG| /dev/sda not mounted
L0658 INFO | Running 'yes | mkfs -t ext4 /dev/sda'
L0470 DEBUG| [stderr] mke2fs 1.45.6 (20-Mar-2020)
L0470 DEBUG| [stderr] /dev/sda is apparently in use by the system; will not make a filesystem here!
L0740 INFO | Command 'yes | mkfs -t ext4 /dev/sda' finished with 1 after 0.003046861s
L0039 ERROR|
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:778
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/partition.py", line 196, in mkfs
L0045 ERROR|     process.system_output("yes | %s" % mkfs_cmd, shell=True)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1223, in system_output
L0045 ERROR|     encoding=encoding)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1093, in run
L0045 ERROR|     raise CmdError(cmd, sp.result)
L0045 ERROR| avocado.utils.process.CmdError: Command 'yes | mkfs -t ext4 /dev/sda' failed.
L0045 ERROR| stdout: b''
L0045 ERROR| stderr: b'mke2fs 1.45.6 (20-Mar-2020)\n/dev/sda is apparently in use by the system; will not make a filesystem here!\n'
L0045 ERROR| additional_info: None

**《Manual-Test-Log》**
It is PASS to run “yes | mkfs -t ext4 /dev/sda” by manual, while it is FAIL to run by Avocado.
![M](https://user-images.githubusercontent.com/63998174/140285466-be48ae65-efe4-4912-a279-0d3f7ff210c5.png)

**《Test Log》**
[20211104-Storage3-tiobench.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7473491/20211104-Storage3-tiobench.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
After use 90 version of Avocado to re-test, the result becomes PASS. Thanks!!
