### ISSUE TITLE
After running disktest.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Partition(/dev/sda): Failed to mkfs: Command 'yes | mkfs -t xfs  -f /dev/sda' failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2147]
After running disktest.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Partition(/dev/sda): Failed to mkfs: Command 'yes | mkfs -t xfs  -f /dev/sda' failed”.

**《yaml-File》**
![yaml_disktest](https://user-images.githubusercontent.com/63998174/140444029-988347c5-cf21-4442-a01b-1580fd4c935d.png)

**《SOL-Log》**
![SOL_disktest](https://user-images.githubusercontent.com/63998174/140444043-78e79cd3-070b-4994-83cb-8ea1ae79e5d3.png)

**《Debug-Log of UID 2》**
L0101 INFO | creating xfs fs on /dev/sda
L0658 INFO | Running 'yes | mkfs -t xfs  -f /dev/sda'
L0470 DEBUG| [stderr] mkfs.xfs: cannot open /dev/sda: Device or resource busy
L0740 INFO | Command 'yes | mkfs -t xfs  -f /dev/sda' finished with 1 after 0.005769657s
L0039 ERROR|
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:778
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/partition.py", line 196, in mkfs
L0045 ERROR|     process.system_output("yes | %s" % mkfs_cmd, shell=True)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1223, in system_output
L0045 ERROR|     encoding=encoding)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1093, in run
L0045 ERROR|     raise CmdError(cmd, sp.result)
L0045 ERROR| avocado.utils.process.CmdError: Command 'yes | mkfs -t xfs  -f /dev/sda' failed.
L0045 ERROR| stdout: b''
L0045 ERROR| stderr: b'mkfs.xfs: cannot open /dev/sda: Device or resource busy\n'
L0045 ERROR| additional_info: None

**《Manual-Test-Log》**
![Manual-XFS](https://user-images.githubusercontent.com/63998174/140444140-b4aac4ae-b785-420e-a29d-4ea2e38507b1.png)

**《Test Log》**
[20211104-Storage3-disktest.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7479927/20211104-Storage3-disktest.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
After use 90 version of Avocado to re-test, the result becomes PASS. Thanks!!
