### ISSUE TITLE
After running Network_config.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: __init__() got an unexpected keyword argument 'run.results_dir'”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2148]
After running Network_config.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: __init__() got an unexpected keyword argument 'run.results_dir'”.

**《yaml-File》**
![yaml](https://user-images.githubusercontent.com/63998174/140462081-87e1aa3b-7d56-4c53-8c58-1d79cb1ac227.png)

**《SOL-Log》**
![SOL](https://user-images.githubusercontent.com/63998174/140462120-73d4e146-ef8c-4163-aef8-1bc17989c140.png)

**《Debug-Log of UID 1》**
[stderr]   File "/usr/local/lib/python3.6/site-packages/avocado/core/loader.py", line 288, in load_test
[stderr]     test_module = imp.load_module(module_name, f, p, d)
[stderr]   File "/usr/lib64/python3.6/imp.py", line 235, in load_module
[stderr]     return load_source(name, filename, file)
[stderr]   File "/usr/lib64/python3.6/imp.py", line 172, in load_source
[stderr]     module = _load(spec)
[stderr]   File "<frozen importlib._bootstrap>", line 684, in _load
[stderr]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
[stderr]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[stderr]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[stderr]   File "/root/tests/tests/avocado-misc-tests/io/net/Network_config.py", line 21, in <module>
[stderr]     import netifaces
[stderr] ModuleNotFoundError: No module named 'netifaces'

**《Test-Log》**
[20211105-Network10-Network_config.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7480756/20211105-Network10-Network_config.zip)

**《Network-Card Setting》**
[SOP of Network-Card Setting.pdf](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7480751/SOP.of.Network-Card.Setting.pdf)

**《Configuration》**
【SUT1】
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology(18ASF2G72PZ-2G9E1)16GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot2: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot7: Nvidia T4 Accelerator 16GB PCIe3 x16 LP
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP

【SUT2】
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
After we run it via cmd "avocado run --test-runner runner Network_config.py -m Network_config.py.data/Network_config.yaml", it shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py", line 235, in load_module'.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/142382347-c84731fd-d708-4178-b658-340b71b37e54.png)

**《Test-Log》**
[20211118-Network10-test_runner-Network_config.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7561399/20211118-Network10-test_runner-Network_config.zip)

**Comment by Gene-Lo** [comment]
When we use **Version 93 of Avocado** to re-test via cmd "avocado run --test-runner runner Network_config.py -m Network_config.py.data/Network_config.yaml", it still shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py"'.

**《SOL-Log》**
![1](https://user-images.githubusercontent.com/63998174/144341036-220bddaa-fead-437f-a892-01b96449b701.png)

**《Test-Log》**
[20211201-Network7-SUT4.2_2.5-test_runner-Network_config.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7638207/20211201-Network7-SUT4.2_2.5-test_runner-Network_config.zip)

Then we use **Version 90 of Avocado** to re-test via cmd "avocado run Network_config.py -m Network_config.py.data/Network_config.yaml", it still shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py"'.

**《Test-Log》**
[20211201-Network7-SUT4.2_2.5-Network_config.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7638217/20211201-Network7-SUT4.2_2.5-Network_config.zip)

Finally we use **Version 80 of Avocado** to re-test via cmd "avocado runNetwork_config.py -m Network_config.py.data/Network_config.yaml", it still shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py"'.

**《Test-Log》**
[20211202-Network7-SUT4.2_2.5-test_runner-Network_config.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7638229/20211202-Network7-SUT4.2_2.5-test_runner-Network_config.zip)

Since we could use **Version 80 of Avocado** to test PASS in Rhel8.2 OS before, please check if the issue's root cause comes from Rhel8.4 OS, and if there is any settings need to change. Thanks !!

**Comment by Gene-Lo** [comment]
After use **Version 90 of Avocado** to test, the result becomes PASS. Thanks!!
