### ISSUE TITLE
After running ethtool-test.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: __init__() got an unexpected keyword argument 'run.results_dir'”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2151]
After running ethtool-test.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: __init__() got an unexpected keyword argument 'run.results_dir'”.

**《yaml-File》**
![yaml](https://user-images.githubusercontent.com/63998174/140463617-8e100bae-242a-449a-a07a-44d39c00a81b.png)

**《SOL-Log》**
![SOL](https://user-images.githubusercontent.com/63998174/140463635-294c656b-916b-4ecc-9896-f3c59b2ab038.png)

**《Debug-Log of UID 1》**
[stderr]   File "/usr/local/lib/python3.6/site-packages/avocado/core/loader.py", line 288, in load_test
[stderr]     test_module = imp.load_module(module_name, f, p, d)
[stderr]   File "/usr/lib64/python3.6/imp.py", line 235, in load_module
[stderr]     return load_source(name, filename, file)
[stderr]   File "/usr/lib64/python3.6/imp.py", line 172, in load_source
[stderr]     module = _load(spec)
[stderr]   File "<frozen importlib._bootstrap>", line 684, in _load
[stderr]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
[stderr]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[stderr]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[stderr]   File "/root/tests/tests/avocado-misc-tests/io/net/Network_config.py", line 21, in <module>
[stderr]     import netifaces
[stderr] ModuleNotFoundError: No module named 'netifaces'

**《Test-Log》**
[20211105-Network10-ethtool_test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7480844/20211105-Network10-ethtool_test.zip)

**《Network-Card Setting》**
[SOP of Network-Card Setting.pdf](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7480846/SOP.of.Network-Card.Setting.pdf)

**《Configuration》**
【SUT1】
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology(18ASF2G72PZ-2G9E1)16GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot2: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot7: Nvidia T4 Accelerator 16GB PCIe3 x16 LP
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP

【SUT2】
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
After we run it via cmd "avocado run --test-runner runner ethtool_test.py -m ethtool_test.py.data/ethtool_test.yaml", it shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py", line 235, in load_module'.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/142382671-c743b7cd-b3ae-40e3-9368-036e5c247864.png)

**《Test-Log》**
[20211118-Network10-test_runner-ethtool_test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7561414/20211118-Network10-test_runner-ethtool_test.zip)

**Comment by Gene-Lo** [comment]
When we use **Version 93 of Avocado** to re-test via cmd "avocado run --test-runner runner ethtool_test.py -m ethtool_test.py.data/ethtool_test.yaml", it still shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py"'.

**《SOL-Log》**
![1](https://user-images.githubusercontent.com/63998174/144341977-02c87ba1-2b84-42fe-95ff-dea53b411d42.png)

**《Test-Log》**
[20211201-Network7-SUT4.2_2.5-test_runner-ethtool_test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7638285/20211201-Network7-SUT4.2_2.5-test_runner-ethtool_test.zip)

Then we use **Version 90 of Avocado** to re-test via cmd "avocado run ethtool_test.py -m ethtool_test.py.data/ethtool_test.yaml", it still shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py"'.

**《Test-Log》**
[20211201-Network7-SUT4.2_2.5-ethtool_test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7638288/20211201-Network7-SUT4.2_2.5-ethtool_test.zip)

Finally we use **Version 80 of Avocado** to re-test via cmd "avocado runethtool_test.py -m ethtool_test.py.data/ethtool_test.yaml", it still shows 'ERROR: Traceback (most recent call last):\n  File "/usr/lib64/python3.6/imp.py"'.

**《Test-Log》**
[20211202-Network7-SUT4.2_2.5-test_runner-ethtool_test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7638292/20211202-Network7-SUT4.2_2.5-test_runner-ethtool_test.zip)

Since in the past we could use **Version 80 of Avocado** to test PASS in **Rhel8.2 OS**, please check if the issue's root cause comes from **Rhel8.4 OS**, and if there is any settings need to change. Thanks !!

**Comment by Gene-Lo** [comment]
After use **Version 90 of Avocado** to test, the result becomes PASS. Thanks!!
