### ISSUE TITLE
After running kretprobe.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: insmod kretprobe_example.ko failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2158]
After running kretprobe.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: insmod kretprobe_example.ko failed”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/140877614-e1179569-e407-4198-8021-3e038aad0cf1.png)

**《Debug-Log of UID 1》**
L0087 INFO | Fetching https://raw.githubusercontent.com/torvalds/linux/master/samples/kprobes/kretprobe_example.c -> /root/avocado/data/cache/by_location/84d0a6769cb0569c52065a2ce18b92c3a18a42da/kretprobe_example.c.edf5c304-4c8e-42b6-9afc-ad60136124e6
L0058 DEBUG| Retrieved URL "https://raw.githubusercontent.com/torvalds/linux/master/samples/kprobes/kretprobe_example.c": content-length 3075, date: "Fri, 05 Nov 2021 09:18:39 GMT", last-modified: "UNKNOWN"
L0261 WARNI| No hash provided. Cannot check the asset file integrity.
L0658 INFO | Running 'make'
L0470 DEBUG| [stdout] make -C /lib/modules/4.18.0-305.el8.ppc64le/build SUBDIRS=/var/tmp/tmpauhqqrrd modules
L0470 DEBUG| [stdout] make[1]: Entering directory '/usr/src/kernels/4.18.0-305.el8.ppc64le'
L0470 DEBUG| [stdout]   CC [M]  /var/tmp/tmpauhqqrrd/kretprobe_example.o
L0470 DEBUG| [stdout]   Building modules, stage 2.
L0470 DEBUG| [stdout]   MODPOST 1 modules
L0470 DEBUG| [stdout]   CC      /var/tmp/tmpauhqqrrd/kretprobe_example.mod.o
L0470 DEBUG| [stdout]   LD [M]  /var/tmp/tmpauhqqrrd/kretprobe_example.ko
L0470 DEBUG| [stdout] make[1]: Leaving directory '/usr/src/kernels/4.18.0-305.el8.ppc64le'
L0740 INFO | Command 'make' finished with 0 after 1.174402361s
L0106 INFO | ============== Testing kretprobe =================
L0658 INFO | Running 'dmesg -C '
L0740 INFO | Command 'dmesg -C ' finished with 0 after 0.000615518s
L0036 INFO | executing ============== insmod ./kretprobe_example.ko =================
L0658 INFO | Running 'insmod ./kretprobe_example.ko'
L0470 DEBUG| [stderr] insmod: ERROR: could not insert module ./kretprobe_example.ko: Invalid parameters
L0740 INFO | Command 'insmod ./kretprobe_example.ko' finished with 1 after 0.114950039s
L0039 ERROR|
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/kretprobe.py", line 132, in test
L0045 ERROR|     self.execute_test()
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/kretprobe.py", line 110, in execute_test
L0045 ERROR|     self.fail("insmod kretprobe_example.ko failed")
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: insmod kretprobe_example.ko failed

**《Manual Test Log》**
After running kprobe.py, there is no kretprobe_example.ko in SUT, which may cause the result FAIL.
[Manual-Test-Log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7502674/Manual-Test-Log.txt)

**《Avocado Test Log》**
[20211105-SUT1-RAS-kretprobe.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7502675/20211105-SUT1-RAS-kretprobe.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
Recently we use **Version 80 of Avocado** to run kretprobe.py in **Rhel8.4**, and it still shows "FAIL: insmod kretprobe_example.ko failed":

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/144987647-6c7ef793-5067-4c80-977e-347951e70553.png)

**《Avocado Test Log》**
[20211207-Distro-Avocado80-kretprobe.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7666428/20211207-Distro-Avocado80-kretprobe.zip)

Since in the past we could use **Version 80 of Avocado** to run kretprobe.py in **Rhel8.2**, and the result was PASS, please check if it is **Rhel8.4**'s limit to run kretprobe.py. Thanks!!

**《Configuration》**
[Kernel]
4.18.0-305.el8.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 16 core *2
Micron Technology(36ASF4G72PZ-2G6D1)32GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot2: Emulex LPE16002B-M6-O 2-port 16Gb Fibre Channel card PCIe3 x8 LP
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot7: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9:  Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8
00VN628 - Micron 5100 PRO - SSD 1920GB SATA *8
00VN629 - Micron 5100 PRO - SSD 3840GB SATA *8

**Comment by Gene-Lo** [comment]
After we use Version 93 of Avocado to re-test it, it still shows "FAIL: insmod kretprobe_example.ko failed".

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/146856858-12f5a611-dbc6-4b71-95ec-0267b7a04d23.png)

**《Avocado Test Log》**
[job.log](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7748974/job.log)

**Comment by PraveenPenguin** [comment]
@disgoel is this still an issue on the recent run?
