### ISSUE TITLE
After running ras_extended.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: 2 command(s) failed in vpdupdate tool verification”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2159]
After running ras_extended.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: 2 command(s) failed in vpdupdate tool verification”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/140877914-9ba459c7-6b55-4469-9005-e0da3bb4d83a.png)

**《Debug-Log of UID 9》**
L0658 INFO | Running 'vpdupdate'
L0740 INFO | Command 'vpdupdate' finished with 0 after 0.915913783s
L0658 INFO | Running 'rm -f /var/lib/lsvpd/vpd.db; touch /var/lib/lsvpd/vpd.db'
L0740 INFO | Command 'rm -f /var/lib/lsvpd/vpd.db; touch /var/lib/lsvpd/vpd.db' finished with 0 after 0.002447623s
L0658 INFO | Running 'lsvpd | grep run | grep vpdupdate'
L0470 DEBUG| [stdout] Please run /usr/sbin/vpdupdate again, before running lsvpd.
L0740 INFO | Command 'lsvpd | grep run | grep vpdupdate' finished with 0 after 0.062155973s
L0658 INFO | Running 'lscfg | grep run | grep vpdupdate'
L0470 DEBUG| [stdout] Please run vpdupdate command, before running lscfg.
L0740 INFO | Command 'lscfg | grep run | grep vpdupdate' finished with 0 after 0.055286428s
L0658 INFO | Running 'lsmcode | grep run | grep vpdupdate'
L0470 DEBUG| [stdout] Please run vpdupdate command, before running lsmcode.
L0740 INFO | Command 'lsmcode | grep run | grep vpdupdate' finished with 0 after 0.047145319s
L0658 INFO | Running 'vpdupdate'
L0740 INFO | Command 'vpdupdate' finished with 0 after 0.897278938s
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/decorators.py", line 90, in wrapper
L0045 ERROR|     return function(obj, *args, **kwargs)
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/ras/ras_extended.py", line 199, in test1_vpdupdate
L0045 ERROR|     "verification" % self.is_fail)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: 2 command(s) failed in vpdupdate tool verification
L0046 ERROR|

**《Manual Test Log》**
[root@sut1 ~]# vpdupdate --version
vpdupdate 1.7.11
[root@sut1 ~]# vpdupdate
[root@sut1 ~]# rm -f /var/lib/lsvpd/vpd.db; touch /var/lib/lsvpd/vpd.db
[root@sut1 ~]# lsvpd | grep vpdupdate
Please run /usr/sbin/vpdupdate again, before running lsvpd.
[root@sut1 ~]# lscfg | grep vpdupdate
Please run vpdupdate command, before running lscfg.
[root@sut1 ~]# lsvpd | grep vpdupdate
Please run /usr/sbin/vpdupdate again, before running lsvpd.
[root@sut1 ~]#

※ The result of Manual-Test is as same as the result of Avocado script.

**《Avocado Test Log》**
[20211108-SUT1-RAS-ras_extended.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7502680/20211108-SUT1-RAS-ras_extended.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
After use **Version 90 of Avocado** to test, the result becomes PASS. Thanks!!
