### ISSUE TITLE
After running memhotplug.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: unable to hot-unplug memory99 block. Device busy?”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2162]
After running memhotplug.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: unable to hot-unplug memory99 block. Device busy?”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/140894955-1f1af5de-e348-4d3a-986b-f1344aa4c22e.png)

**《Debug-Log of UID 1》**
[stdlog] 2021-11-08 20:38:39,030 process          L0658 INFO | Running 'rpm -q stress'
[stdlog] 2021-11-08 20:38:39,041 process          L0470 DEBUG| [stdout] stress-1.0.4-24.el8.ppc64le
[stdlog] 2021-11-08 20:38:39,041 process          L0740 INFO | Command 'rpm -q stress' finished with 0 after 0.009688644s
[stdlog] 2021-11-08 20:38:39,041 parameters       L0143 DEBUG| PARAMS (key=iteration, path=*, default=1) => 1
[stdlog] 2021-11-08 20:38:39,042 parameters       L0143 DEBUG| PARAMS (key=stresstime, path=*, default=10) => 10
[stdlog] 2021-11-08 20:38:39,042 parameters       L0143 DEBUG| PARAMS (key=vmcount, path=*, default=4) => 4
[stdlog] 2021-11-08 20:38:39,042 parameters       L0143 DEBUG| PARAMS (key=iocount, path=*, default=4) => 4
[stdlog] 2021-11-08 20:38:39,042 parameters       L0143 DEBUG| PARAMS (key=memratio, path=*, default=5) => 5
[stdlog] 2021-11-08 20:38:49,220 memhotplug       L0138 ERROR| memory99 : Resource is busy
[stdlog] 2021-11-08 20:38:59,410 memhotplug       L0138 ERROR| memory32 : Resource is busy
[stdlog] 2021-11-08 20:38:59,411 process          L0658 INFO | Running 'dmesg -C '
[stdlog] 2021-11-08 20:38:59,412 process          L0740 INFO | Command 'dmesg -C ' finished with 0 after 0.000711275s
[stdlog] 2021-11-08 20:38:59,412 memhotplug       L0165 INFO | 
[stdlog] TEST: hotunplug and hotplug in a loop
[stdlog] 2021-11-08 20:38:59,413 memhotplug       L0167 INFO | 
[stdlog] hotunplug all memory
[stdlog] 2021-11-08 20:39:20,250 stacktrace       L0039 ERROR| 
[stdlog] 2021-11-08 20:39:20,250 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
[stdlog] 2021-11-08 20:39:20,252 stacktrace       L0045 ERROR| Traceback (most recent call last):
[stdlog] 2021-11-08 20:39:20,253 stacktrace       L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/memory/memhotplug.py", line 168, in test_hotplug_loop
[stdlog] 2021-11-08 20:39:20,253 stacktrace       L0045 ERROR|     self.hotunplug_all(self.blocks_hotpluggable)
[stdlog] 2021-11-08 20:39:20,253 stacktrace       L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/memory/memhotplug.py", line 129, in hotunplug_all
[stdlog] 2021-11-08 20:39:20,253 stacktrace       L0045 ERROR|     err = offline(block)
[stdlog] 2021-11-08 20:39:20,253 stacktrace       L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/memory/memhotplug.py", line 52, in offline
[stdlog] 2021-11-08 20:39:20,253 stacktrace       L0045 ERROR|     memory.hotunplug(block)
[stdlog] 2021-11-08 20:39:20,253 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/memory.py", line 122, in hotunplug
[stdlog] 2021-11-08 20:39:20,253 stacktrace       L0045 ERROR|     "unable to hot-unplug %s block. Device busy?" % block)
[stdlog] 2021-11-08 20:39:20,253 stacktrace       L0045 ERROR| avocado.utils.memory.MemError: unable to hot-unplug memory99 block. Device busy?
[stdlog] 2021-11-08 20:39:20,253 stacktrace       L0046 ERROR|

**※ Can you provide manual-test-commands to us for testing it by manual? Thanks!!**

**《Avocado Test Log》**
[20211108-SUT1-Distro-memhotplug.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7503411/20211108-SUT1-Distro-memhotplug.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
After we use Version 93 of Avocado to re-test, the result becomes PASS.
[20211220-Avocado93-SUT1.13-memhotplug.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7748897/20211220-Avocado93-SUT1.13-memhotplug.zip)
