### ISSUE TITLE
After running numa_test.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: Please check the logs for failure”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2164]
After running numa_test.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: Please check the logs for failure”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/140895824-b13c336c-df5b-4643-8e9e-d2b96248b76c.png)

**《Debug-Log of UID 1》**
[stdlog] 2021-11-05 19:52:39,362 process          L0658 INFO | Running 'make'
[stdlog] 2021-11-05 19:52:39,365 process          L0470 DEBUG| [stdout] cc -o numa_test numa_test.c util.c -lpthread -lnuma -lhugetlbfs
[stdlog] 2021-11-05 19:52:39,365 process          L0470 DEBUG| [stdout] cc -o softoffline softoffline.c util.c -lpthread -lnuma -lhugetlbfs
[stdlog] 2021-11-05 19:52:39,365 process          L0470 DEBUG| [stdout] cc -o bench_movepages bench_movepages.c util.c -lpthread -lnuma -lhugetlbfs
[stdlog] 2021-11-05 19:52:39,454 process          L0740 INFO | Command 'make' finished with 0 after 0.090844510s
[stdlog] 2021-11-05 19:52:39,455 numa_test        L0091 INFO | Starting test...
[stdlog] 2021-11-05 19:52:39,455 process          L0658 INFO | Running './numa_test -m shared -n 20'
[stdlog] 2021-11-05 19:52:39,457 process          L0470 DEBUG| [stderr] /bin/sh: ./numa_test: Permission denied
[stdlog] 2021-11-05 19:52:39,457 process          L0740 INFO | Command './numa_test -m shared -n 20' finished with 126 after 0.001272148s
[stdlog] 2021-11-05 19:52:39,457 stacktrace       L0039 ERROR| 
[stdlog] 2021-11-05 19:52:39,458 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
[stdlog] 2021-11-05 19:52:39,459 stacktrace       L0045 ERROR| Traceback (most recent call last):
[stdlog] 2021-11-05 19:52:39,459 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/decorators.py", line 90, in wrapper
[stdlog] 2021-11-05 19:52:39,459 stacktrace       L0045 ERROR|     return function(obj, *args, **kwargs)
[stdlog] 2021-11-05 19:52:39,459 stacktrace       L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/memory/numa_test.py", line 99, in test_movepages
[stdlog] 2021-11-05 19:52:39,459 stacktrace       L0045 ERROR|     self.fail('Please check the logs for failure')
[stdlog] 2021-11-05 19:52:39,459 stacktrace       L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
[stdlog] 2021-11-05 19:52:39,459 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
[stdlog] 2021-11-05 19:52:39,460 stacktrace       L0045 ERROR| avocado.core.exceptions.TestFail: Please check the logs for failure
[stdlog] 2021-11-05 19:52:39,460 stacktrace       L0046 ERROR| 

**《Manual Test Log》**
※ Manual-Test result:
UID-1: Run “./numa_test -m shared -n 20”, and it shows “PASS”. → Please check if it is script's issue.
UID-3: Run “./numa_test -m private -n 20”, and it shows “PASS”. → Please check if it is script's issue.
UID-4: Run “./numa_test -m private -n 20 -h”, and it shows “FAIL”.
UID-7: No Manual-Test-Commands to test. → Please provide Manual-Test-Commands to us for testing it by manual.
UID-10: After run “./bench_movepages -n 20”, it shows “THP page migration took more time”, and then stop test.
UID-12: After run “./bench_movepages -n 20”, it shows “THP page migration took more time”, and then stop test.
[Manual-Test-Log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7503454/Manual-Test-Log.txt)

**《Avocado Test Log》**
[20211105-SUT1-Distro-numa_test.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7503464/20211105-SUT1-Distro-numa_test.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by PraveenPenguin** [comment]
closing this as we have fixes already preset in master barach
