### ISSUE TITLE
After running perf_basic.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: perf: failed to execute command perf annotate --stdio”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2165]
After running perf_basic.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: perf: failed to execute command perf annotate --stdio”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/140896746-ed8a43f2-52af-4796-b64c-0f76b08838cb.png)

**《Debug-Log of UID 6》**
L0658 INFO | Running 'perf annotate --stdio'
L0470 DEBUG| [stderr] zero-sized data (perf.data), nothing to do!
L0740 INFO | Command 'perf annotate --stdio' finished with 255 after 0.012547387s
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/perf/perf_basic.py", line 98, in test_perf_cmd_annotate
L0045 ERROR|     self.run_cmd("perf annotate --stdio")
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/perf/perf_basic.py", line 55, in run_cmd
L0045 ERROR|     self.fail("perf: failed to execute command %s" % cmd)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: perf: failed to execute command perf annotate --stdio
L0046 ERROR| 

**《Debug-Log of UID 7》**
L0658 INFO | Running 'perf evlist -v'
L0470 DEBUG| [stderr] zero-sized data (perf.data), nothing to do!
L0740 INFO | Command 'perf evlist -v' finished with 255 after 0.012395005s
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/perf/perf_basic.py", line 101, in test_perf_cmd_evlist
L0045 ERROR|     self.run_cmd("perf evlist -v")
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/perf/perf_basic.py", line 55, in run_cmd
L0045 ERROR|     self.fail("perf: failed to execute command %s" % cmd)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: perf: failed to execute command perf evlist -v
L0046 ERROR| 

**《Manual Test Log》**
[root@sut1 ~]# perf version
perf version 4.18.0-305.el8.ppc64le
[root@sut1 ~]# perf annotate
failed to open perf.data: No such file or directory  (try 'perf record' first)
[root@sut1 ~]# perf annotate --stdio
failed to open perf.data: No such file or directory  (try 'perf record' first)
[root@sut1 ~]# perf evlist
failed to open perf.data: No such file or directory  (try 'perf record' first)
[root@sut1 ~]# perf evlist -v
failed to open perf.data: No such file or directory  (try 'perf record' first)
[root@sut1 ~]#

**※ The result of Manual-Test is as same as the result of Avocado script.**

**《Avocado Test Log》**
[20211108-SUT1-Distro-perf_basic.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7503501/20211108-SUT1-Distro-perf_basic.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
After use **Version 90 of Avocado** to test, the result becomes PASS. Thanks!!
