### ISSUE TITLE
After running perf_pcp.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: PCP: perfevent pmda not removed from pmcd daemon”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2167]
After running perf_pcp.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: PCP: perfevent pmda not removed from pmcd daemon”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/141055953-f4908a36-2003-4555-a0b8-207b40b72268.png)

**《Debug-Log of UID 5》**
L0658 INFO | Running 'systemctl restart pmcd'
L0740 INFO | Command 'systemctl restart pmcd' finished with 0 after 16.210057084s
L0658 INFO | Running 'systemctl status pmcd'
L0740 INFO | Command 'systemctl status pmcd' finished with 0 after 0.011288483s
L0470 DEBUG| [stdout] ● pmcd.service - Performance Metrics Collector Daemon
L0470 DEBUG| [stdout]    Loaded: loaded (/usr/lib/systemd/system/pmcd.service; enabled; vendor preset: disabled)
L0470 DEBUG| [stdout]    Active: active (running) since Fri 2021-11-05 20:04:40 CST; 15ms ago
L0470 DEBUG| [stdout]      Docs: man:pmcd(1)
L0470 DEBUG| [stdout]   Process: 466406 ExecStop=/usr/libexec/pcp/lib/pmcd stop-systemd (code=exited, status=0/SUCCESS)
L0470 DEBUG| [stdout]  Main PID: 467101 (pmcd)
L0470 DEBUG| [stdout]     Tasks: 15 (limit: 3156021)
L0470 DEBUG| [stdout]    Memory: 143.2M
L0470 DEBUG| [stdout]    CGroup: /system.slice/pmcd.service
L0470 DEBUG| [stdout]            ├─467022 /bin/sh /usr/libexec/pcp/lib/pmcd start-systemd
L0470 DEBUG| [stdout]            ├─467101 /usr/libexec/pcp/bin/pmcd
L0470 DEBUG| [stdout]            ├─467114 /var/lib/pcp/pmdas/root/pmdaroot
L0470 DEBUG| [stdout]            ├─467115 /var/lib/pcp/pmdas/proc/pmdaproc -d 3
L0470 DEBUG| [stdout]            ├─467117 /var/lib/pcp/pmdas/xfs/pmdaxfs -d 11
L0470 DEBUG| [stdout]            ├─467118 /var/lib/pcp/pmdas/linux/pmdalinux
L0470 DEBUG| [stdout]            ├─467119 python3 /var/lib/pcp/pmdas/nfsclient/pmdanfsclient.python
L0470 DEBUG| [stdout]            ├─467123 /var/lib/pcp/pmdas/kvm/pmdakvm -d 95
L0470 DEBUG| [stdout]            ├─467124 /var/lib/pcp/pmdas/perfevent/pmdaperfevent -d 127
L0470 DEBUG| [stdout]            ├─467126 /var/lib/pcp/pmdas/dm/pmdadm -d 129
L0470 DEBUG| [stdout]            ├─467127 python3 /var/lib/pcp/pmdas/openmetrics/pmdaopenmetrics.python
L0470 DEBUG| [stdout]            ├─467139 /bin/sh /etc/pcp/pmcd/rc.local -v start
L0470 DEBUG| [stdout]            └─467143 grep :/usr/bin:
L0470 DEBUG| [stdout] 
L0470 DEBUG| [stdout] Nov 05 20:04:28 sut1 systemd[1]: Starting Performance Metrics Collector Daemon...
L0470 DEBUG| [stdout] Nov 05 20:04:40 sut1 systemd[1]: Started Performance Metrics Collector Daemon.
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/perf/perf_pcp.py", line 110, in test_pmda_perfevent_remove
L0045 ERROR|     self.fail("PCP: perfevent pmda not removed from pmcd daemon")
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: PCP: perfevent pmda not removed from pmcd daemon
L0046 ERROR| 
L0798 DEBUG| Local variables:
L0801 DEBUG|  -> output <class 'avocado.utils.process.CmdResult'>: command: 'systemctl status pmcd'

**《Manual-Test-Log of UID 5》**
**※ The result of Manual-Test is as same as the result of Avocado script.**

[root@sut1 ~]# systemctl restart pmcd
[root@sut1 ~]# systemctl status pmcd
● pmcd.service - Performance Metrics Collector Daemon
   Loaded: loaded (/usr/lib/systemd/system/pmcd.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2021-11-09 17:47:40 CST; 5s ago
     Docs: man:pmcd(1)
  Process: 55761 ExecStop=/usr/libexec/pcp/lib/pmcd stop-systemd (code=exited, status=0/SUCCESS)
 Main PID: 56193 (pmcd)
    Tasks: 10 (limit: 3156021)
   Memory: 134.2M
   CGroup: /system.slice/pmcd.service
           ├─56193 /usr/libexec/pcp/bin/pmcd
           ├─56198 /var/lib/pcp/pmdas/root/pmdaroot
           ├─56199 /var/lib/pcp/pmdas/proc/pmdaproc -d 3
           ├─56201 /var/lib/pcp/pmdas/xfs/pmdaxfs -d 11
           ├─56202 /var/lib/pcp/pmdas/linux/pmdalinux
           ├─56203 python3 /var/lib/pcp/pmdas/nfsclient/pmdanfsclient.python
           ├─56207 /var/lib/pcp/pmdas/kvm/pmdakvm -d 95
           ├─56208 /var/lib/pcp/pmdas/dm/pmdadm -d 129
           └─56209 python3 /var/lib/pcp/pmdas/openmetrics/pmdaopenmetrics.python

Nov 09 17:47:29 sut1 systemd[1]: Starting Performance Metrics Collector Daemon...
Nov 09 17:47:40 sut1 systemd[1]: Started Performance Metrics Collector Daemon.
[root@sut1 ~]#

**《Avocado Test Log》**
[20211105-SUT1-Distro-perf_pcp.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7510129/20211105-SUT1-Distro-perf_pcp.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
After use **Version 90 of Avocado** to test, the result becomes PASS. Thanks!!
