### ISSUE TITLE
After running perf_uprobe.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Command 'perf probe -d \*' failed.”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2168]
After running perf_uprobe.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Command 'perf probe -d \*' failed.”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/141056162-a48b1973-2c58-4e7a-ba5d-c13401bd79d0.png)

**《Debug-Log of UID 1》**
L0658 INFO | Running 'perf probe -d \*'
L0740 INFO | Command 'perf probe -d \*' finished with 254 after 0.011006330s
L0470 DEBUG| [stderr] "*" does not hit any event.
L0470 DEBUG| [stderr]   Error: Failed to delete events.
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:819
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/perf/perf_uprobe.py", line 123, in tearDown
L0045 ERROR|     self.cmd_verify('perf probe -d \\*')
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/perf/perf_uprobe.py", line 74, in cmd_verify
L0045 ERROR|     return process.run(cmd, shell=True)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1093, in run
L0045 ERROR|     raise CmdError(cmd, sp.result)
L0045 ERROR| avocado.utils.process.CmdError: Command 'perf probe -d \*' failed.
L0045 ERROR| stdout: b''
L0045 ERROR| stderr: b'"*" does not hit any event.\n  Error: Failed to delete events.\n'
L0045 ERROR| additional_info: None

**《Manual Test Log of UID 1》**
[root@sut1 ~]# perf report --input=/var/tmp/tmplp8nfor4
[root@sut1 ~]# perf probe -d \*
"*" does not hit any event.
  Error: Failed to delete events.
[root@sut1 ~]#

**《Debug-Log of UID 2》**
L0658 INFO | Running 'perf record -o /var/tmp/tmp_dd1x9h6 -e probe_uprobe_test:doit__return -- ./uprobe_test'
L0470 DEBUG| [stderr] [ perf record: Woken up 1 times to write data ]
L0470 DEBUG| [stdout] i's addr : 0x7fffecf32900  i : 42
L0470 DEBUG| [stderr] [ perf record: Captured and wrote 0.018 MB /var/tmp/tmp_dd1x9h6 ]
L0740 INFO | Command 'perf record -o /var/tmp/tmp_dd1x9h6 -e probe_uprobe_test:doit__return -- ./uprobe_test' finished with 0 after 1.819728289s
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/perf/perf_uprobe.py", line 107, in test_uprobe_return
L0045 ERROR|     self.fail("perf: perf.data file not created")
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: perf: perf.data file not created
L0046 ERROR|

**《Manual Test Log of UID 2》**
[root@sut1 ~]# perf record -o /var/tmp/tmp_dd1x9h6 -e probe_uprobe_test:doit__return -- ./uprobe_test
event syntax error: 'probe_uprobe_test:doit__return'
                     \___ unknown tracepoint

Error:  File /sys/kernel/tracing/events/probe_uprobe_test/doit__return not found.
Hint:   Perhaps this kernel misses some CONFIG_ setting to enable this feature?.

Run 'perf list' for a list of valid events

 Usage: perf record [<options>] [<command>]
    or: perf record [<options>] -- <command> [<options>]

    -e, --event <event>   event selector. use 'perf list' to list available events
[root@sut1 ~]#

**《Avocado Test Log》**
[20211108-SUT1-Distro-perf_uprobe.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7510137/20211108-SUT1-Distro-perf_uprobe.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
00VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by Gene-Lo** [comment]
After use **Version 90 of Avocado** to test, the result becomes PASS. Thanks!!
