### ISSUE TITLE
After running ltp.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Command 'make' failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2175]
After running ltp.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Command 'make' failed”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/141400551-1bbf8b55-22c6-43ea-af20-af9446853375.png)

**《Debug-Log of UID 6》**
L0470 DEBUG| [stderr] make: error while loading shared libraries: libdl.so.2: failed to map segment from shared object
L0470 DEBUG| [stderr] make[3]: *** [../../../include/mk/generic_trunk_target.inc:108: all] Error 127
L0470 DEBUG| [stderr] make[2]: *** [../../include/mk/generic_trunk_target.inc:108: all] Error 2
L0470 DEBUG| [stderr] make[1]: *** [../include/mk/generic_trunk_target.inc:108: all] Error 2
L0470 DEBUG| [stdout] make[1]: Leaving directory '/var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/testcases'
L0470 DEBUG| [stderr] make: *** [Makefile:106: testcases-all] Error 2
L0740 INFO | Command 'make' finished with 2 after 84.482381362s
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:778
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/generic/ltp.py", line 130, in setUp
L0045 ERROR|     build.make(ltp_dir)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/build.py", line 118, in make
L0045 ERROR|     result = run_make(path, make, extra_args, kwargs)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/build.py", line 84, in run_make
L0045 ERROR|     make_process = process.run(cmd, **process_kwargs)
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1093, in run
L0045 ERROR|     raise CmdError(cmd, sp.result)
L0045 ERROR| avocado.utils.process.CmdError: Command 'make' failed.

**《Manual Test Log》**
[Manual-Test-Log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7524547/Manual-Test-Log.txt)

make[1]: Leaving directory '/var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/testcases'
make -C "tools" \
        -f "/var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/tools/Makefile" all
make[1]: Entering directory '/var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/tools'
make[2]: Nothing to be done for 'all'.
make -C "/var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/lib" -f "/var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/lib/Makefile" all
make[4]: Nothing to be done for 'all'.
make[4]: Nothing to be done for 'all'.
make[1]: Leaving directory '/var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/tools'
make -C "metadata" \
        -f "/var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/metadata/Makefile" all
make[1]: Entering directory '/var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/metadata'
/var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/metadata/parse.sh > ltp.json
make[1]: Leaving directory '/var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/metadata'
if git describe >/dev/null 2>&1; then \
        git describe > "Version"; \
else \
        cp /var/tmp/.avocado-task55uzley_/test-results/tmp_dirveka3a3p/1-LTP.test/ltp-master/VERSION "Version"; \
fi

**《Avocado Test Log》**
[20211111-SUT1.2-Distro-ltp.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7524558/20211111-SUT1.2-Distro-ltp.zip)

**《Note》**
We try to install LTP package and run ltp.py via cmd “./runltp -f syscalls”, but the result is still FAIL.

**<SOP of LTP Installation & Run ltp.py by Manual>**
[SOP of LTP Installation & Run ltp.py by Manual.pdf](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7524553/SOP.of.LTP.Installation.Run.ltp.py.by.Manual.pdf)

**<LTP-Installation-Log>**
[LTP-Installation-Log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7524555/LTP-Installation-Log.txt)

**<ltp_Manual-Test-log>**
[20211111-ltp_Manual-Test-log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7524557/20211111-ltp_Manual-Test-log.txt)

[root@sut4 ~]# cat 20211111-ltp_Manual-Test-log.txt | grep Summary: -A2 | grep failed | sort | uniq
epoll01     0  TINFO  :  Summary: Of 13824 tests, epoll_ctl failed 0 (100% passed).
epoll01     0  TINFO  :  Summary: Of 33 tests, epoll_create failed 0 (100% passed).
failed   0
failed   2
failed   5
failed   6
[root@sut4 ~]#

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot2: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot7: Nvidia T4 Accelerator 16GB PCIe3 x16 LP
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
0VN497 - Seagate Skybolt - HDD 2400GB SAS *3
00VN629 - Micron 5100 PRO - SSD 3840GB SATA *4
00VN329 - Samsung PM1643 - SSD 3840GB SAS *9

**Comment by PraveenPenguin** [comment]
working fine @Gene-Lo please try and facing issue please open a fresh issue
