### ISSUE TITLE
After running pmqa.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: few tests cases failed please check log” and then suspends.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2183]
After running pmqa.py in Rhel8.4 with Avocado (version: 92.0), it shows “FAIL: few tests cases failed please check log” and then suspends.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/141927545-2d8540c0-433b-406e-bf8a-9a43f1ff78ec.png)

**《Debug-Log》**
L0658 INFO | Running 'grep -wF 'fail' /var/tmp/.avocado-task9dn3avos/test-results/1-Pmqa.test/stdout'
L0740 INFO | Command 'grep -wF 'fail' /var/tmp/.avocado-task9dn3avos/test-results/1-Pmqa.test/stdout' finished with 1 after 0.000632950s
L0075 INFO | b''
L0039 ERROR| 
L0042 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
L0045 ERROR| Traceback (most recent call last):
L0045 ERROR|   File "/root/tests/tests/avocado-misc-tests/cpu/pmqa.py", line 76, in test
L0045 ERROR|     self.fail("few tests cases failed please check log")
L0045 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 979, in fail
L0045 ERROR|     raise exceptions.TestFail(message)
L0045 ERROR| avocado.core.exceptions.TestFail: few tests cases failed please check log

**《Manual Test Log》**
[root@sut2 ~]# cd /var/tmp/.avocado-task9dn3avos/test-results/1-Pmqa.test
[root@sut2 1-Pmqa.test]# ls
data  debug.log  output  stderr  stdout  sysinfo  whiteboard
[root@sut2 1-Pmqa.test]# git clone git://git.linaro.org/power/pm-qa.git
Cloning into 'pm-qa'...
remote: Enumerating objects: 1744, done.
remote: Counting objects: 100% (1744/1744), done.
remote: Compressing objects: 100% (879/879), done.
remote: Total 1744 (delta 1265), reused 1080 (delta 797), pack-reused 0
Receiving objects: 100% (1744/1744), 1.07 MiB | 2.03 MiB/s, done.
Resolving deltas: 100% (1265/1265), done.
[root@sut2 1-Pmqa.test]# ls
data  debug.log  output  pm-qa  stderr  stdout  sysinfo  whiteboard
[root@sut2 1-Pmqa.test]# cd pm-qa/
[root@sut2 pm-qa]# ls
Android.mk  COPYING  cpufreq  cpuhotplug  cpuidle  cputopology  include  Makefile  powertop  README  suspend  Switches  Test.mk  thermal  utils  VERSION
[root@sut2 pm-qa]# /bin/git fetch -q -f -u -t git://git.linaro.org/power/pm-qa.git master:master
[root@sut2 pm-qa]# /bin/git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
[root@sut2 pm-qa]# /bin/git log --pretty=format:%H -1
5ead8481bc9b315dfd71e0d34384d1cc7a923007
[root@sut2 pm-qa]# /bin/git describe
pm-qa-v0.5.2-14-g5ead848
[root@sut2 pm-qa]# make -C thermal  run_tests
make: Entering directory '/var/tmp/.avocado-task9dn3avos/test-results/1-Pmqa.test/pm-qa/thermal'
./thermal_sanity.sh
thermal zone is not available. Skipping all tests
thermal_01: skip
thermal_02: skip
thermal_03: skip
thermal_04: skip
thermal_05: skip
thermal_06: skip
make: Leaving directory '/var/tmp/.avocado-task9dn3avos/test-results/1-Pmqa.test/pm-qa/thermal'
[root@sut2 pm-qa]# grep -wF 'fail' /var/tmp/.avocado-task9dn3avos/test-results/1-Pmqa.test/stdout
[root@sut2 pm-qa]#

**《Avocado Test Log》**
[20211114-SUT2.1-CPU-pmqa.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7543670/20211114-SUT2.1-CPU-pmqa.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology (72ASS8G72PSZ-2S6G1) 64GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot2: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot7: Nvidia T4 Accelerator 16GB PCIe3 x16 LP
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
0VN497 - Seagate Skybolt - HDD 2400GB SAS *8

**Comment by PraveenPenguin** [comment]
@Gene-Lo please try all Test using `runner` passing explicitly on all the test  like 

`avocado run  --test-runner runner  <pyfile> `

if the YAML file need to as input  please use below  like command line 

`avocado run  --test-runner runner  <pyfile> -m <yamlfile>`
