### ISSUE TITLE
After running livepatch.py in Rhel8.4 with Avocado (version: 92.0), it shows “ERROR: Command 'make' failed”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2185]
After running livepatch.py in Rhel8.4 with Avocado (version: 92.0) via cmd "avocado run --test-runner runner livepatch.py", it shows “ERROR: Command 'make' failed”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/142790997-71cc5f7d-4ade-42a1-a1dd-de2feaa00609.png)

**《Debug-Log of UID 1》**
02:08:56 INFO | Fetching https://raw.githubusercontent.com/torvalds/linux/master/samples/livepatch/livepatch-sample.c -> /root/avocado/data/cache/by_location/7a183b884fa2e313f5ee9ba0e8bd65fbdd6adf2d/livepatch-sample.c.9728cee2-6c1f-42e9-bf53-a4f4bd8f5366
02:09:01 DEBUG| Retrieved URL "https://raw.githubusercontent.com/torvalds/linux/master/samples/livepatch/livepatch-sample.c": content-length 1370, date: "Thu, 18 Nov 2021 18:09:01 GMT", last-modified: "UNKNOWN"
02:09:01 WARNI| No hash provided. Cannot check the asset file integrity.
02:09:01 INFO | Running 'make'
02:09:01 DEBUG| [stdout] make -C /lib/modules/4.18.0-305.25.1.el8_4.ppc64le/build SUBDIRS=/var/tmp/tmpnmmwgz58 modules
02:09:01 DEBUG| [stderr] make[1]: *** /lib/modules/4.18.0-305.25.1.el8_4.ppc64le/build: No such file or directory.  Stop.
02:09:01 INFO | Command 'make' finished with 2 after 0.005216978s
02:09:01 DEBUG| [stderr] make: *** [Makefile:5: default] Error 2
02:09:01 ERROR| 
02:09:01 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:793
02:09:01 ERROR| Traceback (most recent call last):
02:09:01 ERROR|   File "/root/tests/tests/avocado-misc-tests/kernel/livepatch.py", line 165, in test
02:09:01 ERROR|     self.build_module()
02:09:01 ERROR|   File "/root/tests/tests/avocado-misc-tests/kernel/livepatch.py", line 109, in build_module
02:09:01 ERROR|     if build.make(self.sourcedir) >= 1:
02:09:01 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/build.py", line 118, in make
02:09:01 ERROR|     result = run_make(path, make, extra_args, kwargs)
02:09:01 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/build.py", line 84, in run_make
02:09:01 ERROR|     make_process = process.run(cmd, **process_kwargs)
02:09:01 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1093, in run
02:09:01 ERROR|     raise CmdError(cmd, sp.result)
02:09:01 ERROR| avocado.utils.process.CmdError: Command 'make' failed.
02:09:01 ERROR| stdout: b'make -C /lib/modules/4.18.0-305.25.1.el8_4.ppc64le/build SUBDIRS=/var/tmp/tmpnmmwgz58 modules\n'
02:09:01 ERROR| stderr: b'make[1]: *** /lib/modules/4.18.0-305.25.1.el8_4.ppc64le/build: No such file or directory.  Stop.\nmake: *** [Makefile:5: default] Error 2\n'
02:09:01 ERROR| additional_info: None

**《Manual Test Log》**
**※ There is no file can make.**

[root@sut1 ~]# cd /root/avocado/data/cache/by_location/7a183b884fa2e313f5ee9ba0e8bd65fbdd6adf2d
[root@sut1 7a183b884fa2e313f5ee9ba0e8bd65fbdd6adf2d]# ls
livepatch-sample.c  livepatch-sample.c-CHECKSUM
[root@sut1 7a183b884fa2e313f5ee9ba0e8bd65fbdd6adf2d]# wget https://raw.githubusercontent.com/torvalds/linux/master/samples/livepatch/livepatch-sample.c
--2021-11-22 10:06:48--  https://raw.githubusercontent.com/torvalds/linux/master/samples/livepatch/livepatch-sample.c
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1370 (1.3K) [text/plain]
Saving to: ‘livepatch-sample.c.1’

livepatch-sample.c.1                                     100%[==================================================================================================================================>]   1.34K  --.-KB/s    in 0s

2021-11-22 10:06:53 (54.1 MB/s) - ‘livepatch-sample.c.1’ saved [1370/1370]

[root@sut1 7a183b884fa2e313f5ee9ba0e8bd65fbdd6adf2d]# ls
livepatch-sample.c  livepatch-sample.c.1  livepatch-sample.c-CHECKSUM
[root@sut1 7a183b884fa2e313f5ee9ba0e8bd65fbdd6adf2d]# make
make: *** No targets specified and no makefile found.  Stop.
[root@sut1 7a183b884fa2e313f5ee9ba0e8bd65fbdd6adf2d]#

**《Avocado Test Log》**
[20211118-SUT1.1-Distro-test_runner-livepatch.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7577790/20211118-SUT1.1-Distro-test_runner-livepatch.zip)

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology(18ASF2G72PZ-2G9E1)16GiB x32SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot2: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Marvell QUAD E'NET (2X1 + 2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER SFP+ SR COPPER)
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot7: Nvidia T4 Accelerator 16GB PCIe3 x16 LP
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
00VN329 - Samsung PM1643 - SSD 3840GB SAS *8

**Comment by Gene-Lo** [comment]
After use **Version 90 of Avocado** to test, the result becomes PASS. Thanks!!
