### ISSUE TITLE
After running systemtap.py in Rhel8.4 with Avocado (version: 93.0), it shows “CANCEL: simple systemtap test failed,kernel debuginfo package may be missing”.

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#2186]
After running systemtap.py in Rhel8.4 with Avocado (version: 93.0), it shows “CANCEL: simple systemtap test failed,kernel debuginfo package may be missing”.

**《SOL-Log》**
![SOL-Log](https://user-images.githubusercontent.com/63998174/143221516-ebb55759-c4f7-4f7b-9d23-8571b08300dc.png)

**《Debug-Log》**
17:58:19 INFO | Running 'PATH=%s/bin:$PATH stap -v /bin/true -e 'probe vfs.read { exit() }''
17:58:19 DEBUG| [stderr] Checking "/lib/modules/4.18.0-305.25.1.el8_4.ppc64le/build/.config" failed with error: No such file or directory
17:58:19 INFO | Command 'PATH=%s/bin:$PATH stap -v /bin/true -e 'probe vfs.read { exit() }'' finished with 1 after 0.009866472s
17:58:19 ERROR| 
17:58:19 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:775
17:58:19 ERROR| Traceback (most recent call last):
17:58:19 ERROR|   File "/root/tests/tests/avocado-misc-tests/toolchain/systemtap.py", line 71, in setUp
17:58:19 ERROR|     self.cancel("simple systemtap test failed,"
17:58:19 ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 1012, in cancel
17:58:19 ERROR|     raise exceptions.TestCancel(message)
17:58:19 ERROR| avocado.core.exceptions.TestCancel: simple systemtap test failed,kernel debuginfo package may be missing

**《Test Steps》**
1. Install related packages via cmd: **yum install dejagnu debuginfo kernel-debuginfo kernel -y**
2. Download & install below rpm files:
[root@sut1 dbg_pkg_4.18.0-305.25.1]# rpm -ivh **kernel-debuginfo-common-ppc64le-4.18.0-305.25.1.el8_4.ppc64le.rpm**
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:kernel-debuginfo-common-ppc64le-4################################# [100%]
[root@sut1 dbg_pkg_4.18.0-305.25.1]# rpm -ivh **kernel-debug-devel-4.18.0-305.25.1.el8_4.ppc64le.rpm**
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:kernel-debug-devel-4.18.0-305.25.################################# [100%]
[root@sut1 dbg_pkg_4.18.0-305.25.1]# rpm -ivh **kernel-debug-4.18.0-305.25.1.el8_4.ppc64le.rpm**
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        package kernel-debug-4.18.0-305.25.1.el8_4.ppc64le is already installed
[root@sut1 dbg_pkg_4.18.0-305.25.1]# rpm -ivh **kernel-debug-debuginfo-4.18.0-305.25.1.el8_4.ppc64le.rpm**
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:kernel-debug-debuginfo-4.18.0-305################################# [100%]
[root@sut1 dbg_pkg_4.18.0-305.25.1]# rpm -ivh **kernel-debuginfo-4.18.0-305.25.1.el8_4.ppc64le.rpm**
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:kernel-debuginfo-4.18.0-305.25.1.################################# [100%]
[root@sut1 dbg_pkg_4.18.0-305.25.1]#

3. Run Avocado via cmd: **avocado run --test-runner runner systemtap.py -m systemtap.py.data/systemtap.yaml**

**《Avocado-Test-Log》**
[20211124-SUT1.6-systemtap.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7594871/20211124-SUT1.6-systemtap.zip)

**《Manual-Test-Log》**
[Manual-Test-log.txt](https://github.com/avocado-framework-tests/avocado-misc-tests/files/7594870/Manual-Test-log.txt)

**※Could you kindly illustrate what package we should install to run systemtap.py ? Thanks!!**

**《Configuration》**
[Kernel]
4.18.0-305.25.1.el8_4.ppc64le

[FW Config]
BMC: op940.22.mih-1-0-g41157d8d2e
Pnor: OP9_v2.4.1-4.31-prod

[HW Config]
CPU DD2.3 20 core *2
Micron Technology(18ASF2G72PZ-2G9E1)16GiB x32
SAMSUNG PM985 (MZ1LB960HAJQ-00007) 960GB M.2 x1
PSU ACBEL 2000w *2
Slot1: Mellanox 2-PORT EDR 100Gb IB CONNECTX-5 GEN4 PCIe x16 CAPI CAPABLE LP ADAPTER
Slot2: Emulex LPE16002B-M6-O 2-port 16Gb Fibre Channel card PCIe3 x8 LP
Slot3: Mellanox 2-PORT 10Gb NIC&ROCE ConnectX-4Lx SR/Cu PCIe 3.0 LP CAPABLE ADAPTER
Slot4: Broadcom 2-port 32Gb Fibre Channel adapter PCIe3 x8 LP
Slot5: Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports
Slot6: Mellanox 2-PORT 100Gb ROCE EN CONNECTX-5 GEN4 PCIe x16 LP CAPABLE ADAPTER
Slot7: Marvell 2-PORT E'NET (2X10 10Gb), PCIe Gen 2 X8/SHORT LP CAPABLE (SHINER 10GBase-T)
Slot8: Mellanox 2-PORT 25/10Gb NIC&ROCE SR/Cu PCIe 3.0 (25/10Gb EVERGLADES EN)
Slot9: Broadcom 5719 QP 1G (1G/100M/10M) Network Interface Card PCIe x4 LP
Slot10: Broadcom 9305-16i SAS/SATA HBA PCIe Gen3 x8 LP
00VN628 - Micron 5100 PRO - SSD 1920GB SATA *8
00VN629 - Micron 5100 PRO - SSD 3840GB SATA *8
00VN329 - Samsung PM1643 - SSD 3840GB SAS *8

**Comment by Gene-Lo** [comment]
After we change OS to kernel "4.18.0-305.el8.ppc64le", install related packages, and run systemtap.py again, the result becomes PASS.
