### ISSUE TITLE
While running ndctl.py with Avocado 92.0, traceback messages are seen [(most recent call last):File "/usr/lib64/python3.6/multiprocessing/process.py"..] 

### ISSUE THREAD

**Issue by Geet2** [avocado-framework-tests/avocado-misc-tests#2201]
**Describe the bug**
While running ndctl.py in Rhel with Avocado 92.0, noticed traceback messages [(most recent call last):File "/usr/lib64/python3.6/multiprocessing/process.py"..] 

**Steps to reproduce**
Run the test memory/ndctl.py

**Output** 
```
05:11:41 INFO    : Running Host Tests Suite nvdimm_ndctl_ndctl
05:11:41 INFO    : Running: /usr/local/bin/avocado run --test-runner runner avocado-misc-tests/memory/ndctl.py -m /home/recreate/avocado-fvt-wrapper/tests/avocado-misc-tests/memory/ndctl.py.data/ndctl.yaml --force-job-id 056c6ea2c7abaec340ab41d2ec91ccd696837ce1  --job-results-dir /home/recreate/avocado-fvt-wrapper/results --mux-filter-out /run/mode_types --execution-order tests-per-variant
Fetching asset from /home/recreate/avocado-fvt-wrapper/tests/avocado-misc-tests/memory/ndctl.py:NdctlTest.test_bus_ids
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-92.0-py3.6.egg/avocado/utils/download.py", line 73, in download
    src_file = url_open(url, data=data)
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-92.0-py3.6.egg/avocado/utils/download.py", line 47, in url_open
    result = urlopen(url, data=data, timeout=timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Fetching asset from /home/recreate/avocado-fvt-wrapper/tests/avocado-misc-tests/memory/ndctl.py:NdctlTest.test_dimms
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-92.0-py3.6.egg/avocado/utils/download.py", line 73, in download
    src_file = url_open(url, data=data)
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-92.0-py3.6.egg/avocado/utils/download.py", line 47, in url_open
    result = urlopen(url, data=data, timeout=timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
...
```
Note : The test runs as per expectation, however the above messages are noticed as many times as the no. of CPUs.

**System information :**

    OS : RHEL 8.6 (also seen on RHEL 8.4/RHEL9.0/SLES15SP3)
   
    Avocado version: avocado -v
    Avocado 92.0
   
    Avocado installation method: pip, rpm, github ?
    cloning from github

**Comment by PraveenPenguin** [comment]
@Geet2 are you still facing this issue , if not can you please close this
