### ISSUE TITLE
arcconf_cntl_oper script is skiping the test case due to im-proper checking

### ISSUE THREAD

**Issue by vrbagalkote** [avocado-framework-tests/avocado-misc-tests#250]
Script arcconf_cntl_oper script skipping the FW flash test case due to improper checking.

2017-01-30 04:06:31,040 download         L0062 INFO | Fetching http://9.47.67.137/repo/firmware/RAID/arcconf/tool/Arcconf-2.02-22404.ppc64el.deb -> /usr/share/avocado/data/cache/Arcconf-2.02-22404.ppc64el.deb.NuO94t
2017-01-30 04:06:31,104 process          L0368 INFO | Running 'dpkg -i /usr/share/avocado/data/cache/Arcconf-2.02-22404.ppc64el.deb'
2017-01-30 04:06:31,235 process          L0458 DEBUG| [stdout] Selecting previously unselected package arcconf.
2017-01-30 04:06:31,260 process          L0458 DEBUG| [stdout] (Reading database ... 83162 files and directories currently installed.)
2017-01-30 04:06:31,262 process          L0458 DEBUG| [stdout] Preparing to unpack .../Arcconf-2.02-22404.ppc64el.deb ...
2017-01-30 04:06:31,310 process          L0458 DEBUG| [stdout] Unpacking arcconf (2.02-22404) ...
2017-01-30 04:06:31,638 process          L0458 DEBUG| [stdout] Setting up arcconf (2.02-22404) ...
2017-01-30 04:06:31,731 process          L0458 DEBUG| [stdout]
2017-01-30 04:06:31,734 process          L0458 DEBUG| [stdout] Arcconf is located at /opt/pmcs/cli
2017-01-30 04:06:31,873 process          L0478 INFO | Command 'dpkg -i /usr/share/avocado/data/cache/Arcconf-2.02-22404.ppc64el.deb' finished with 0 after 0.767499923706s
2017-01-30 04:06:31,874 stacktrace       L0038 ERROR|
2017-01-30 04:06:31,874 stacktrace       L0041 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado_framework-45.0-py2.7.egg/avocado/core/test.py:470
2017-01-30 04:06:31,874 stacktrace       L0044 ERROR| Traceback (most recent call last):
2017-01-30 04:06:31,875 stacktrace       L0044 ERROR|   File "/var/lib/libvirt/images/workspace/PMC_Sierra/avocado-misc-tests/io/disk/arcconf/arcconf_cntl_oper.py", line 87, in setUp
2017-01-30 04:06:31,875 stacktrace       L0044 ERROR|     self.skip("Unable to install arcconf")
2017-01-30 04:06:31,875 stacktrace       L0044 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado_framework-45.0-py2.7.egg/avocado/core/test.py", line 672, in skip
2017-01-30 04:06:31,875 stacktrace       L0044 ERROR|     raise exceptions.TestSkipError(message)
2017-01-30 04:06:31,875 stacktrace       L0044 ERROR| TestSkipError: Unable to install arcconf

**Comment by PraveenPenguin** [comment]
@manvanthar can you please have a look in to this ?

**Comment by PraveenPenguin** [comment]
#252

**Comment by nasastry** [comment]
@PraveenPenguin 
Seems "Arcconf" from "Arcconf-2.02-22404.ppc64el.deb" and "arcconf" are not matching. Case sensitivity issue.

\# rpm -q gcc
gcc-6.2.1-2.fc25.ppc64le
\# rpm -q Gcc
package Gcc is not installed

**Comment by PraveenPenguin** [comment]
@nasastry  i think this should not be the case as previously after command run successfully (as process.system return zero) it skip the test i think that is not valid  we  have check like if command fail (not able to install package) will do skip the test

**Comment by PraveenPenguin** [comment]
check this 
https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/io/disk/arcconf/arcconf_cntl_oper.py#L77-L87

**Comment by PraveenPenguin** [comment]
closing this issue as PR #252 merged
