### ISSUE TITLE
Run of FioTest.test on embedded linux device leads to crash of Avocado

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#689]
If the IO/disk tests are run on an embedded linux device with `avocado run ~/avocado-misc-tests-master/io/disk` the test run aborts during execution of FioTest.test which leads to a crash of `Avocado`:

```
 (06/75) /home/rc/avocado-misc-tests-master/io/disk/fiotest.py:FioTest.test: -Unhandled exception in thread started by 
\Error in sys.excepthook:

Original exception was:
-Unhandled exception in thread started by-Avocado crashed unexpectedly: maximum recursion depth exceeded
You can find details in /var/tmp/avocado-traceback-2017-11-09_09:13:55-uPvpy8.log
ERROR (1015.91 s)

Avocado crashed: TestError: Process died before it pushed early test_status.
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/job.py", line 474, in run_tests
    execution_order)

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/runner.py", line 616, in run_suite
    deadline):

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/runner.py", line 398, in run_test
    test_status.wait_for_early_status(proc, 60)

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/runner.py", line 157, in wait_for_early_status
    raise exceptions.TestError("Process died before it pushed "

TestError: Process died before it pushed early test_status.

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
```

The relevant log file content:

```
 (06/75) /home/rc/avocado-misc-tests-master/io/disk/fiotest.py:FioTest.test: -Unhandled exception in thread started by 
\Error in sys.excepthook:

Original exception was:
-Unhandled exception in thread started by-Avocado crashed unexpectedly: maximum recursion depth exceeded
You can find details in /var/tmp/avocado-traceback-2017-11-09_09:13:55-uPvpy8.log
ERROR (1015.91 s)

Avocado crashed: TestError: Process died before it pushed early test_status.
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/job.py", line 474, in run_tests
    execution_order)

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/runner.py", line 616, in run_suite
    deadline):

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/runner.py", line 398, in run_test
    test_status.wait_for_early_status(proc, 60)

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/runner.py", line 157, in wait_for_early_status
    raise exceptions.TestError("Process died before it pushed "

TestError: Process died before it pushed early test_status.

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
rc@rc-visard-02911982:~$ cat /var/tmp/avocado-traceback-2017-11-09_09:13:55-uPvpy8.log
Avocado crashed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 823, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/local/lib/python2.7/dist-packages/avocado/core/output.py", line 640, in write
    self._log_line("%s\n" % data_lines[0])
  File "/usr/local/lib/python2.7/dist-packages/avocado/core/output.py", line 651, in _log_line
    logger.log(self._level, prefix + line)
  File "/usr/lib/python2.7/logging/__init__.py", line 1216, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 942, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
  File "/usr/lib/python2.7/traceback.py", line 13, in _print

(traceback repeated between "line 640" and "line 13" statements a lot of times)

  File "/usr/local/lib/python2.7/dist-packages/avocado/core/output.py", line 640, in write
    self._log_line("%s\n" % data_lines[0])
  File "/usr/local/lib/python2.7/dist-packages/avocado/core/output.py", line 651, in _log_line
    logger.log(self._level, prefix + line)
  File "/usr/lib/python2.7/logging/__init__.py", line 1216, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1262, in _log
    fn, lno, func = self.findCaller()
  File "/usr/lib/python2.7/logging/__init__.py", line 1223, in findCaller
    f = currentframe()
RuntimeError: maximum recursion depth exceeded
```

Could it be required to adjust the "maximum recursion depth" when the test is run on an embedded linux device.

**Comment by narasimhan-v** [comment]
@fkromer Thanks for the report. That would be a good solution to fix this. Would you like to send a pull request to fix that ?

Alternatively, the fiotest needed atleast 2GB of space on the system to create fio job files. Can you change that and retry the test once again, so that we could nail a better fix ?

**Comment by fkromer** [comment]
@narasimhan-v I am working on a PR.

**Comment by fkromer** [comment]
I ran the test in isolation just fine:

```
$ avocado run ./io/disk/fiotest.py:FioTest.test
JOB ID     : a0f0ae07c4df1aaa685022a811771a1f4fd1671f
JOB LOG    : /home/rc/avocado/job-results/job-2017-11-30T15.52-a0f0ae0/job.log
 (1/1) ./io/disk/fiotest.py:FioTest.test: PASS (667.27 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 671.07 s
```

I run the whole test set again to figure out if one/several of the the previous tests consume more than `0,4G` disk space and does not free it during teardown.

```
$ avocado list ./io/disk
INSTRUMENTED ./io/disk/bonnie.py:Bonnie.test
INSTRUMENTED ./io/disk/dbench.py:Dbench.test
INSTRUMENTED ./io/disk/disk_info.py:DiskInfo.test_commands
INSTRUMENTED ./io/disk/disk_info.py:DiskInfo.test
INSTRUMENTED ./io/disk/disktest.py:Disktest.test
INSTRUMENTED ./io/disk/fiotest.py:FioTest.test
```

**Comment by fkromer** [comment]
The test passes when run in this sequence as well:

```
$ avocado run ./io/disk
...
 (06/75) ./io/disk/fiotest.py:FioTest.test: PASS (653.11 s)
```

Probably other tests run before this test/test sequence lead to the failing test. We could add a check of the available disk space. However this is no priority for me and I will not be able to implement this now. Feel free to close this issue...

**Comment by narasimhan-v** [comment]
@fkromer The disk utilisation depends on the size specified in yaml file. So, it is difficult to address that in the test.

Since the test is working, closing the issue.
