### ISSUE TITLE
IO driver test suite test 4 execution leads to an "OSError: [Errno 8] Exec format error"

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#692]
If I run the IO driver test suite with avocado run ~/avocado-misc-tests-master/io/driver (I downloaded and unzipped the test repository into ~/avocado-misc-tests-master) the execution of test 4 leads to an error:

    2017-11-09 10:46:58,746 test             L0965 ERROR| ERROR 4-/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml -> OSError: [Errno 8] Exec format error (/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml)

Seems to related to #691.

The relevant log file content:

```
2017-11-09 10:46:57,487 test             L0381 INFO | START 4-/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml
2017-11-09 10:46:57,494 test             L0402 DEBUG| Test metadata:
2017-11-09 10:46:57,510 test             L0403 DEBUG|   filename: /home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml
2017-11-09 10:46:57,623 process          L0389 INFO | Running '/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml'
2017-11-09 10:46:57,766 stacktrace       L0041 ERROR| 
2017-11-09 10:46:57,770 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:817
2017-11-09 10:46:57,802 stacktrace       L0047 ERROR| Traceback (most recent call last):
2017-11-09 10:46:57,809 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 1113, in test
2017-11-09 10:46:57,815 stacktrace       L0047 ERROR|     self._execute_cmd()
2017-11-09 10:46:57,821 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 1097, in _execute_cmd
2017-11-09 10:46:57,824 stacktrace       L0047 ERROR|     env=test_params)
2017-11-09 10:46:57,838 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 1114, in run
2017-11-09 10:46:57,840 stacktrace       L0047 ERROR|     cmd_result = sp.run(timeout=timeout)
2017-11-09 10:46:57,852 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 638, in run
2017-11-09 10:46:57,854 stacktrace       L0047 ERROR|     self._init_subprocess()
2017-11-09 10:46:57,856 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 402, in _init_subprocess
2017-11-09 10:46:57,859 stacktrace       L0047 ERROR|     raise details
2017-11-09 10:46:57,875 stacktrace       L0047 ERROR| OSError: [Errno 8] Exec format error (/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml)
2017-11-09 10:46:57,877 stacktrace       L0048 ERROR| 
2017-11-09 10:46:57,880 test             L0822 DEBUG| Local variables:
2017-11-09 10:46:58,700 test             L0825 DEBUG|  -> self <class 'avocado.core.test.SimpleTest'>: 4-/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml
2017-11-09 10:46:58,707 test             L0278 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, file)
2017-11-09 10:46:58,725 test             L0278 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, file)
2017-11-09 10:46:58,729 test             L0950 ERROR| Traceback (most recent call last):

2017-11-09 10:46:58,731 test             L0950 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 888, in _run_avocado
    raise test_exception

2017-11-09 10:46:58,744 test             L0950 ERROR| OSError: [Errno 8] Exec format error (/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml)

2017-11-09 10:46:58,746 test             L0965 ERROR| ERROR 4-/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml -> OSError: [Errno 8] Exec format error (/home/rc/avocado-misc-tests-master/io/driver/driver_bind_test.py.data/driver_bind_test.yaml)
2017-11-09 10:46:58,748 test             L0954 INFO | 
2017-11-09 10:47:00,096 sysinfo          L0111 DEBUG| Not logging /proc/pci (file does not exist)
2017-11-09 10:47:00,231 sysinfo          L0109 DEBUG| Not logging /proc/slabinfo (lack of permissions)
2017-11-09 10:47:00,512 sysinfo          L0111 DEBUG| Not logging /sys/kernel/debug/sched_features (file does not exist)
2017-11-09 10:47:01,573 job              L0478 INFO | Test results available in /home/rc/avocado/job-results/job-2017-11-09T10.46-adb194e
```

**Comment by narasimhan-v** [comment]
This is also fixed via #711
