### ISSUE TITLE
Is NStress.test suiteable for other systems than IBM AIX?

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#727]
The test `generic/nstress.py:NStress.test` fails if run on Ubuntu + ARMv7 arch. Is this test suitable for non-AIX systems? ( [IBM developerworks - nstress](https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/Power+Systems/page/nstress) / [wikipedia - IBM AIX](https://en.wikipedia.org/wiki/IBM_AIX))

```
$ avocado run generic/nstress.py:NStress.test
JOB ID     : 37fe342a01080cc3f9b14ea5c5f72850deb488b9
JOB LOG    : /home/rc/avocado/job-results/job-2017-12-01T11.21-37fe342/job.log
 (1/1) generic/nstress.py:NStress.test: FAIL (1.17 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 4.55 s
rc@rc-visard-02911982:~/avocado-misc-tests$ cat /home/rc/avocado/job-results/job-2017-12-01T11.21-37fe342/job.log
2017-12-01 11:21:27,038 extension        L0189 DEBUG| found extension EntryPoint.parse('journal = avocado.plugins.journal:JournalResult')
2017-12-01 11:21:27,041 extension        L0189 DEBUG| found extension EntryPoint.parse('tap = avocado.plugins.tap:TAPResult')
2017-12-01 11:21:27,044 extension        L0189 DEBUG| found extension EntryPoint.parse('human = avocado.plugins.human:Human')
2017-12-01 11:21:27,061 extension        L0189 DEBUG| found extension EntryPoint.parse('teststmpdir = avocado.plugins.teststmpdir:TestsTmpDir')
2017-12-01 11:21:27,069 extension        L0189 DEBUG| found extension EntryPoint.parse('jobscripts = avocado.plugins.jobscripts:JobScripts')
2017-12-01 11:21:27,076 extension        L0189 DEBUG| found extension EntryPoint.parse('human = avocado.plugins.human:HumanJob')
2017-12-01 11:21:27,127 sysinfo          L0415 INFO | Commands configured by file: /etc/avocado/sysinfo/commands
2017-12-01 11:21:27,130 sysinfo          L0426 INFO | Files configured by file: /etc/avocado/sysinfo/files
2017-12-01 11:21:27,133 sysinfo          L0446 INFO | Profilers configured by file: /etc/avocado/sysinfo/profilers
2017-12-01 11:21:27,135 sysinfo          L0454 INFO | Profiler disabled
2017-12-01 11:21:27,216 sysinfo          L0266 DEBUG| Journalctl collection failed: [Errno 2] No such file or directory (journalctl --quiet --lines 1 --output json)
2017-12-01 11:21:27,219 job              L0327 INFO | Command line: /usr/local/bin/avocado run generic/nstress.py:NStress.test
2017-12-01 11:21:27,221 job              L0328 INFO | 
2017-12-01 11:21:27,282 job              L0357 INFO | Avocado version: 55.0
2017-12-01 11:21:27,285 job              L0358 INFO | 
2017-12-01 11:21:27,286 job              L0362 INFO | Config files read (in order):
2017-12-01 11:21:27,288 job              L0364 INFO | /etc/avocado/avocado.conf
2017-12-01 11:21:27,289 job              L0364 INFO | /etc/avocado/conf.d/gdb.conf
2017-12-01 11:21:27,292 job              L0364 INFO | /home/rc/.config/avocado/avocado.conf
2017-12-01 11:21:27,293 job              L0369 INFO | 
2017-12-01 11:21:27,294 job              L0371 INFO | Avocado config:
2017-12-01 11:21:27,312 job              L0380 INFO | Section.Key                             Value
2017-12-01 11:21:27,313 job              L0380 INFO | datadir.paths.base_dir                  /var/lib/avocado
2017-12-01 11:21:27,315 job              L0380 INFO | datadir.paths.test_dir                  /usr/share/avocado/tests
2017-12-01 11:21:27,317 job              L0380 INFO | datadir.paths.data_dir                  /var/lib/avocado/data
2017-12-01 11:21:27,318 job              L0380 INFO | datadir.paths.logs_dir                  ~/avocado/job-results
2017-12-01 11:21:27,319 job              L0380 INFO | sysinfo.collect.enabled                 True
2017-12-01 11:21:27,321 job              L0380 INFO | sysinfo.collect.commands_timeout        -1
2017-12-01 11:21:27,323 job              L0380 INFO | sysinfo.collect.installed_packages      False
2017-12-01 11:21:27,324 job              L0380 INFO | sysinfo.collect.profiler                False
2017-12-01 11:21:27,325 job              L0380 INFO | sysinfo.collect.locale                  C
2017-12-01 11:21:27,327 job              L0380 INFO | sysinfo.collect.per_test                False
2017-12-01 11:21:27,328 job              L0380 INFO | sysinfo.collectibles.commands           /etc/avocado/sysinfo/commands
2017-12-01 11:21:27,329 job              L0380 INFO | sysinfo.collectibles.files              /etc/avocado/sysinfo/files
2017-12-01 11:21:27,331 job              L0380 INFO | sysinfo.collectibles.profilers          /etc/avocado/sysinfo/profilers
2017-12-01 11:21:27,333 job              L0380 INFO | runner.output.colored                   True
2017-12-01 11:21:27,335 job              L0380 INFO | runner.output.utf8                      
2017-12-01 11:21:27,336 job              L0380 INFO | remoter.behavior.reject_unknown_hosts   False
2017-12-01 11:21:27,338 job              L0380 INFO | remoter.behavior.disable_known_hosts    False
2017-12-01 11:21:27,340 job              L0380 INFO | job.output.loglevel                     debug
2017-12-01 11:21:27,342 job              L0380 INFO | restclient.connection.hostname          localhost
2017-12-01 11:21:27,343 job              L0380 INFO | restclient.connection.port              9405
2017-12-01 11:21:27,345 job              L0380 INFO | restclient.connection.username          
2017-12-01 11:21:27,347 job              L0380 INFO | restclient.connection.password          
2017-12-01 11:21:27,349 job              L0380 INFO | plugins.disable                         []
2017-12-01 11:21:27,350 job              L0380 INFO | plugins.skip_broken_plugin_notification []
2017-12-01 11:21:27,352 job              L0380 INFO | plugins.loaders                         ['file', '@DEFAULT']
2017-12-01 11:21:27,353 job              L0380 INFO | gdb.paths.gdb                           /usr/bin/gdb
2017-12-01 11:21:27,355 job              L0380 INFO | gdb.paths.gdbserver                     /usr/bin/gdbserver
2017-12-01 11:21:27,356 job              L0381 INFO | 
2017-12-01 11:21:27,358 job              L0384 INFO | Avocado Data Directories:
2017-12-01 11:21:27,359 job              L0385 INFO | 
2017-12-01 11:21:27,366 job              L0386 INFO | base     /home/rc/avocado
2017-12-01 11:21:27,368 job              L0387 INFO | tests    /usr/share/avocado/tests
2017-12-01 11:21:27,374 job              L0388 INFO | data     /home/rc/avocado/data
2017-12-01 11:21:27,376 job              L0389 INFO | logs     /home/rc/avocado/job-results/job-2017-12-01T11.21-37fe342
2017-12-01 11:21:27,378 job              L0390 INFO | 
2017-12-01 11:21:27,381 job              L0396 INFO | No variants available, using defaults only
2017-12-01 11:21:27,382 job              L0396 INFO | 
2017-12-01 11:21:27,384 job              L0396 INFO | Variant :    /
2017-12-01 11:21:27,386 job              L0400 INFO | Temporary dir: /var/tmp/avocado_ysJFfS
2017-12-01 11:21:27,387 job              L0401 INFO | 
2017-12-01 11:21:27,388 job              L0319 INFO | Job ID: 37fe342a01080cc3f9b14ea5c5f72850deb488b9
2017-12-01 11:21:27,390 job              L0322 INFO | 
2017-12-01 11:21:28,038 sysinfo          L0111 DEBUG| Not logging /proc/pci (file does not exist)
2017-12-01 11:21:28,110 sysinfo          L0109 DEBUG| Not logging /proc/slabinfo (lack of permissions)
2017-12-01 11:21:28,264 sysinfo          L0111 DEBUG| Not logging /sys/kernel/debug/sched_features (file does not exist)
2017-12-01 11:21:28,778 sysinfo          L0415 INFO | Commands configured by file: /etc/avocado/sysinfo/commands
2017-12-01 11:21:28,787 sysinfo          L0426 INFO | Files configured by file: /etc/avocado/sysinfo/files
2017-12-01 11:21:28,790 sysinfo          L0446 INFO | Profilers configured by file: /etc/avocado/sysinfo/profilers
2017-12-01 11:21:28,792 sysinfo          L0454 INFO | Profiler disabled
2017-12-01 11:21:28,891 sysinfo          L0266 DEBUG| Journalctl collection failed: [Errno 2] No such file or directory (journalctl --quiet --lines 1 --output json)
2017-12-01 11:21:28,903 varianter        L0116 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
2017-12-01 11:21:28,904 test             L0381 INFO | START 1-generic/nstress.py:NStress.test
2017-12-01 11:21:28,911 test             L0402 DEBUG| Test metadata:
2017-12-01 11:21:28,914 test             L0403 DEBUG|   filename: /home/rc/avocado-misc-tests/generic/nstress.py
2017-12-01 11:21:29,075 varianter        L0116 DEBUG| PARAMS (key=tar_ball_ubuntu, path=*, default=nstress_Ubuntu1410_ppc64_Nov_2015.tar) => 'nstress_Ubuntu1410_ppc64_Nov_2015.tar'
2017-12-01 11:21:29,191 varianter        L0116 DEBUG| PARAMS (key=duration, path=*, default=300) => 300
2017-12-01 11:21:29,198 process          L0389 INFO | Running '/usr/bin/sudo -n -s ./nmem -m 250 -s 300'
2017-12-01 11:21:29,453 process          L0479 DEBUG| [stderr] /bin/bash: ./nmem: cannot execute binary file: Exec format error
2017-12-01 11:21:29,511 process          L0499 INFO | Command '/usr/bin/sudo -n -s ./nmem -m 250 -s 300' finished with 126 after 0.274646043777s
2017-12-01 11:21:29,515 nstress          L0031 INFO | ./nmem -m 250 -s 300 test failed
2017-12-01 11:21:29,522 process          L0389 INFO | Running '/usr/bin/sudo -n -s ./nmem64 -m 2047 -s 300'
2017-12-01 11:21:29,768 process          L0479 DEBUG| [stderr] /bin/bash: ./nmem64: cannot execute binary file: Exec format error
2017-12-01 11:21:29,826 process          L0499 INFO | Command '/usr/bin/sudo -n -s ./nmem64 -m 2047 -s 300' finished with 126 after 0.267843961716s
2017-12-01 11:21:29,829 nstress          L0031 INFO | ./nmem64 -m 2047 -s 300 test failed
2017-12-01 11:21:29,832 stacktrace       L0041 ERROR| 
2017-12-01 11:21:29,834 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:817
2017-12-01 11:21:29,844 stacktrace       L0047 ERROR| Traceback (most recent call last):
2017-12-01 11:21:29,846 stacktrace       L0047 ERROR|   File "/home/rc/avocado-misc-tests/generic/nstress.py", line 54, in test
2017-12-01 11:21:29,848 stacktrace       L0047 ERROR|     self.fail("nstress test failed")
2017-12-01 11:21:29,851 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 983, in fail
2017-12-01 11:21:29,853 stacktrace       L0047 ERROR|     raise exceptions.TestFail(message)
2017-12-01 11:21:29,856 stacktrace       L0047 ERROR| TestFail: nstress test failed
2017-12-01 11:21:29,858 stacktrace       L0048 ERROR| 
2017-12-01 11:21:29,861 test             L0822 DEBUG| Local variables:
2017-12-01 11:21:30,213 test             L0825 DEBUG|  -> self <class 'nstress.NStress'>: 1-generic/nstress.py:NStress.test
2017-12-01 11:21:30,222 test             L0278 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2017-12-01 11:21:30,227 test             L0278 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2017-12-01 11:21:30,230 test             L0965 ERROR| FAIL 1-generic/nstress.py:NStress.test -> TestFail: nstress test failed
2017-12-01 11:21:30,232 test             L0954 INFO | 
2017-12-01 11:21:30,953 sysinfo          L0111 DEBUG| Not logging /proc/pci (file does not exist)
2017-12-01 11:21:31,026 sysinfo          L0109 DEBUG| Not logging /proc/slabinfo (lack of permissions)
2017-12-01 11:21:31,183 sysinfo          L0111 DEBUG| Not logging /sys/kernel/debug/sched_features (file does not exist)
2017-12-01 11:21:31,641 job              L0478 INFO | Test results available in /home/rc/avocado/job-results/job-2017-12-01T11.21-37fe342
```

**Comment by PraveenPenguin** [comment]
@Pavithra1602 can you please help here

**Comment by PraveenPenguin** [comment]
@Pavithra1602 thanks

**Comment by PraveenPenguin** [comment]
closing this issue as #885 fix the issue
