### ISSUE TITLE
Package_check.test fails on ARMv7

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#728]
When the test `generic/packages.py:Package_check.test` is executed on system with ARMv7 cpu it fails. Seems like it is specific to powerpc (`job_generic_repo_tests.log` is the log file of the whole test suite `generic`):

```
$ cat job_generic_repo_tests.log | grep -B 34 "| FAIL 21"
2017-11-09 18:09:10,328 test             L0381 INFO | START 21-/home/rc/avocado-misc-tests-master/generic/packages.py:Package_check.test
2017-11-09 18:09:10,329 test             L0402 DEBUG| Test metadata:
2017-11-09 18:09:10,329 test             L0403 DEBUG|   filename: /home/rc/avocado-misc-tests-master/generic/packages.py
2017-11-09 18:09:10,351 varianter        L0116 DEBUG| PARAMS (key=packages, path=*, default=['powerpc-utils', 'ppc64-diag', 'lsvpd']) => ['powerpc-utils', 'ppc64-diag', 'lsvpd']
2017-11-09 18:09:10,353 varianter        L0116 DEBUG| PARAMS (key=packages_ubuntu, path=*, default=['librtas2']) => ['librtas2']
2017-11-09 18:09:10,353 process          L0389 INFO | Running 'apt-mark showauto powerpc-utils'
2017-11-09 18:09:10,853 process          L0499 INFO | Command 'apt-mark showauto powerpc-utils' finished with 0 after 0.495363950729s
2017-11-09 18:09:10,854 packages         L0059 INFO | powerpc-utils package is not installed by default
2017-11-09 18:09:10,854 process          L0389 INFO | Running 'apt-mark showauto ppc64-diag'
2017-11-09 18:09:11,366 process          L0499 INFO | Command 'apt-mark showauto ppc64-diag' finished with 0 after 0.507091999054s
2017-11-09 18:09:11,367 packages         L0059 INFO | ppc64-diag package is not installed by default
2017-11-09 18:09:11,367 process          L0389 INFO | Running 'apt-mark showauto lsvpd'
2017-11-09 18:09:11,867 process          L0499 INFO | Command 'apt-mark showauto lsvpd' finished with 0 after 0.495292901993s
2017-11-09 18:09:11,867 packages         L0059 INFO | lsvpd package is not installed by default
2017-11-09 18:09:11,868 process          L0389 INFO | Running 'apt-mark showauto librtas2'
2017-11-09 18:09:12,369 process          L0499 INFO | Command 'apt-mark showauto librtas2' finished with 0 after 0.49556684494s
2017-11-09 18:09:12,370 packages         L0059 INFO | librtas2 package is not installed by default
2017-11-09 18:09:12,370 stacktrace       L0041 ERROR| 
2017-11-09 18:09:12,370 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:817
2017-11-09 18:09:12,371 stacktrace       L0047 ERROR| Traceback (most recent call last):
2017-11-09 18:09:12,372 stacktrace       L0047 ERROR|   File "/home/rc/avocado-misc-tests-master/generic/packages.py", line 68, in test
2017-11-09 18:09:12,372 stacktrace       L0047 ERROR|     self.fail("%s package(s) not installed by default" % is_fail)
2017-11-09 18:09:12,372 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 983, in fail
2017-11-09 18:09:12,372 stacktrace       L0047 ERROR|     raise exceptions.TestFail(message)
2017-11-09 18:09:12,372 stacktrace       L0047 ERROR| TestFail: 4 package(s) not installed by default
2017-11-09 18:09:12,373 stacktrace       L0048 ERROR| 
2017-11-09 18:09:12,373 test             L0822 DEBUG| Local variables:
2017-11-09 18:09:12,408 test             L0825 DEBUG|  -> packages_ubuntu <type 'list'>: ['librtas2']
2017-11-09 18:09:12,409 test             L0825 DEBUG|  -> is_fail <type 'int'>: 4
2017-11-09 18:09:12,409 test             L0825 DEBUG|  -> self <class 'packages.Package_check'>: 21-/home/rc/avocado-misc-tests-master/generic/packages.py:Package_check.test
2017-11-09 18:09:12,409 test             L0825 DEBUG|  -> dist <class 'avocado.utils.distro.LinuxDistro'>: <LinuxDistro: name=Ubuntu, version=14, release=04, arch=armv7l>
2017-11-09 18:09:12,409 test             L0825 DEBUG|  -> package <type 'str'>: librtas2
2017-11-09 18:09:12,410 test             L0278 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2017-11-09 18:09:12,410 test             L0278 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2017-11-09 18:09:12,411 test             L0965 ERROR| FAIL 21-/home/rc/avocado-misc-tests-master/generic/packages.py:Package_check.test -> TestFail: 4 package(s) not installed by default
```

**Comment by PraveenPenguin** [comment]
@fkromer thanks for reporting ,  Would you like to send a pull request to fix this ?

**Comment by fkromer** [comment]
@PraveenPenguin I am planning to PR for a lot of issues. W.r.t. workflow it is faster to analyse all failing tests first and fix them together later. However it depends on the scheduling of my tasks if I will be able to actually PR in the near future.

**Comment by PraveenPenguin** [comment]
@fkromer any update on this

**Comment by fkromer** [comment]
@PraveenPenguin Unfortunately no. But can be closed from my side. (It is not solved yet but I won't have time to go continue with this and it has low prio for me.)

**Comment by PraveenPenguin** [comment]
@fkromer sure i will send PR for fixing this issue
