### ISSUE TITLE
Test HWInfo.test has status ERROR on Ubuntu 14.04

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#736]
The test `generic/hwinfo.py:HWInfo.test` depends on `hwinfo` [which is not available for Ubuntu 14.04](https://askubuntu.com/questions/662971/hwinfo-replaced-with-what/662973#662973) out of the box. When executed the test status is `ERROR`.

**Comment by PraveenPenguin** [comment]
@fkromer thanks for report , i think this test will skip on this condition  what you say ?

**Comment by fkromer** [comment]
@PraveenPenguin Actual output:

```
$ sudo avocado run generic/hwinfo.py
JOB ID     : e4d53fb1ddccf0eb3a78e33a49f02ec1da533f8e
JOB LOG    : /home/rc/avocado/job-results/job-2017-12-05T10.33-e4d53fb/job.log
 (1/1) generic/hwinfo.py:Hwinfo.test: ERROR (10.24 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 14.75 s
```

Log file content:

```
$ cat /home/rc/avocado/job-results/job-2017-12-05T10.33-e4d53fb/job.log
2017-12-05 10:33:48,287 extension        L0189 DEBUG| found extension EntryPoint.parse('journal = avocado.plugins.journal:JournalResult')
2017-12-05 10:33:48,290 extension        L0189 DEBUG| found extension EntryPoint.parse('tap = avocado.plugins.tap:TAPResult')
2017-12-05 10:33:48,292 extension        L0189 DEBUG| found extension EntryPoint.parse('human = avocado.plugins.human:Human')
2017-12-05 10:33:48,307 extension        L0189 DEBUG| found extension EntryPoint.parse('teststmpdir = avocado.plugins.teststmpdir:TestsTmpDir')
2017-12-05 10:33:48,314 extension        L0189 DEBUG| found extension EntryPoint.parse('jobscripts = avocado.plugins.jobscripts:JobScripts')
2017-12-05 10:33:48,320 extension        L0189 DEBUG| found extension EntryPoint.parse('human = avocado.plugins.human:HumanJob')
2017-12-05 10:33:48,388 sysinfo          L0415 INFO | Commands configured by file: /etc/avocado/sysinfo/commands
2017-12-05 10:33:48,399 sysinfo          L0426 INFO | Files configured by file: /etc/avocado/sysinfo/files
2017-12-05 10:33:48,412 sysinfo          L0446 INFO | Profilers configured by file: /etc/avocado/sysinfo/profilers
2017-12-05 10:33:48,414 sysinfo          L0454 INFO | Profiler disabled
2017-12-05 10:33:48,584 sysinfo          L0266 DEBUG| Journalctl collection failed: [Errno 2] No such file or directory (journalctl --quiet --lines 1 --output json)
2017-12-05 10:33:48,587 job              L0327 INFO | Command line: /usr/local/bin/avocado run generic/hwinfo.py
2017-12-05 10:33:48,588 job              L0328 INFO | 
2017-12-05 10:33:48,662 job              L0357 INFO | Avocado version: 55.0
2017-12-05 10:33:48,665 job              L0358 INFO | 
2017-12-05 10:33:48,667 job              L0362 INFO | Config files read (in order):
2017-12-05 10:33:48,668 job              L0364 INFO | /etc/avocado/avocado.conf
2017-12-05 10:33:48,671 job              L0364 INFO | /etc/avocado/conf.d/gdb.conf
2017-12-05 10:33:48,672 job              L0364 INFO | /home/rc/.config/avocado/avocado.conf
2017-12-05 10:33:48,674 job              L0369 INFO | 
2017-12-05 10:33:48,676 job              L0371 INFO | Avocado config:
2017-12-05 10:33:48,692 job              L0380 INFO | Section.Key                             Value
2017-12-05 10:33:48,694 job              L0380 INFO | datadir.paths.base_dir                  /var/lib/avocado
2017-12-05 10:33:48,696 job              L0380 INFO | datadir.paths.test_dir                  /usr/share/avocado/tests
2017-12-05 10:33:48,697 job              L0380 INFO | datadir.paths.data_dir                  /var/lib/avocado/data
2017-12-05 10:33:48,699 job              L0380 INFO | datadir.paths.logs_dir                  ~/avocado/job-results
2017-12-05 10:33:48,701 job              L0380 INFO | sysinfo.collect.enabled                 True
2017-12-05 10:33:48,703 job              L0380 INFO | sysinfo.collect.commands_timeout        -1
2017-12-05 10:33:48,704 job              L0380 INFO | sysinfo.collect.installed_packages      False
2017-12-05 10:33:48,706 job              L0380 INFO | sysinfo.collect.profiler                False
2017-12-05 10:33:48,707 job              L0380 INFO | sysinfo.collect.locale                  C
2017-12-05 10:33:48,708 job              L0380 INFO | sysinfo.collect.per_test                False
2017-12-05 10:33:48,710 job              L0380 INFO | sysinfo.collectibles.commands           /etc/avocado/sysinfo/commands
2017-12-05 10:33:48,711 job              L0380 INFO | sysinfo.collectibles.files              /etc/avocado/sysinfo/files
2017-12-05 10:33:48,713 job              L0380 INFO | sysinfo.collectibles.profilers          /etc/avocado/sysinfo/profilers
2017-12-05 10:33:48,714 job              L0380 INFO | runner.output.colored                   True
2017-12-05 10:33:48,715 job              L0380 INFO | runner.output.utf8                      
2017-12-05 10:33:48,717 job              L0380 INFO | remoter.behavior.reject_unknown_hosts   False
2017-12-05 10:33:48,719 job              L0380 INFO | remoter.behavior.disable_known_hosts    False
2017-12-05 10:33:48,720 job              L0380 INFO | job.output.loglevel                     debug
2017-12-05 10:33:48,722 job              L0380 INFO | restclient.connection.hostname          localhost
2017-12-05 10:33:48,723 job              L0380 INFO | restclient.connection.port              9405
2017-12-05 10:33:48,725 job              L0380 INFO | restclient.connection.username          
2017-12-05 10:33:48,726 job              L0380 INFO | restclient.connection.password          
2017-12-05 10:33:48,727 job              L0380 INFO | plugins.disable                         []
2017-12-05 10:33:48,729 job              L0380 INFO | plugins.skip_broken_plugin_notification []
2017-12-05 10:33:48,731 job              L0380 INFO | plugins.loaders                         ['file', '@DEFAULT']
2017-12-05 10:33:48,732 job              L0380 INFO | gdb.paths.gdb                           /usr/bin/gdb
2017-12-05 10:33:48,734 job              L0380 INFO | gdb.paths.gdbserver                     /usr/bin/gdbserver
2017-12-05 10:33:48,735 job              L0381 INFO | 
2017-12-05 10:33:48,737 job              L0384 INFO | Avocado Data Directories:
2017-12-05 10:33:48,738 job              L0385 INFO | 
2017-12-05 10:33:48,743 job              L0386 INFO | base     /var/lib/avocado
2017-12-05 10:33:48,745 job              L0387 INFO | tests    /usr/share/avocado/tests
2017-12-05 10:33:48,749 job              L0388 INFO | data     /var/lib/avocado/data
2017-12-05 10:33:48,751 job              L0389 INFO | logs     /home/rc/avocado/job-results/job-2017-12-05T10.33-e4d53fb
2017-12-05 10:33:48,752 job              L0390 INFO | 
2017-12-05 10:33:48,755 job              L0396 INFO | No variants available, using defaults only
2017-12-05 10:33:48,756 job              L0396 INFO | 
2017-12-05 10:33:48,757 job              L0396 INFO | Variant :    /
2017-12-05 10:33:48,759 job              L0400 INFO | Temporary dir: /var/tmp/avocado_fv_wYb
2017-12-05 10:33:48,760 job              L0401 INFO | 
2017-12-05 10:33:48,762 job              L0319 INFO | Job ID: e4d53fb1ddccf0eb3a78e33a49f02ec1da533f8e
2017-12-05 10:33:48,764 job              L0322 INFO | 
2017-12-05 10:33:49,967 sysinfo          L0111 DEBUG| Not logging /proc/pci (file does not exist)
2017-12-05 10:33:50,866 sysinfo          L0415 INFO | Commands configured by file: /etc/avocado/sysinfo/commands
2017-12-05 10:33:50,877 sysinfo          L0426 INFO | Files configured by file: /etc/avocado/sysinfo/files
2017-12-05 10:33:50,880 sysinfo          L0446 INFO | Profilers configured by file: /etc/avocado/sysinfo/profilers
2017-12-05 10:33:50,883 sysinfo          L0454 INFO | Profiler disabled
2017-12-05 10:33:50,968 sysinfo          L0266 DEBUG| Journalctl collection failed: [Errno 2] No such file or directory (journalctl --quiet --lines 1 --output json)
2017-12-05 10:33:50,980 varianter        L0116 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
2017-12-05 10:33:50,982 test             L0381 INFO | START 1-generic/hwinfo.py:Hwinfo.test
2017-12-05 10:33:50,989 test             L0402 DEBUG| Test metadata:
2017-12-05 10:33:50,991 test             L0403 DEBUG|   filename: /home/rc/PraveenPenguin/avocado-misc-tests/generic/hwinfo.py
2017-12-05 10:33:51,372 software_manager L0692 DEBUG| apt-get version: 1.0.1ubuntu2
2017-12-05 10:33:51,401 process          L0389 INFO | Running '/usr/bin/dpkg -s gdebi-core'
2017-12-05 10:33:52,665 process          L0479 DEBUG| [stdout] Package: gdebi-core
2017-12-05 10:33:52,671 process          L0479 DEBUG| [stdout] Status: install ok installed
2017-12-05 10:33:52,675 process          L0479 DEBUG| [stdout] Priority: optional
2017-12-05 10:33:52,683 process          L0499 INFO | Command '/usr/bin/dpkg -s gdebi-core' finished with 0 after 1.20065593719s
2017-12-05 10:33:52,687 process          L0479 DEBUG| [stdout] Section: admin
2017-12-05 10:33:52,692 process          L0479 DEBUG| [stdout] Installed-Size: 132
2017-12-05 10:33:52,696 process          L0479 DEBUG| [stdout] Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
2017-12-05 10:33:52,726 process          L0479 DEBUG| [stdout] Architecture: all
2017-12-05 10:33:52,734 process          L0479 DEBUG| [stdout] Source: gdebi
2017-12-05 10:33:52,754 process          L0479 DEBUG| [stdout] Version: 0.9.5.3ubuntu3
2017-12-05 10:33:52,757 process          L0479 DEBUG| [stdout] Depends: python3:any (>= 3.3.2-2~), python3-apt, python3-debian, file
2017-12-05 10:33:52,774 process          L0479 DEBUG| [stdout] Suggests: xz-utils | xz-lzma
2017-12-05 10:33:52,778 process          L0479 DEBUG| [stdout] Description: simple tool to install deb files
2017-12-05 10:33:52,799 process          L0479 DEBUG| [stdout]  gdebi lets you install local deb packages resolving and installing
2017-12-05 10:33:52,804 process          L0479 DEBUG| [stdout]  its dependencies. apt does the same, but only for remote (http, ftp)
2017-12-05 10:33:52,808 process          L0479 DEBUG| [stdout]  located packages.
2017-12-05 10:33:52,824 process          L0479 DEBUG| [stdout]  .
2017-12-05 10:33:52,828 process          L0479 DEBUG| [stdout]  This package contains the libraries and command-line utility.
2017-12-05 10:33:52,835 process          L0479 DEBUG| [stdout] Original-Maintainer: Ubuntu Developers <ubuntu-dev-team@lists.alioth.debian.org>
2017-12-05 10:33:52,849 process          L0389 INFO | Running '/usr/bin/dpkg -s hwinfo'
2017-12-05 10:33:53,859 process          L0479 DEBUG| [stderr] dpkg-query: package 'hwinfo' is not installed and no information is available
2017-12-05 10:33:53,866 process          L0479 DEBUG| [stderr] Use dpkg --info (= dpkg-deb --info) to examine archive files,
2017-12-05 10:33:53,871 process          L0479 DEBUG| [stderr] and dpkg --contents (= dpkg-deb --contents) to list their contents.
2017-12-05 10:33:53,881 process          L0499 INFO | Command '/usr/bin/dpkg -s hwinfo' finished with 1 after 0.993000030518s
2017-12-05 10:33:53,893 process          L0389 INFO | Running '/usr/bin/apt-get --yes --allow-unauthenticated -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install hwinfo'
2017-12-05 10:33:54,199 process          L0479 DEBUG| [stdout] Reading package lists...
2017-12-05 10:33:59,063 process          L0479 DEBUG| [stdout] Building dependency tree...
2017-12-05 10:33:59,157 process          L0479 DEBUG| [stdout] Reading state information...
2017-12-05 10:34:01,254 process          L0479 DEBUG| [stdout] Package hwinfo is not available, but is referred to by another package.
2017-12-05 10:34:01,258 process          L0479 DEBUG| [stdout] This may mean that the package is missing, has been obsoleted, or
2017-12-05 10:34:01,262 process          L0479 DEBUG| [stdout] is only available from another source
2017-12-05 10:34:01,287 process          L0479 DEBUG| [stdout] 
2017-12-05 10:34:01,296 process          L0479 DEBUG| [stderr] E: Package 'hwinfo' has no installation candidate
2017-12-05 10:34:01,310 process          L0499 INFO | Command '/usr/bin/apt-get --yes --allow-unauthenticated -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install hwinfo' finished with 100 after 7.35837292671s
2017-12-05 10:34:01,315 stacktrace       L0041 ERROR| 
2017-12-05 10:34:01,319 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:797
2017-12-05 10:34:01,337 stacktrace       L0047 ERROR| Traceback (most recent call last):
2017-12-05 10:34:01,339 stacktrace       L0047 ERROR|   File "/home/rc/PraveenPenguin/avocado-misc-tests/generic/hwinfo.py", line 44, in setUp
2017-12-05 10:34:01,341 stacktrace       L0047 ERROR|     self.error("Fail to install hwinfo required for this test.")
2017-12-05 10:34:01,353 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 995, in error
2017-12-05 10:34:01,355 stacktrace       L0047 ERROR|     raise exceptions.TestError(message)
2017-12-05 10:34:01,364 stacktrace       L0047 ERROR| TestError: Fail to install hwinfo required for this test.
2017-12-05 10:34:01,366 stacktrace       L0048 ERROR| 
2017-12-05 10:34:01,370 test             L0965 ERROR| ERROR 1-generic/hwinfo.py:Hwinfo.test -> TestSetupFail: Fail to install hwinfo required for this test.
2017-12-05 10:34:01,382 test             L0954 INFO | 
2017-12-05 10:34:02,385 sysinfo          L0111 DEBUG| Not logging /proc/pci (file does not exist)
2017-12-05 10:34:03,092 job              L0478 INFO | Test results available in /home/rc/avocado/job-results/job-2017-12-05T10.33-e4d53fb
```

**Comment by harish-24** [comment]
@fkromer It should be `self.cancel`. you can send a patch changing `self.error` to `self.cancel`.

**Comment by PraveenPenguin** [comment]
#973 will address  this issue , closing
