### ISSUE TITLE
Test Aiostress.test fails during command invocation

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#742]
When executing the test `Aiostress.test` with `sudo avocado run perf/aiostress.py:Aiostress.test` on Ubuntu 16.04.3 on an embedded linux system it fails due to `CmdError: Command './aio-stress foo' failed (rc=-11)` with status `ERROR`.

```
2017-12-05 08:07:10,766 test             L0381 INFO | START 1-perf/aiostress.py:Aiostress.test
2017-12-05 08:07:10,771 test             L0402 DEBUG| Test metadata:
2017-12-05 08:07:10,773 test             L0403 DEBUG|   filename: /home/rc/avocado-misc-tests/perf/aiostress.py
2017-12-05 08:07:11,066 software_manager L0692 DEBUG| apt-get version: 1.0.1ubuntu2
2017-12-05 08:07:11,073 process          L0389 INFO | Running '/usr/bin/dpkg -s gdebi-core'
2017-12-05 08:07:11,797 process          L0479 DEBUG| [stdout] Package: gdebi-core
2017-12-05 08:07:11,803 process          L0499 INFO | Command '/usr/bin/dpkg -s gdebi-core' finished with 0 after 0.692743062973s
2017-12-05 08:07:11,805 process          L0479 DEBUG| [stdout] Status: install ok installed
2017-12-05 08:07:11,811 process          L0479 DEBUG| [stdout] Priority: optional
2017-12-05 08:07:11,815 process          L0479 DEBUG| [stdout] Section: admin
2017-12-05 08:07:11,818 process          L0479 DEBUG| [stdout] Installed-Size: 132
2017-12-05 08:07:11,824 process          L0479 DEBUG| [stdout] Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
2017-12-05 08:07:11,827 process          L0479 DEBUG| [stdout] Architecture: all
2017-12-05 08:07:11,831 process          L0479 DEBUG| [stdout] Source: gdebi
2017-12-05 08:07:11,835 process          L0479 DEBUG| [stdout] Version: 0.9.5.3ubuntu3
2017-12-05 08:07:11,838 process          L0479 DEBUG| [stdout] Depends: python3:any (>= 3.3.2-2~), python3-apt, python3-debian, file
2017-12-05 08:07:11,842 process          L0479 DEBUG| [stdout] Suggests: xz-utils | xz-lzma
2017-12-05 08:07:11,846 process          L0479 DEBUG| [stdout] Description: simple tool to install deb files
2017-12-05 08:07:11,849 process          L0479 DEBUG| [stdout]  gdebi lets you install local deb packages resolving and installing
2017-12-05 08:07:11,853 process          L0479 DEBUG| [stdout]  its dependencies. apt does the same, but only for remote (http, ftp)
2017-12-05 08:07:11,857 process          L0479 DEBUG| [stdout]  located packages.
2017-12-05 08:07:11,861 process          L0479 DEBUG| [stdout]  .
2017-12-05 08:07:11,864 process          L0479 DEBUG| [stdout]  This package contains the libraries and command-line utility.
2017-12-05 08:07:11,868 process          L0479 DEBUG| [stdout] Original-Maintainer: Ubuntu Developers <ubuntu-dev-team@lists.alioth.debian.org>
2017-12-05 08:07:11,876 process          L0389 INFO | Running '/usr/bin/dpkg -s libaio1'
2017-12-05 08:07:12,562 process          L0479 DEBUG| [stdout] Package: libaio1
2017-12-05 08:07:12,569 process          L0499 INFO | Command '/usr/bin/dpkg -s libaio1' finished with 0 after 0.657629013062s
2017-12-05 08:07:12,573 process          L0479 DEBUG| [stdout] Status: install ok installed
2017-12-05 08:07:12,576 process          L0479 DEBUG| [stdout] Priority: optional
2017-12-05 08:07:12,580 process          L0479 DEBUG| [stdout] Section: libs
2017-12-05 08:07:12,584 process          L0479 DEBUG| [stdout] Installed-Size: 52
2017-12-05 08:07:12,588 process          L0479 DEBUG| [stdout] Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
2017-12-05 08:07:12,594 process          L0479 DEBUG| [stdout] Architecture: armhf
2017-12-05 08:07:12,598 process          L0479 DEBUG| [stdout] Multi-Arch: same
2017-12-05 08:07:12,602 process          L0479 DEBUG| [stdout] Source: libaio
2017-12-05 08:07:12,605 process          L0479 DEBUG| [stdout] Version: 0.3.109-4
2017-12-05 08:07:12,608 process          L0479 DEBUG| [stdout] Pre-Depends: multiarch-support
2017-12-05 08:07:12,612 process          L0479 DEBUG| [stdout] Description: Linux kernel AIO access library - shared library
2017-12-05 08:07:12,617 process          L0479 DEBUG| [stdout]  This library enables userspace to use Linux kernel asynchronous I/O
2017-12-05 08:07:12,622 process          L0479 DEBUG| [stdout]  system calls, important for the performance of databases and other
2017-12-05 08:07:12,625 process          L0479 DEBUG| [stdout]  advanced applications.
2017-12-05 08:07:12,628 process          L0479 DEBUG| [stdout] Original-Maintainer: Guillem Jover <guillem@debian.org>
2017-12-05 08:07:12,632 process          L0479 DEBUG| [stdout] Homepage: http://www.kernel.org/pub/linux/libs/aio/
2017-12-05 08:07:12,642 process          L0389 INFO | Running '/usr/bin/dpkg -s libaio-dev'
2017-12-05 08:07:13,360 process          L0479 DEBUG| [stdout] Package: libaio-dev
2017-12-05 08:07:13,365 process          L0479 DEBUG| [stdout] Status: install ok installed
2017-12-05 08:07:13,369 process          L0479 DEBUG| [stdout] Priority: optional
2017-12-05 08:07:13,371 process          L0499 INFO | Command '/usr/bin/dpkg -s libaio-dev' finished with 0 after 0.694006919861s
2017-12-05 08:07:13,377 process          L0479 DEBUG| [stdout] Section: libdevel
2017-12-05 08:07:13,381 process          L0479 DEBUG| [stdout] Installed-Size: 82
2017-12-05 08:07:13,384 process          L0479 DEBUG| [stdout] Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
2017-12-05 08:07:13,389 process          L0479 DEBUG| [stdout] Architecture: armhf
2017-12-05 08:07:13,392 process          L0479 DEBUG| [stdout] Source: libaio
2017-12-05 08:07:13,396 process          L0479 DEBUG| [stdout] Version: 0.3.109-4
2017-12-05 08:07:13,400 process          L0479 DEBUG| [stdout] Depends: libaio1 (= 0.3.109-4)
2017-12-05 08:07:13,403 process          L0479 DEBUG| [stdout] Description: Linux kernel AIO access library - development files
2017-12-05 08:07:13,407 process          L0479 DEBUG| [stdout]  This library enables userspace to use Linux kernel asynchronous I/O
2017-12-05 08:07:13,410 process          L0479 DEBUG| [stdout]  system calls, important for the performance of databases and other
2017-12-05 08:07:13,414 process          L0479 DEBUG| [stdout]  advanced applications.
2017-12-05 08:07:13,417 process          L0479 DEBUG| [stdout] Original-Maintainer: Guillem Jover <guillem@debian.org>
2017-12-05 08:07:13,421 process          L0479 DEBUG| [stdout] Homepage: http://www.kernel.org/pub/linux/libs/aio/
2017-12-05 08:07:13,436 download         L0066 INFO | Fetching https://oss.oracle.com/~mason/aio-stress/aio-stress.c -> /var/lib/avocado/data/cache/aio-stress.c.C0tx_A
2017-12-05 08:07:14,714 process          L0389 INFO | Running 'gcc -Wall -o aio-stress /var/lib/avocado/data/cache/aio-stress.c -laio -lpthread'
2017-12-05 08:07:15,577 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c: In function ‘worker’:
2017-12-05 08:07:15,583 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c:1175:3: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int’ [-Wformat=]
2017-12-05 08:07:15,587 process          L0479 DEBUG| [stderr]    t->stage_mb_trans, seconds);
2017-12-05 08:07:15,590 process          L0479 DEBUG| [stderr]    ^
2017-12-05 08:07:15,609 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c: In function ‘main’:
2017-12-05 08:07:15,614 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c:1455:10: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘off_t’ [-Wformat=]
2017-12-05 08:07:15,619 process          L0479 DEBUG| [stderr]           file_size, num_contexts);
2017-12-05 08:07:15,623 process          L0479 DEBUG| [stderr]           ^
2017-12-05 08:07:15,627 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c:1460:6: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘off_t’ [-Wformat=]
2017-12-05 08:07:15,630 process          L0479 DEBUG| [stderr]       file_size / (1024 * 1024), rec_len / 1024, depth, io_iter);
2017-12-05 08:07:15,634 process          L0479 DEBUG| [stderr]       ^
2017-12-05 08:07:15,639 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c:1465:6: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 6 has type ‘off_t’ [-Wformat=]
2017-12-05 08:07:15,643 process          L0479 DEBUG| [stderr]       context_offset / (1024 * 1024), verify ? "on" : "off");
2017-12-05 08:07:15,647 process          L0479 DEBUG| [stderr]       ^
2017-12-05 08:07:18,582 process          L0499 INFO | Command 'gcc -Wall -o aio-stress /var/lib/avocado/data/cache/aio-stress.c -laio -lpthread' finished with 0 after 3.82759809494s
2017-12-05 08:07:18,588 process          L0389 INFO | Running './aio-stress foo'
2017-12-05 08:07:18,632 process          L0479 DEBUG| [stderr] file size 1024MB, record size 0KB, depth 64, ios per iteration 64
2017-12-05 08:07:18,640 process          L0479 DEBUG| [stderr] max io_submit 8, buffer alignment set to 4KB
2017-12-05 08:07:18,643 process          L0499 INFO | Command './aio-stress foo' finished with -11 after 0.0169310569763s
2017-12-05 08:07:18,654 stacktrace       L0041 ERROR| 
2017-12-05 08:07:18,656 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:817
2017-12-05 08:07:18,666 stacktrace       L0047 ERROR| Traceback (most recent call last):
2017-12-05 08:07:18,668 stacktrace       L0047 ERROR|   File "/home/rc/avocado-misc-tests/perf/aiostress.py", line 74, in test
2017-12-05 08:07:18,671 stacktrace       L0047 ERROR|     process.run(cmd)
2017-12-05 08:07:18,675 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 1117, in run
2017-12-05 08:07:18,676 stacktrace       L0047 ERROR|     raise CmdError(cmd, sp.result)
2017-12-05 08:07:18,678 stacktrace       L0047 ERROR| CmdError: Command './aio-stress foo' failed (rc=-11)
2017-12-05 08:07:18,680 stacktrace       L0048 ERROR| 
2017-12-05 08:07:18,682 test             L0822 DEBUG| Local variables:
2017-12-05 08:07:19,027 test             L0825 DEBUG|  -> self <class 'aiostress.Aiostress'>: 1-perf/aiostress.py:Aiostress.test
2017-12-05 08:07:19,029 test             L0825 DEBUG|  -> cmd <type 'str'>: ./aio-stress foo
2017-12-05 08:07:19,035 test             L0278 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2017-12-05 08:07:19,040 test             L0278 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2017-12-05 08:07:19,044 test             L0950 ERROR| Traceback (most recent call last):

2017-12-05 08:07:19,046 test             L0950 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 888, in _run_avocado
    raise test_exception

2017-12-05 08:07:19,048 test             L0950 ERROR| CmdError: Command './aio-stress foo' failed (rc=-11)

2017-12-05 08:07:19,050 test             L0965 ERROR| ERROR 1-perf/aiostress.py:Aiostress.test -> CmdError: Command './aio-stress foo' failed (rc=-11)
```

**Comment by PraveenPenguin** [comment]
@fkromer still it seems me system resource issue , can you please let me  how much storage on your setup

**Comment by fkromer** [comment]
@PraveenPenguin The available memory available initially is about 1.3G. But after execution of avocado tests the available space shrank significantly (I can't remember how much it was). I run the test again with an "unused" image.

**Comment by fkromer** [comment]
@PraveenPenguin The test still fails with status `ERROR` right after starting the execution:

```
2017-12-07 14:02:56,302 test             L0381 INFO | START 1-avocado-misc-tests/perf/aiostress.py:Aiostress.test
2017-12-07 14:02:56,304 test             L0402 DEBUG| Test metadata:
2017-12-07 14:02:56,304 test             L0403 DEBUG|   filename: /home/rc/avocado-misc-tests/perf/aiostress.py
2017-12-07 14:02:56,371 software_manager L0692 DEBUG| apt-get version: 1.0.1ubuntu2
2017-12-07 14:02:56,372 process          L0389 INFO | Running '/usr/bin/dpkg -s gdebi-core'
2017-12-07 14:02:56,452 process          L0479 DEBUG| [stdout] Package: gdebi-core
2017-12-07 14:02:56,453 process          L0479 DEBUG| [stdout] Status: install ok installed
2017-12-07 14:02:56,453 process          L0479 DEBUG| [stdout] Priority: optional
2017-12-07 14:02:56,453 process          L0499 INFO | Command '/usr/bin/dpkg -s gdebi-core' finished with 0 after 0.076425075531s
2017-12-07 14:02:56,454 process          L0479 DEBUG| [stdout] Section: admin
2017-12-07 14:02:56,455 process          L0479 DEBUG| [stdout] Installed-Size: 132
2017-12-07 14:02:56,455 process          L0479 DEBUG| [stdout] Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
2017-12-07 14:02:56,455 process          L0479 DEBUG| [stdout] Architecture: all
2017-12-07 14:02:56,456 process          L0479 DEBUG| [stdout] Source: gdebi
2017-12-07 14:02:56,456 process          L0479 DEBUG| [stdout] Version: 0.9.5.3ubuntu3
2017-12-07 14:02:56,456 process          L0479 DEBUG| [stdout] Depends: python3:any (>= 3.3.2-2~), python3-apt, python3-debian, file
2017-12-07 14:02:56,457 process          L0479 DEBUG| [stdout] Suggests: xz-utils | xz-lzma
2017-12-07 14:02:56,457 process          L0479 DEBUG| [stdout] Description: simple tool to install deb files
2017-12-07 14:02:56,458 process          L0479 DEBUG| [stdout]  gdebi lets you install local deb packages resolving and installing
2017-12-07 14:02:56,459 process          L0479 DEBUG| [stdout]  its dependencies. apt does the same, but only for remote (http, ftp)
2017-12-07 14:02:56,459 process          L0479 DEBUG| [stdout]  located packages.
2017-12-07 14:02:56,459 process          L0479 DEBUG| [stdout]  .
2017-12-07 14:02:56,460 process          L0479 DEBUG| [stdout]  This package contains the libraries and command-line utility.
2017-12-07 14:02:56,460 process          L0479 DEBUG| [stdout] Original-Maintainer: Ubuntu Developers <ubuntu-dev-team@lists.alioth.debian.org>
2017-12-07 14:02:56,461 process          L0389 INFO | Running '/usr/bin/dpkg -s libaio1'
2017-12-07 14:02:56,544 process          L0479 DEBUG| [stdout] Package: libaio1
2017-12-07 14:02:56,545 process          L0479 DEBUG| [stdout] Status: install ok installed
2017-12-07 14:02:56,545 process          L0479 DEBUG| [stdout] Priority: optional
2017-12-07 14:02:56,545 process          L0479 DEBUG| [stdout] Section: libs
2017-12-07 14:02:56,546 process          L0479 DEBUG| [stdout] Installed-Size: 52
2017-12-07 14:02:56,546 process          L0499 INFO | Command '/usr/bin/dpkg -s libaio1' finished with 0 after 0.078803062439s
2017-12-07 14:02:56,546 process          L0479 DEBUG| [stdout] Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
2017-12-07 14:02:56,547 process          L0479 DEBUG| [stdout] Architecture: armhf
2017-12-07 14:02:56,547 process          L0479 DEBUG| [stdout] Multi-Arch: same
2017-12-07 14:02:56,548 process          L0479 DEBUG| [stdout] Source: libaio
2017-12-07 14:02:56,548 process          L0479 DEBUG| [stdout] Version: 0.3.109-4
2017-12-07 14:02:56,548 process          L0479 DEBUG| [stdout] Pre-Depends: multiarch-support
2017-12-07 14:02:56,549 process          L0479 DEBUG| [stdout] Description: Linux kernel AIO access library - shared library
2017-12-07 14:02:56,549 process          L0479 DEBUG| [stdout]  This library enables userspace to use Linux kernel asynchronous I/O
2017-12-07 14:02:56,549 process          L0479 DEBUG| [stdout]  system calls, important for the performance of databases and other
2017-12-07 14:02:56,550 process          L0479 DEBUG| [stdout]  advanced applications.
2017-12-07 14:02:56,550 process          L0479 DEBUG| [stdout] Original-Maintainer: Guillem Jover <guillem@debian.org>
2017-12-07 14:02:56,550 process          L0479 DEBUG| [stdout] Homepage: http://www.kernel.org/pub/linux/libs/aio/
2017-12-07 14:02:56,551 process          L0389 INFO | Running '/usr/bin/dpkg -s libaio-dev'
2017-12-07 14:02:56,632 process          L0479 DEBUG| [stdout] Package: libaio-dev
2017-12-07 14:02:56,633 process          L0479 DEBUG| [stdout] Status: install ok installed
2017-12-07 14:02:56,633 process          L0499 INFO | Command '/usr/bin/dpkg -s libaio-dev' finished with 0 after 0.0779430866241s
2017-12-07 14:02:56,634 process          L0479 DEBUG| [stdout] Priority: optional
2017-12-07 14:02:56,634 process          L0479 DEBUG| [stdout] Section: libdevel
2017-12-07 14:02:56,635 process          L0479 DEBUG| [stdout] Installed-Size: 82
2017-12-07 14:02:56,635 process          L0479 DEBUG| [stdout] Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
2017-12-07 14:02:56,635 process          L0479 DEBUG| [stdout] Architecture: armhf
2017-12-07 14:02:56,636 process          L0479 DEBUG| [stdout] Source: libaio
2017-12-07 14:02:56,636 process          L0479 DEBUG| [stdout] Version: 0.3.109-4
2017-12-07 14:02:56,636 process          L0479 DEBUG| [stdout] Depends: libaio1 (= 0.3.109-4)
2017-12-07 14:02:56,637 process          L0479 DEBUG| [stdout] Description: Linux kernel AIO access library - development files
2017-12-07 14:02:56,637 process          L0479 DEBUG| [stdout]  This library enables userspace to use Linux kernel asynchronous I/O
2017-12-07 14:02:56,638 process          L0479 DEBUG| [stdout]  system calls, important for the performance of databases and other
2017-12-07 14:02:56,638 process          L0479 DEBUG| [stdout]  advanced applications.
2017-12-07 14:02:56,638 process          L0479 DEBUG| [stdout] Original-Maintainer: Guillem Jover <guillem@debian.org>
2017-12-07 14:02:56,639 process          L0479 DEBUG| [stdout] Homepage: http://www.kernel.org/pub/linux/libs/aio/
2017-12-07 14:02:56,647 process          L0389 INFO | Running 'gcc -Wall -o aio-stress /var/lib/avocado/data/cache/aio-stress.c -laio -lpthread'
2017-12-07 14:02:56,747 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c: In function ‘worker’:
2017-12-07 14:02:56,748 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c:1175:3: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int’ [-Wformat=]
2017-12-07 14:02:56,749 process          L0479 DEBUG| [stderr]    t->stage_mb_trans, seconds);
2017-12-07 14:02:56,749 process          L0479 DEBUG| [stderr]    ^
2017-12-07 14:02:56,752 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c: In function ‘main’:
2017-12-07 14:02:56,753 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c:1455:10: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘off_t’ [-Wformat=]
2017-12-07 14:02:56,754 process          L0479 DEBUG| [stderr]           file_size, num_contexts);
2017-12-07 14:02:56,754 process          L0479 DEBUG| [stderr]           ^
2017-12-07 14:02:56,755 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c:1460:6: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘off_t’ [-Wformat=]
2017-12-07 14:02:56,755 process          L0479 DEBUG| [stderr]       file_size / (1024 * 1024), rec_len / 1024, depth, io_iter);
2017-12-07 14:02:56,755 process          L0479 DEBUG| [stderr]       ^
2017-12-07 14:02:56,756 process          L0479 DEBUG| [stderr] /var/lib/avocado/data/cache/aio-stress.c:1465:6: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 6 has type ‘off_t’ [-Wformat=]
2017-12-07 14:02:56,756 process          L0479 DEBUG| [stderr]       context_offset / (1024 * 1024), verify ? "on" : "off");
2017-12-07 14:02:56,757 process          L0479 DEBUG| [stderr]       ^
2017-12-07 14:02:57,108 process          L0499 INFO | Command 'gcc -Wall -o aio-stress /var/lib/avocado/data/cache/aio-stress.c -laio -lpthread' finished with 0 after 0.45584821701s
2017-12-07 14:02:57,109 process          L0389 INFO | Running './aio-stress foo'
2017-12-07 14:02:57,117 process          L0479 DEBUG| [stderr] file size 1024MB, record size 0KB, depth 64, ios per iteration 64
2017-12-07 14:02:57,117 process          L0499 INFO | Command './aio-stress foo' finished with -11 after 0.00217509269714s
2017-12-07 14:02:57,118 process          L0479 DEBUG| [stderr] max io_submit 8, buffer alignment set to 4KB
2017-12-07 14:02:57,119 stacktrace       L0041 ERROR| 
2017-12-07 14:02:57,119 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:817
2017-12-07 14:02:57,120 stacktrace       L0047 ERROR| Traceback (most recent call last):
2017-12-07 14:02:57,120 stacktrace       L0047 ERROR|   File "/home/rc/avocado-misc-tests/perf/aiostress.py", line 74, in test
2017-12-07 14:02:57,120 stacktrace       L0047 ERROR|     process.run(cmd)
2017-12-07 14:02:57,121 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/utils/process.py", line 1117, in run
2017-12-07 14:02:57,122 stacktrace       L0047 ERROR|     raise CmdError(cmd, sp.result)
2017-12-07 14:02:57,122 stacktrace       L0047 ERROR| CmdError: Command './aio-stress foo' failed (rc=-11)
2017-12-07 14:02:57,123 stacktrace       L0048 ERROR| 
2017-12-07 14:02:57,123 test             L0822 DEBUG| Local variables:
2017-12-07 14:02:57,178 test             L0825 DEBUG|  -> self <class 'aiostress.Aiostress'>: 1-avocado-misc-tests/perf/aiostress.py:Aiostress.test
2017-12-07 14:02:57,178 test             L0825 DEBUG|  -> cmd <type 'str'>: ./aio-stress foo
2017-12-07 14:02:57,179 test             L0278 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2017-12-07 14:02:57,180 test             L0278 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2017-12-07 14:02:57,180 test             L0950 ERROR| Traceback (most recent call last):

2017-12-07 14:02:57,180 test             L0950 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 888, in _run_avocado
    raise test_exception

2017-12-07 14:02:57,180 test             L0950 ERROR| CmdError: Command './aio-stress foo' failed (rc=-11)

2017-12-07 14:02:57,181 test             L0965 ERROR| ERROR 1-avocado-misc-tests/perf/aiostress.py:Aiostress.test -> CmdError: Command './aio-stress foo' failed (rc=-11)
```

**Comment by PraveenPenguin** [comment]
am not able to recreate this issue any more please try on the recent code base, if still facing issue feel free to reopen
