### ISSUE TITLE
Configuration of sosreport.py

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#753]
How do I have to configure `sosreport.py` for Ubuntu14.04 armhf? (If I run the test with the default configuration the test fails with status `FAIL`.)

```
2017-12-08 16:10:34,935 process          L0574 INFO | Command 'sosreport --batch --tmp-dir=/var/tmp/tmpeYYnPO -s /home/' finished with 0 after 11.2995071411s
2017-12-08 16:10:35,358 stacktrace       L0041 ERROR| 
2017-12-08 16:10:35,358 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:819
2017-12-08 16:10:35,361 stacktrace       L0047 ERROR| Traceback (most recent call last):
2017-12-08 16:10:35,361 stacktrace       L0047 ERROR|   File "/home/rc/avocado-misc-tests/generic/sosreport.py", line 160, in test
2017-12-08 16:10:35,362 stacktrace       L0047 ERROR|     self.is_fail)
2017-12-08 16:10:35,362 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 988, in fail
2017-12-08 16:10:35,362 stacktrace       L0047 ERROR|     raise exceptions.TestFail(message)
2017-12-08 16:10:35,362 stacktrace       L0047 ERROR| TestFail: 1 command(s) failed in sosreport tool verification
2017-12-08 16:10:35,362 stacktrace       L0048 ERROR| 
2017-12-08 16:10:35,363 test             L0824 DEBUG| Local variables:
2017-12-08 16:10:35,404 test             L0827 DEBUG|  -> files <type 'str'>: proc/device-tree/
2017-12-08 16:10:35,404 test             L0827 DEBUG|  -> file_name_xz2 <type 'str'>: /var/tmp/tmpeYYnPO/sosreport-rc-visard-02911982-20171208160952.tar.xz
2017-12-08 16:10:35,404 test             L0827 DEBUG|  -> sosreport_dir <type 'str'>: /var/tmp/sosreport-rc-visard-02911982-20171208161010/sos_reports
2017-12-08 16:10:35,404 test             L0827 DEBUG|  -> list_item <type 'str'>: --all-logs
2017-12-08 16:10:35,405 test             L0827 DEBUG|  -> dir_name <type 'str'>: /var/tmp/sosreport-rc-visard-02911982-20171208161010
2017-12-08 16:10:35,405 test             L0827 DEBUG|  -> file_name <type 'str'>: /root/sosreport-rc-visard-02911982-20171208160836.tar.xz
2017-12-08 16:10:35,405 test             L0827 DEBUG|  -> file_name_bz2 <type 'str'>: /var/tmp/tmpeYYnPO/sosreport-rc-visard-02911982-20171208160855.tar.bz2
2017-12-08 16:10:35,405 test             L0827 DEBUG|  -> cmd <type 'str'>: sosreport --batch --tmp-dir=/var/tmp/tmpeYYnPO --all-logs
2017-12-08 16:10:35,405 test             L0827 DEBUG|  -> list <type 'list'>: ['--all-logs']
2017-12-08 16:10:35,406 test             L0827 DEBUG|  -> self <class 'sosreport.sosreport_test'>: 1-sosreport.py:sosreport_test.test
2017-12-08 16:10:35,406 test             L0827 DEBUG|  -> file_name_gz <type 'str'>: /var/tmp/tmpeYYnPO/sosreport-rc-visard-02911982-20171208160915.tar.gz
2017-12-08 16:10:35,406 test             L0827 DEBUG|  -> case_id <type 'str'>: testid
2017-12-08 16:10:35,406 test             L0827 DEBUG|  -> md5_sum1 <type 'str'>: 35b6fe556e7fdf1ebab0cc3084b29430
2017-12-08 16:10:35,406 test             L0827 DEBUG|  -> md5_sum2 <type 'str'>: 35b6fe556e7fdf1ebab0cc3084b29430
2017-12-08 16:10:35,407 test             L0827 DEBUG|  -> file_list <type 'list'>: ['proc/device-tree/']
2017-12-08 16:10:35,407 test             L0827 DEBUG|  -> file_name_xz <type 'str'>: /var/tmp/tmpeYYnPO/sosreport-rc-visard-02911982-20171208160933.tar.xz
2017-12-08 16:10:35,407 test             L0827 DEBUG|  -> directory_name <type 'str'>: /var/tmp/tmpeYYnPO
2017-12-08 16:10:35,407 test             L0827 DEBUG|  -> file_path <type 'str'>: /var/tmp/sosreport-rc-visard-02911982-20171208161010/proc/device-tree/
2017-12-08 16:10:35,407 test             L0827 DEBUG|  -> ticket_id <type 'str'>: testid
2017-12-08 16:10:35,408 test             L0278 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2017-12-08 16:10:35,409 test             L0278 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2017-12-08 16:10:35,409 test             L0970 ERROR| FAIL 1-sosreport.py:sosreport_test.test -> TestFail: 1 command(s) failed in sosreport tool verification
```

**Comment by abdhaleegit** [comment]
@fkromer '-s' or '--sysroot' options is available only with latest version of sos package.
check your sos package should be sos-3.3-4 and later.
sos-3.1 does not have '-s' support.

please upgrade your rpm package.

**Comment by fkromer** [comment]
@abdhaleegit If I run the test with `sosreport v3.4` and `sudo` I still get a `FAIL`. 

```
$ sudo avocado run generic/sosreport.py:sosreport_test.test
JOB ID     : 31fdb83b44a4fcd9ab379fa3c72ef25626a8e321
JOB LOG    : /home/rc/avocado/job-results/job-2018-01-03T11.10-31fdb83/job.log
 (1/1) generic/sosreport.py:sosreport_test.test: FAIL (453.51 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 454.08 s
```

The job log file looks still the same:

```
$ cat /home/rc/avocado/job-results/job-2018-01-03T11.10-31fdb83/job.log | grep -B 33 "FAIL 1"
2018-01-03 11:18:06,041 process          L0604 INFO | Command 'sosreport --batch --tmp-dir=/var/tmp/tmpxRILTx -s /home/' finished with 0 after 11.4317080975s
2018-01-03 11:18:06,514 stacktrace       L0041 ERROR| 
2018-01-03 11:18:06,515 stacktrace       L0044 ERROR| Reproduced traceback from: /usr/local/lib/python2.7/dist-packages/avocado/core/test.py:834
2018-01-03 11:18:06,517 stacktrace       L0047 ERROR| Traceback (most recent call last):
2018-01-03 11:18:06,518 stacktrace       L0047 ERROR|   File "/home/rc/avocado-misc-tests/generic/sosreport.py", line 160, in test
2018-01-03 11:18:06,518 stacktrace       L0047 ERROR|     self.is_fail)
2018-01-03 11:18:06,518 stacktrace       L0047 ERROR|   File "/usr/local/lib/python2.7/dist-packages/avocado/core/test.py", line 1029, in fail
2018-01-03 11:18:06,518 stacktrace       L0047 ERROR|     raise exceptions.TestFail(message)
2018-01-03 11:18:06,518 stacktrace       L0047 ERROR| TestFail: 1 command(s) failed in sosreport tool verification
2018-01-03 11:18:06,518 stacktrace       L0048 ERROR| 
2018-01-03 11:18:06,519 test             L0839 DEBUG| Local variables:
2018-01-03 11:18:06,555 test             L0842 DEBUG|  -> files <type 'str'>: proc/device-tree/
2018-01-03 11:18:06,556 test             L0842 DEBUG|  -> file_name_xz2 <type 'str'>: /var/tmp/tmpxRILTx/sosreport-rc-visard-02911982-20180103111719.tar.xz
2018-01-03 11:18:06,556 test             L0842 DEBUG|  -> sosreport_dir <type 'str'>: /var/tmp/sosreport-rc-visard-02911982-20180103111740/sos_reports
2018-01-03 11:18:06,556 test             L0842 DEBUG|  -> list_item <type 'str'>: --all-logs
2018-01-03 11:18:06,556 test             L0842 DEBUG|  -> dir_name <type 'str'>: /var/tmp/sosreport-rc-visard-02911982-20180103111740
2018-01-03 11:18:06,556 test             L0842 DEBUG|  -> file_name <type 'str'>: /root/sosreport-rc-visard-02911982-20180103111557.tar.xz
2018-01-03 11:18:06,557 test             L0842 DEBUG|  -> file_name_bz2 <type 'str'>: /var/tmp/tmpxRILTx/sosreport-rc-visard-02911982-20180103111617.tar.bz2
2018-01-03 11:18:06,557 test             L0842 DEBUG|  -> cmd <type 'str'>: sosreport --batch --tmp-dir=/var/tmp/tmpxRILTx --all-logs
2018-01-03 11:18:06,557 test             L0842 DEBUG|  -> list <type 'list'>: ['--all-logs']
2018-01-03 11:18:06,557 test             L0842 DEBUG|  -> self <class 'sosreport.sosreport_test'>: 1-generic/sosreport.py:sosreport_test.test
2018-01-03 11:18:06,558 test             L0842 DEBUG|  -> file_name_gz <type 'str'>: /var/tmp/tmpxRILTx/sosreport-rc-visard-02911982-20180103111639.tar.gz
2018-01-03 11:18:06,558 test             L0842 DEBUG|  -> case_id <type 'str'>: testid
2018-01-03 11:18:06,558 test             L0842 DEBUG|  -> md5_sum1 <type 'str'>: 27859eae7c5f0a71f75be7452d9c794b
2018-01-03 11:18:06,558 test             L0842 DEBUG|  -> md5_sum2 <type 'str'>: 27859eae7c5f0a71f75be7452d9c794b
2018-01-03 11:18:06,558 test             L0842 DEBUG|  -> file_list <type 'list'>: ['proc/device-tree/']
2018-01-03 11:18:06,559 test             L0842 DEBUG|  -> file_name_xz <type 'str'>: /var/tmp/tmpxRILTx/sosreport-rc-visard-02911982-20180103111659.tar.xz
2018-01-03 11:18:06,559 test             L0842 DEBUG|  -> directory_name <type 'str'>: /var/tmp/tmpxRILTx
2018-01-03 11:18:06,559 test             L0842 DEBUG|  -> file_path <type 'str'>: /var/tmp/sosreport-rc-visard-02911982-20180103111740/proc/device-tree/
2018-01-03 11:18:06,559 test             L0842 DEBUG|  -> ticket_id <type 'str'>: testid
2018-01-03 11:18:06,560 test             L0286 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, test, file)
2018-01-03 11:18:06,560 test             L0286 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, test, file)
2018-01-03 11:18:06,561 test             L0286 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, test, file)
2018-01-03 11:18:06,561 test             L1011 ERROR| FAIL 1-generic/sosreport.py:sosreport_test.test -> TestFail: 1 command(s) failed in sosreport tool verification
```
